### ISSUE TITLE
[Bug]: Can't access to any bottle I created.

### ISSUE THREAD

**Issue by v38armageddon** [bottlesdevs/Bottles#1610] opened 2022-06-13 08:51 UTC
### Describe the bug

I wanted access to a program I installed on Bottles but when I click on my bottle, nothing happened. I update my system, same problem.

When I open via a Terminal, I have this error showing up:
```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/usr/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 336, in set_config
    self.switch_runtime.handler_block_by_func(self.__toggle_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_runtime of <bottle_preferences.PreferencesView object at 0x7f7ad17c88c0 (DetailsPreferences at 0x55a7fc6a3200)>>
```

### To Reproduce

1. Open Bottles
2. Select any created bottle

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.3-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Disk:
    Total: 180367654912
    Free: 154354171904
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 13.2GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Screenshot of the bug:
![image](https://user-images.githubusercontent.com/69727502/173316357-a2d3d5a0-117e-4173-8c45-68c45bd7edd4.png)

**Comment by mirkobrombin** [comment] 2022-06-13 11:51
duplicate of #1600

**Closed by mirkobrombin** 2022-06-13 11:51 UTC
