### ISSUE TITLE
[Bug]: Crash when starting

### ISSUE THREAD

**Issue by LeviMarvin** [bottlesdevs/Bottles#2424] opened 2022-12-21 18:31 UTC
### Describe the bug

Crashed when starting the Bottles

### To Reproduce

!. Install Bottles
2. Run

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Troubleshooting Logs

```shell
name 'requests' is not defined  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 165, in checks
    self.check_nvapi(install_latest)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 459, in check_nvapi
    res = self.__check_component("nvapi", install_latest)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 517, in __check_component
    self.component_manager.install(component_type, component_version)

  File "/app/share/bottles/bottles/backend/managers/component.py", line 355, in install
    res = self.download(

  File "/app/share/bottles/bottles/backend/managers/component.py", line 203, in download
    except requests.exceptions.RequestException:
```

**Comment by mirkobrombin** [comment] 2023-01-05 15:48
duplicate of #2420

**Closed by mirkobrombin** 2023-01-05 15:48 UTC
