### ISSUE TITLE
[Bug]: No librrary icon in bar

### ISSUE THREAD

**Issue by Pyntux** [bottlesdevs/Bottles#2162] opened 2022-10-14 11:26 UTC
### Describe the bug

There is no librrary icon (if I am not wrong, that would be "heart" icon) in heder/bar app...

![bottles_no_librrary_icon](https://user-images.githubusercontent.com/2485335/195835289-03aef5fd-f48e-4714-862c-08e0a20ac46c.png)

### To Reproduce

1. Open Bottles app.
2.  Look for librrary icon.

### Package

Flatpak from Flathub

### Distribution

Arch linux + KDE Plasma

### Troubleshooting Logs

```shell
Version: 2022.10.14
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.1-arch2-1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8351240192
    Free: 8351096832
RAM:
    MemTotal: "16.7\_GB"
    MemAvailable: "13.2\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment] 2022-10-14 12:07
Duplicate of https://github.com/bottlesdevs/Bottles/issues/1627

Read https://github.com/bottlesdevs/Bottles/issues/1627#issuecomment-1156398604

**Closed by mirkobrombin** 2022-10-14 12:07 UTC
