### ISSUE TITLE
[Crash report]  run() got multiple values fo

### ISSUE THREAD

**Issue by jessieprovo** [bottlesdevs/Bottles#990] opened 2022-01-30 00:35 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.1.28-trento

**Log**
```python3
run() got multiple values for argument 'file'  File "/app/share/bottles/bottles/utils.py", line 339, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 101, in run
    return self.__launch_lnk()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 180, in __launch_lnk
    res = start.run(

```

**Comment by mirkobrombin** [comment] 2022-01-30 06:43
Duplicate of #986

**Closed by mirkobrombin** 2022-01-30 06:43 UTC
