### ISSUE TITLE
[Crash report]  checks() got an unexpected keyword argument 'after'

### ISSUE THREAD

**Issue by peterkingsbury** [bottlesdevs/Bottles#828] opened 2021-12-20 01:42 UTC
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
(20:41:00) INFO Performing Bottles checks... 
(20:41:00) INFO Runners found:
	 - sys-wine-5.0
 
(20:41:02) INFO Bottles Started! 
(20:42:20) ERROR Error while running async job: <bound method Manager.checks of <bottles.backend.manager.Manager object at 0x7fe231f89be0>>
Exception: checks() got an unexpected keyword argument 'after' 
  File "/tmp/.mount_BottleGjSVtO///usr/local/share/bottles/bottles/utils.py", line 335, in __target
```

**Comment by mirkobrombin** [comment] 2021-12-20 06:12
Duplicate of #784

**Closed by mirkobrombin** 2021-12-20 06:12 UTC
