### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by mac2098** [bottlesdevs/Bottles#511] opened 2021-09-01 00:31 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.8.14-treviso

**Log**
```python3
[Errno 2] No such file or directory: '/home/mac/.local/share/bottles/bottles/windows-bottle/bottle.yml'  File "/usr/share/bottles/bottles/utils.py", line 236, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/runner.py", line 1167, in async_create_bottle
    with open(f"{bottle_complete_path}/bottle.yml", "w") as conf_file:

```

**Comment by mirkobrombin** [comment] 2021-09-01 05:37
duplicate of #504

**Closed by mirkobrombin** 2021-09-01 05:37 UTC
