### ISSUE TITLE
[Bug]: Crash Report

### ISSUE THREAD

**Issue by MandiYang** [bottlesdevs/Bottles#2327] opened 2022-11-26 14:22 UTC
### Describe the bug

```
'NoneType' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 100, in run_program
    if program.get("dxvk") != dxvk:
```

### To Reproduce

1. Running windows exe file
2. No response from the exe file so I closed bottles
3. Open up bottles again
4. Se error

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-53-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4109651968
    Free: 4109508608
RAM:
    MemTotal: "8.2\_GB"
    MemAvailable: "4.5\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment] 2022-11-26 16:06
duplicate of https://github.com/bottlesdevs/Bottles/issues/2252

**Closed by mirkobrombin** 2022-11-26 16:06 UTC
