### ISSUE TITLE
[Crash report]  'NoneType' object has no att

### ISSUE THREAD

**Issue by apcamargo** [bottlesdevs/Bottles#1821] opened 2022-07-22 14:54 UTC
This happened when trying to create a Steam shortcut via "Add to Steam".

**Details**
* **package**: Flatpak
* **version**: 2022.7.14-brescia-3

**Log**
```python3
'NoneType' object has no attribute 'get'  File "/app/share/bottles/bottles/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 521, in add_shortcut
    "StartDir": ManagerUtils.get_bottle_path(self.config),

  File "/app/share/bottles/bottles/backend/utils/manager.py", line 85, in get_bottle_path
    if config.get("IsLayer"):

```

**Comment by mirkobrombin** [comment] 2022-07-22 16:03
duplicate of #1788 

Please when the crash dialog appear, always look at this section to avoid duplicates
![image](https://user-images.githubusercontent.com/9479903/180478972-15dfee22-87ba-4df6-9846-c95db303305d.png)

**Closed by mirkobrombin** 2022-07-22 16:03 UTC
