### ISSUE TITLE
[Bug]: `str` object has no attribute `Parameters`

### ISSUE THREAD

**Issue by hagiomassaru** [bottlesdevs/Bottles#2926] opened 2023-06-13 14:56 UTC
### Describe the bug

'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk
 

### To Reproduce

After using it for a while and trying to close the app, it ended up freezing everything.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-73-generic
Disk:
    Total: 8349253632
    Free: 8349097984
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 10.2GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk
```

**Comment by jannuary** [comment] 2023-06-13 15:00
Duplicate of #2908

**Closed** 2023-06-13 14:59 UTC
