### ISSUE TITLE
[Bug]: Crash report

### ISSUE THREAD

**Issue by CBx86** [bottlesdevs/Bottles#2322] opened 2022-11-24 14:47 UTC
### Describe the bug

'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 26, in send_status
    if status == 0 and not WineServer(self.config).is_alive():

  File "/app/share/bottles/bottles/backend/utils/decorators.py", line 44, in wrapped_f
    return f(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 25, in is_alive
    if not config.get("Runner"):

### To Reproduce

Start Bottle

### Package

Flatpak from Flathub

### Distribution

FC37

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.9-300.fc37.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8273215488
    Free: 8273072128
RAM:
    MemTotal: "16.5\_GB"
    MemAvailable: "12.9\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-11-24 15:51
Duplicate of #2307

**Closed by mirkobrombin** 2022-11-24 15:51 UTC
