### ISSUE TITLE
[Crash report]  checks() got an unexpected k

### ISSUE THREAD

**Issue by teratux** [bottlesdevs/Bottles#832] opened 2021-12-20 04:59 UTC
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottlewnFP4D///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by teratux** [comment] 2021-12-20 05:37
> This crash report was generated by Bottles.
> 
> **Details**
> 
> * **package**: AppImage
> * **version**: 2021.12.14-treviso
> 
> **Log**
> 
> ```python
> checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottlewnFP4D///usr/local/share/bottles/bottles/utils.py", line 335, in __target
>     result = self.task_func(*args, **kwargs)
> ```

umm I just recently read about #784 and it seems anything above 2021.12.14-treviso fixes it, so I'll redownload and try again.  It might be good to just remove the 2021.12.14-treviso version from the tags since downloading runners doesn't work

**Comment by teratux** [comment] 2021-12-20 05:46
well I'm past that issue, now I get another one:

```bash
 (00:48:15) INFO Installing component: [dxvk-1.9.2]. 
(00:48:15) ERROR Extraction failed! Archive ends earlier than expected. 
(00:48:15) WARNING No dxvk found. 
```
this gets repeated continously in the console

**Comment by mirkobrombin** [comment] 2021-12-20 06:09
Duplicate of  #784

About your second problem: can be caused by an interrupted download. If the problem persist open a specific issue please.

**Closed by mirkobrombin** 2021-12-20 06:09 UTC
