### ISSUE TITLE
[Bug]: EA Launcher won’t load on Steam Deck; all manifest dependencies and parameters match

### ISSUE THREAD

**Issue by BillyParsons** [bottlesdevs/Bottles#1576] opened 2022-06-03 22:48 UTC
### Describe the bug

Trying to access the EA Launcher through “desktop mode” on a Steam Deck. App will not load through Bottles despite having all dependencies and parameters set according to the EA Launcher manifest. 

### To Reproduce

Steps:

Install Bottles from Discover;
Create a bottle (all environments tried);
Download all dependencies and set all parameters according to the EA Launcher manifest in the Installers tab;
Install EA Launcher from the Installers tab

From here, the installer opens and allows you to select “Let’s Go!” After that, the app installs. Once complete, the app does not launch and the screen shows a blank dark blue/black rectangle where the app should be. 

### Package

Flatpak from Flathub

### Distribution

Steam Deck

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 12.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

**Comment by mirkobrombin** [comment] 2022-06-04 04:55
Duplicate of https://github.com/bottlesdevs/programs/issues/75

**Closed by mirkobrombin** 2022-06-04 04:55 UTC
Labels: Invalid, Not a bug
