### ISSUE TITLE
[Bug]: Failed to install dependency : Microsoft Arial Font

### ISSUE THREAD

**Issue by MarcEste** [bottlesdevs/Bottles#3359] opened 2024-05-02 14:42 UTC
### Describe the bug

I installed Bottles and then tried to create my first bottle; it did not create a bottle and showed the message 'Failed to install dependency : Microsoft Arial Font'

### To Reproduce

create a new bottle (first bottle after installing)

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.3

### Debugging Information

```shell
Debugging information :

Official Package: true
Version: '51.11'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-171-04/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-105-generic
Disk:
    Total: 8268443648
    Free: 8268259328
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 13.7GiB
Bottles_envs: null
```

**Comment by igor2x** [comment] 2024-05-02 15:15
Today I installed Bluefin 39 (this is a sister project of Fedora Atom Silverblue) inside VirtualBox virtual machine.
Flatpak software is already installed on this Linux distribution and configured to use Flathub.org.

1. Installed Bottles flatpak from Flathub.org.
2. Clicked on "Create New Bottle" button, type in some new name, left default Environment = Application and "Create" button. Error appears:
```
Generating bottle configuration…
The Wine config is being updated…
Wine config updated!
Running as Flatpak, sandboxing userdir…
Setting Windows version…
Apply CMD default settings…
Optimizing environment…
Applying environment: application…
Installing DXVK…
Installing VKD3D…
Installing dependency: Microsoft Arial Font …
Failed to install dependency: Microsoft Arial Font
```
3. From About Bottles | Troubleshooting | Debugging Information:
```
Official Package: true
Version: '51.11'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors: {}
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.7-200.fc39.x86_64
Disk:
    Total: 2050301952
    Free: 2050138112
RAM:
    MemTotal: 3.8GiB
    MemAvailable: 1.7GiB
Bottles_envs: null
```

**Comment by Leigars** [comment] 2024-05-02 15:31
I have the same issue.

**Comment by Dhizaes** [comment] 2024-05-02 17:46
Looks like it is fixed. I'm sure it wasn't related to Bottles but SourceForge or any related CDN server.

**Comment by igor2x** [comment] 2024-05-02 19:13
Now it also works for me. Maybe "Microsoft Arial Font" is downloaded from somewhere, but I can't know because error message is not descriptive. If possible, may I suggest to provide more descriptive error message, like why dependency fail to install.

**Comment by mirkobrombin** [comment] 2024-05-02 20:53
Fixed by https://github.com/bottlesdevs/dependencies/commit/a05a4b83563d86b151c868617abf9eeb2bfbed6e

**Closed by mirkobrombin** 2024-05-02 20:53 UTC

**Comment by Rustring** [comment] 2024-08-26 07:18
@mirkobrombin the issue is back, now I have it

**Comment by Rustring** [comment] 2024-08-26 07:19
Also the Verdan32 and Trubes32 fonts also fail to install
