### ISSUE TITLE
[Crash report]  'Sketchup2017'  

### ISSUE THREAD

**Issue by jma1795** [bottlesdevs/Bottles#706] opened 2021-11-11 12:11 UTC
This crash report was generated by Bottles. I'm unable to remove this container and every time I do bottles crashes. I was finally able to manually go and delete the bottle in the system files to resolve the issue.

**Details**
* **package**: Flatpak
* **version**: 2021.10.28-treviso

**Log**
```python3
'Sketchup2017'  File "/app/share/bottles/bottles/utils.py", line 298, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 1178, in async_delete_bottle
    del self.local_bottles[config.get("Path")]

```

**Comment by mirkobrombin** [comment] 2021-11-11 13:21
Duplicate of #676

**Closed by mirkobrombin** 2021-11-11 13:21 UTC
