### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bjnobre** [bottlesdevs/Bottles#2339] opened 2022-11-30 13:23 UTC
### Describe the bug

Just after I upgrade Ubuntu

### To Reproduce

1. It crashes when I try do open it

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Troubleshooting Logs

```shell
'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 26, in send_status
    if status == 0 and not WineServer(self.config).is_alive():

  File "/app/share/bottles/bottles/backend/utils/decorators.py", line 44, in wrapped_f
    return f(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 25, in is_alive
    if not config.get("Runner"):
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment] 2022-11-30 13:58
Duplicate of https://github.com/bottlesdevs/Bottles/issues/2336

**Closed** 2022-11-30 13:59 UTC
