### ISSUE TITLE
[Request] Being able to open programs in a file manager

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#132] opened 2021-02-24 03:56 UTC
**Is your feature request related to a problem? Please describe.**
No,but I would like a file manager integration,cause that would be much faster.

**Describe the solution you'd like**
What I mean is that you can right click a .exe or folder with .exe instide in your file manager,then select "open with Bottles",then a window pops up that asks "Do you want to add/install/launch a program"
If you click on "add":Then you can add a .exe or whole folder to a existing prefix or create a prefix new prefix and select the wine version for that and add the program to there.

If you click on "install":Then you can install a program to an existing prefix or create a new one and install it there with a selected wine version.

If you click on "launch":Then it will launch the program with it's selected wine version and prefix if it's already added to Bottles. And if you didn't add that .exe to Bottles and hit "launch,then it will ask you which wine version you want to launch it with and then launches it once with that wine version and it will use a test prefix that exists only for that purpose.

And also,being able to do that for multiple files at once would be cool.
I would find this feature useful,cause then you can do everything directly in the file manager.

And if you click on "add",then you are also able to select "add whole folder".

There are 2 more options that would be cool:
If you select "open with wine cmd":Then it asks which wine version you want to choose and then opens that file in wine cmd.

If you select "add prefix":Then it will add that prefix to Bottles.

And also,it would be cool if you could create a new prefix in a file manager directly.

**Comment by mirkobrombin** [comment] 2021-02-24 06:18
This feature already exists (at least for Flatpak and native packages).What package are you using?

**Comment by Toadfield** [comment] 2021-02-24 10:13
I use the AUR version.
Does that feature exactly work how I described it?

**Comment by mirkobrombin** [comment] 2021-02-24 10:25
Should work. Please contact the maintainer from the AUR repository because the AUR package is not an official supported.

**Comment by Toadfield** [comment] 2021-03-02 15:30
It works,but what about the other features?
Will they be added in the future?

**Comment by mirkobrombin** [comment] 2021-03-02 18:31
> It works,but what about the other features?
> Will they be added in the future?

Probably yes but I can't make any promises right now

**Comment by mirkobrombin** [comment] 2021-06-11 10:02
> > This feature already exists (at least for Flatpak and native packages).What package are you using?
> 
> I'm using the Flatpak version with GNOME 40 on Fedora 34 and don't see a way to launch .exe files with Nautilus.
> 
> I have Bottles version 3.1.11 (latest on Flathub) installed as a Flatpak. I right click an .exe in ~/Downloads/, choose "Open With Other Application", click "View All Applications", and Bottles isn't in the list.
> 
> ![image](https://user-images.githubusercontent.com/10246/121655918-44558c00-ca9f-11eb-920c-67172c9f2ab3.png)

This could be a regression. In a few hours 3.1.14 should be available in flathub, let's see.

**Comment by garrett** [comment] 2021-06-11 11:05
> This could be a regression. In a few hours 3.1.14 should be available in flathub, let's see.

Thanks! Looking forward to it!

**Comment by mirkobrombin** [comment] 2021-11-27 19:40
Should be fixed by #432

**Closed by mirkobrombin** 2021-11-27 19:40 UTC
Labels: Feature request
