### ISSUE TITLE
[Crash report]  'test'  

### ISSUE THREAD

**Issue by JUNUX1** [bottlesdevs/Bottles#683] opened 2021-10-31 18:32 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.10.28-treviso

**Log**
```python3
'test'  File "/usr/share/bottles/bottles/utils.py", line 298, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/manager.py", line 1178, in async_delete_bottle
    del self.local_bottles[config.get("Path")]

```

**Comment by mirkobrombin** [comment] 2021-10-31 19:44
Duplicate of https://github.com/bottlesdevs/Bottles/issues/676

**Closed by mirkobrombin** 2021-10-31 19:44 UTC

**Comment by JUNUX1** [comment] 2021-10-31 19:49
Well nothing important happening actually and everything is working perfectly.
I just wanted to help by reporting the issue.
Good job

**Comment by mirkobrombin** [comment] 2021-10-31 20:53
> Well nothing important happening actually and everything is working perfectly. I just wanted to help by reporting the issue. Good job

Thanks for reporting 🖖😅
