### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by DudeThuRein** [bottlesdevs/Bottles#409] opened 2021-07-29 11:54 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other

**Log**
```python3
[Errno 2] No such file or directory: '/home/thurein/.local/share/bottles/temp/w2ksp4_en/i386/riched20.dl_'  File "/usr/share/bottles/bottles/utils.py", line 184, in target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/runner.py", line 476, in async_install_dependency
    shutil.copyfile(

  File "/usr/lib64/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

```

**Comment by mirkobrombin** [comment] 2021-07-29 12:06
Duplicate of #408

Provide more informations if not.

**Closed by mirkobrombin** 2021-07-29 12:06 UTC
