### ISSUE TITLE
[Request]: Sandbox or toggle internet and/or network access to bottle

### ISSUE THREAD

**Issue by Willdrick** [bottlesdevs/Bottles#1763] opened 2022-07-12 19:42 UTC
### Tell us the problem or your need

I need to test functionality of software offline

### Describe the solution you'd like

 A simple toggle on the bottle options for disabling the programs running on the bottle from access the internet and another for disabling network capabilities altogether.

### Other solutions?

There are ways to trick wine into not reaching internet, such as giving it a bogus proxy address. This might work for some programs but not every case (i.e. the program is hardcoded to go to a specific IP address)

### Additional context and references

Since Bottles (as a flatpak) is the perfect implementation of sandboxed wine apps, without getting cumbersome, this lacking feature would improve a lot the security of foreign untested or otherwise untrusted applications without compromising the security of the network (i.e. other windows machines) or some kind of beacon lighting up the host pc.

**Comment by axtloss** [comment] 2022-07-12 19:53
This shouldn't be very hard to implement, since bottles supports running bottles in their own sandbox by using `flatpak-spawn`, which also has a flag to block network (`--no-network`).

**Comment by mirkobrombin** [comment] 2022-07-12 20:09
like this?

![image](https://user-images.githubusercontent.com/9479903/178585306-249061e9-3dac-4b0e-ae2c-472b6a4e4cad.png)

check https://github.com/bottlesdevs/Bottles/issues/1158 https://github.com/bottlesdevs/Bottles/issues/1691

**Comment by axtloss** [comment] 2022-07-12 20:12
Yes that does seem good, but why an extra window? In my opinion would be better as an extra section in the Bottle prefrences.

**Comment by mirkobrombin** [comment] 2022-07-12 20:16
> Yes that does seem good, but why an extra window? In my opinion would be better as an extra section in the Bottle preferences.

It's just following gamescope UI implementation:
![image](https://user-images.githubusercontent.com/9479903/178586895-27dd5180-39fa-4bcd-be14-e01eba12f57e.png)

**Comment by axtloss** [comment] 2022-07-12 20:20
Oh I wasn't aware that this is already in bottles since I didn't have the sandboxes enabled.
But I guess this issue could be closed if it already is implemented.

**Comment by mirkobrombin** [comment] 2022-07-12 20:23
duplicate of #1158

**Closed by mirkobrombin** 2022-07-12 20:23 UTC
Labels: Feature request

**Comment by fred0r** [comment] 2022-08-05 02:37
would be supernice if bottles would provide to disable/enable all network-traffic for each 'bottle'.

**Comment by Willdrick** [comment] 2022-08-05 21:18
holy crap, 25 days... really sorry @mirkobrombin. For whatever reason I didn't get notified on my email up until 19 hours ago with the latest post, that looks exactly like what I was looking for. Just a simple toggle to disable network capabilities to a specific bottle. For now I decided to pull the big guns and have a w98 VM on gnome-boxes, but definetly Bottles would be far less cumbersome
