### ISSUE TITLE
[BUG] dotnet472 doesn't download or install with Flatpak

### ISSUE THREAD

**Issue by FilBot3** [bottlesdevs/Bottles#739] opened 2021-11-20 22:16 UTC
# **Describe the bug**

When attempting to install `dotnet472`, Bottles seems to think it does, but nothing actually happens.

```
021-11-20 16:07:17 INFO: Installing dependency [dotnet472] in bottle [reMarkable].
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2021-11-20 16:07:21 INFO: Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscoree] and Data: [native] in register bottle: reMarkable
reg: The operation completed successfully

2021-11-20 16:07:21 INFO: Setting Key: [Installed_Dependencies] to [['allfonts', 'dotnet48', 'dotnet472']] for bottle: [reMarkable]…
2021-11-20 16:07:21 INFO: Setting Key: [dotnet472] to [NO_UNINSTALLER] for bottle: [reMarkable]…
```

Generally the installation takes around five minutes, like the `dotnet48` install does, even when downloaded.

## **Installation**

 - Method: Flatpak
 - Version: 2021.11.14-treviso-4

```bash
➜  ~ flatpak info com.usebottles.bottles

Bottles - Run Windows software

          ID: com.usebottles.bottles
         Ref: app/com.usebottles.bottles/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2021.11.14-treviso-4
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 19.5 MB
     Runtime: org.gnome.Platform/x86_64/41
         Sdk: org.gnome.Sdk/x86_64/41

      Commit: db6cbab875209185c03d0d898e9ff4b7a80e29e969b6b5f6b3e747df43167d32
      Parent: ba5041ac2bcd99deb08b00b9f88cdcd780650a2802cf1fe59a593baa86b8614d
     Subject: Update com.usebottles.bottles.yml (258eb8f0)
        Date: 2021-11-19 06:43:23 +0000
```

## **To Reproduce**

1. Launch Bottles. I launched it from the terminal for debugging output.
2. Create a new Bottle
2. Click on Dependencies
3. Click the download button for dotnet472
4. Watch terminal output.

## **Expected behavior**

I expect the `dotnet472` package to be downloaded and installed.

## **Screenshots**

* There are none.

## **Desktop (please complete the following information):**

 - OS: Pop!_OS
 - Version 21.04
 - Display server: Xorg

## Add any other context about the problem here.

```bash
➜  ~ neofetch 
             /////////////                filbot@pop-os 
         /////////////////////            ------------- 
      ///////*767////////////////         OS: Pop!_OS 21.04 x86_64 
    //////7676767676*//////////////       Host: Oryx Pro oryp6 
   /////76767//7676767//////////////      Kernel: 5.13.0-7620-generic 
  /////767676///*76767///////////////     Uptime: 2 hours, 46 mins 
 ///////767676///76767.///7676*///////    Packages: 2754 (dpkg), 83 (flatpak) 
/////////767676//76767///767676////////   Shell: zsh 5.8 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 3.38.4 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-10875H (16) @ 5.100GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 2060 Mobile 
      ///////////////////////////         GPU: Intel CometLake-H GT2 [UHD Graphics] 
         /////////////////////            Memory: 4620MiB / 31977MiB 
             /////////////
```

**Comment by mirkobrombin** [comment] 2021-11-20 22:41
Are you sure it is not going to be installed? Can you check using the uninstaller tool or looking for its files?

Also, dotnet48 should be more heavy then 472

**Comment by mirkobrombin** [comment] 2021-11-27 19:10
I'm not able to reproduce, closing. Feel free to provide more info.

**Closed by mirkobrombin** 2021-11-27 19:10 UTC
Labels: bug
