### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nahdd1234** [bottlesdevs/Bottles#2319] opened 2022-11-24 04:33 UTC
### Describe the bug

Run exe and nothing happened.
Reboot and restart bottles, then popup error report screen.

### To Reproduce

1. Go to "Run Executable..."
2. Select exe
3. nothing any react.
4. reboot
5. start bottles 
6. error report screen

### Package

Flatpak from Flathub

### Distribution

OpenSuse Tumbleweed

### Troubleshooting Logs

```shell
'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 58, in launch
    res = WineCommand(

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 100, in __init__
    self.cwd = self.__get_cwd(cwd)

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 112, in __get_cwd
    if config.get("Environment", "Custom") == "Steam":
```

**Comment by mirkobrombin** [comment] 2022-11-24 08:37
Related https://github.com/bottlesdevs/Bottles/issues/2057

**Comment by MandiYang** [comment] 2022-11-26 11:45
Same issue using Ubuntu 22.04 Wayland

**Comment by Heus-Sueh** [comment] 2022-11-26 21:32
'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 58, in launch
    res = WineCommand(

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 100, in __init__
    self.cwd = self.__get_cwd(cwd)

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 112, in __get_cwd
    if config.get("Environment", "Custom") == "Steam":


Nobara Linux 36 KDE Plasma 5.26.3 x11

**Comment by Fijxu** [comment] 2022-11-28 22:07
Same error here

```py
'Result' object has no attribute 'get'  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/wine/wineprogram.py", line 58, in launch
    res = WineCommand(

  File "/usr/share/bottles/bottles/backend/wine/winecommand.py", line 100, in __init__
    self.cwd = self.__get_cwd(cwd)

  File "/usr/share/bottles/bottles/backend/wine/winecommand.py", line 112, in __get_cwd
    if config.get("Environment", "Custom") == "Steam":
```

Arch Linux, Python 3.10.8, Native Build

**Comment by Willdrick** [comment] 2022-11-29 20:15
same issue here. Fedora 37, bottles from flathub (v2022.11.14)

**Comment by mirkobrombin** [comment] 2022-11-30 13:57
Duplicate of #2307

**Closed by mirkobrombin** 2022-11-30 13:57 UTC
