### ISSUE TITLE
[Bug]: Could not get index for

### ISSUE THREAD

**Issue by Rrauros** [bottlesdevs/Bottles#2421] opened 2022-12-21 16:54 UTC
### Describe the bug

When I launch flatpak Bottles with "flatpak run com.usebottles.bottles"
it give me these errors: 
11:35:25 (ERROR) Could not get index for components repository: (28, 'Resolving timed out after 4876 milliseconds') 
11:35:35 (ERROR) Could not get index for dependencies repository: (28, 'Resolving timed out after 4879 milliseconds') 
11:35:46 (ERROR) Could not get index for installers repository: (28, 'Resolving timed out after 4854 milliseconds') 

And preferences, runners and dll components seems empty. If I didn't created bottles already and when I am starting the program for the first time it fails to install any components which also means it can't set up a bottle. 
If I have set it up bottles already, I can't install any dependency on it. This has started to happening with the latest versions, this month. I had no issues like this on last month's version as far as I can remember. 

Sometimes it connects to servers and I can be able to install wine or dxvk on it but 95 percent of the time it says could not get index and runners, dll components seems empty. 
![Screenshot_20221221_114819](https://user-images.githubusercontent.com/62460316/208959602-8dbe9232-0d83-4b43-854f-2a314469620a.png)

### To Reproduce

Launch bottles
It reports errors
You can't install any wine or dxvk component.

### Package

Flatpak from Flathub

### Distribution

EndeavourOS

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.0-2-cachyos-lto
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8363405312
    Free: 8363241472
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.4GiB
Bottles_envs: null
```

**Comment by StoneMoe** [comment] 2022-12-23 10:09
You seems have a bad connection just like me, currently Bottles' CDN is not works very well globally

and the Bottles itself does not support bad connection very well, so there is no way to refresh repository index without reopen your Bottles app currently.

**Comment by Rrauros** [comment] 2022-12-23 10:36
> and the Bottles itself does not support bad connection very well, so there is no way to refresh repository index without reopen your Bottles app currently.

Closing and reopening the app doesn't fix the problem for me. My internet speed is slow but not that slow.  I'm guessing the real problem is that I must be far away to Bottles' servers maybe.

**Comment by Kinsteen** [comment] 2022-12-23 10:44
In your browser, can you access https://proxy.usebottles.com/repo/components/index.yml ?

**Comment by Rrauros** [comment] 2022-12-23 11:29
> In your browser, can you access https://proxy.usebottles.com/repo/components/index.yml ? This is the URL that Bottles is trying to reach but fails in your case

Yes, I think I can be able to reach there from my browser since my browser downloads index.yml when I try to enter to that adress, which I guess is expected right?

**Comment by mirkobrombin** [comment] 2023-01-05 15:54
Can you try this build? https://github.com/bottlesdevs/Bottles/actions/runs/3848152891

**Comment by Rrauros** [comment] 2023-01-05 18:23
> Can you try this build? https://github.com/bottlesdevs/Bottles/actions/runs/3848152891

Nope its still not working: 
13:20:38 (INFO) Bottles Started! 
13:21:08 (ERROR) Could not get index for components repository: (28, 'Resolving timed out after 4888 milliseconds') 
13:21:08 (ERROR) Could not get index for components repository 
13:21:09 (ERROR) Could not get index for installers repository: (28, 'Resolving timed out after 4215 milliseconds') 
13:21:09 (ERROR) Could not get index for installers repository 

![Screenshot from 2023-01-05 13-22-22](https://user-images.githubusercontent.com/62460316/210852726-7811abbb-6d48-4f44-a7ae-c1ed3cb54d71.png)

**Comment by Kinsteen** [comment] 2023-01-05 18:27
Citing @francescomasala [here](https://github.com/bottlesdevs/Bottles/issues/2477#issuecomment-1372481048), can you try to run `dig proxy.usebottles.com`? And if you could tell us the country you're from, that would be of help too

**Comment by Rrauros** [comment] 2023-01-05 18:29
> Citing @francescomasala [here](https://github.com/bottlesdevs/Bottles/issues/2477#issuecomment-1372481048), can you try to run `dig proxy.usebottles.com`? And if you could tell us the country you're from, that would be of help too

; <<>> DiG 9.18.10 <<>> proxy.usebottles.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2100
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;proxy.usebottles.com.		IN	A

;; ANSWER SECTION:
proxy.usebottles.com.	300	IN	A	172.67.153.15
proxy.usebottles.com.	300	IN	A	104.21.40.150

;; Query time: 47 msec
;; SERVER: 192.168.1.1#53(192.168.1.1) (UDP)
;; WHEN: Thu Jan 05 13:27:26 EST 2023


I'm from Turkey.

**Comment by francescomasala** [comment] 2023-01-05 18:33
Strange, from our side everything is working
EU Mirror - Online
IT Mirror - Online
US/CA/MX Mirror - Online
GeoLB Workers - Online
Cloudflare - Online

**Comment by Rrauros** [comment] 2023-01-05 18:59
> proxy.usebottles.com. 300 IN A 172.67.153.15
> proxy.usebottles.com. 300 IN A 104.21.40.150

Does this mean it tries to connect to US servers. I'm in Turkey so I should connect to EU or IT servers right?

**Comment by francescomasala** [comment] 2023-01-05 19:03
> > proxy.usebottles.com. 300 IN A 172.67.153.15
> 
> > proxy.usebottles.com. 300 IN A 104.21.40.150
> 
> 
> 
> Does this mean it tries to connect to US servers? I'm in Turkey so I should connect to EU or IT servers right?

The GeoLB is pointing you to the italian mirror (the IP from proxy.usebottles.com is from your nearest cloudflare POP)

**Comment by Rrauros** [comment] 2023-01-05 19:06
> > > proxy.usebottles.com. 300 IN A 172.67.153.15
> > 
> > 
> > > proxy.usebottles.com. 300 IN A 104.21.40.150
> > 
> > 
> > Does this mean it tries to connect to US servers? I'm in Turkey so I should connect to EU or IT servers right?
> 
> The GeoLB is pointing you to the italian mirror (the IP from proxy.usebottles.com is from your nearest cloudflare POP)

Hmmm, as I mentioned in my first comment this has started happening in the last couple of months. I don't know what has changed. But let me know if there is anything I could do to help.

**Comment by francescomasala** [comment] 2023-01-05 19:29
We have changed all the core infrastructure, so let me get home and I'll try to help you!

**Comment by francescomasala** [comment] 2023-01-06 20:57
> > > > proxy.usebottles.com. 300 IN A 172.67.153.15
> > > 
> > > 
> > > > proxy.usebottles.com. 300 IN A 104.21.40.150
> > > 
> > > 
> > > Does this mean it tries to connect to US servers? I'm in Turkey so I should connect to EU or IT servers right?
> > 
> > 
> > The GeoLB is pointing you to the italian mirror (the IP from proxy.usebottles.com is from your nearest cloudflare POP)
> 
> Hmmm, as I mentioned in my first comment this has started happening in the last couple of months. I don't know what has changed. But let me know if there is anything I could do to help.

Any news?

**Comment by Rrauros** [comment] 2023-01-06 21:16
> Any news?

16:14:07 (ERROR) Could not get index for dependencies repository: (28, 'Resolving timed out after 4741 milliseconds') 
16:14:07 (ERROR) Could not get index for components repository: (28, 'Resolving timed out after 4833 milliseconds') 
16:14:07 (ERROR) Could not get index for components repository 
16:14:07 (ERROR) Could not get index for dependencies repository 
16:14:07 (ERROR) Could not get index for installers repository: (28, 'Resolving timed out after 4856 milliseconds') 

It is still not working.

**Comment by francescomasala** [comment] 2023-01-09 11:44
Seems like that is a problem from your side

**Comment by Rrauros** [comment] 2023-01-09 20:01
> Seems like that is a problem from your side

I'm using flatpak package. Tried in different distros and haven't changed anything. Someone else is also having the same problem. https://github.com/bottlesdevs/Bottles/issues/2477 

Maybe there is a problem with my ISP (it doesn't support ipv6). But I don't know what causing it.

**Comment by francescomasala** [comment] 2023-01-09 20:16
Try to check now, in theory I should have fixed some cloudflare WAF settings

**Comment by Rrauros** [comment] 2023-01-09 22:54
> Try to check now, in theory I should have fixed some cloudflare WAF settings

17:49:20 (ERROR) Could not get index for dependencies repository: (28, 'Resolving timed out after 4889 milliseconds') 
17:49:30 (ERROR) Could not get index for installers repository: (28, 'Resolving timed out after 4870 milliseconds')

As you can see from my previous post sometimes it can't get index for dependicies, components and installers but sometimes it connects it to some parts as in the case right now and gets the components but not for others. Rarely it can be able connects to all of them and I can setup new bottles and install some wine until next restart of the program. This is really weird behaviour that I cannot explain.
Maybe there is a timout problem?

**Comment by Rrauros** [comment] 2023-01-09 22:59
Here I tried and it did connected to servers. I closed the bottles and reopened again but couldn't connect again. 
![Screenshot_2](https://user-images.githubusercontent.com/62
![Screenshot_4](https://user-images.githubusercontent.com/62460316/211425027-bdda6957-a787-4836-82d6-efc85de2598a.png)
460316/211425021-e8aa2177-8fb4-46f1-b08e-f994df8eb177.png)

**Comment by Rrauros** [comment] 2023-01-09 23:01
I opened the bottles it did manage to connect to servers. I closed it and tried again just after 5 minutes later and this time it failed connect. 

![Screenshot_2](https://user-images.githubusercontent.com/62460316/211425330-aaecf9c4-6fe7-445e-ad07-3ae26223aac5.png)

![Screenshot_4](https://user-images.githubusercontent.com/62460316/211425326-e1be1351-832f-4b69-bf2f-f32481e571bd.png)

**Comment by francescomasala** [comment] 2023-01-10 05:18
Are you using a vpn / for service?

**Comment by Rrauros** [comment] 2023-01-10 08:27
> Are you using a vpn / tor service?

No vpn. Not using any dns service as well.

**Comment by Rrauros** [comment] 2023-01-10 12:23
I have to test and try out more but since this morning it seems that I can be able to reach every part (components, installer and dependencies etc) of Bottles. Thanks for helping.

**Comment by Rrauros** [comment] 2023-01-10 19:07
> since this morning it seems that I can be able to reach every part (components, installer and dependencies etc) of Bottles

It worked whole day but unfortunately, its not working right now. Still getting Could not get index for error.

**Comment by francescomasala** [comment] 2023-01-11 05:58
Strange, from my side I don't see any problem

**Comment by SoullessBoi** [comment] 2023-01-16 17:45
i believe i have the same problem... i live in Jordan.

**Comment by francescomasala** [comment] 2023-01-18 11:50
In theory now it should be working, keep me updated please

**Comment by Rrauros** [comment] 2023-01-21 10:13
> In theory now it should be working, keep me updated please

For me its the same. It's still unstable. Sometimes it connects to some parts but most of the time it's still prints could not get index for error.

**Comment by gioan777** [comment] 2023-01-24 11:41
So I had the same issue and after fiddling with networking I found out that /etc/resolv.conf, was by default using the IPv6 address of my router. After I changed it to IPv4 Bottles worked again. In other words I changed 
`nameserver fe80::1`
to
`nameserver 192.168.1.1`
I'm not sure what exactly caused the issue, but looking through dns queries in wireshark it seems as if the DNS queries work fine if the various usebottles servers return an IPv6 address but the moment it returns an IPv4 address my computer gives up and timeouts.

**Comment by pollux56** [comment] 2023-05-13 03:51
i'm getting the same issue on arch.
weird thing is that it works on fedora but since iv switched to arch its having this issue
for me i can't fetch the installer repo index
i'm from australia using starlink as my isp 
iv also checked my resolv.conf and its set to ipv4 which is correct and im not using any dns 
using windscribe vpn to a sydney server im able to download and install blizzard and ea, aswell as runners all fine

**Comment by Noobao** [comment] 2023-07-01 16:59
Having the same issue, it times out and I can't fetch.

I live on brazil and I've set everything correctly with ipv4 and such, I'm also not using any dns nor vpn, my browser also doesn't do anything with the proxy for the installer index.

**Comment by kin0be** [comment] 2023-07-13 13:53
Same thing happening for me. 

Malaysia, no VPN, resolv.conf is IPv4 (8.8.8.8). 

I can get to the index.yml just fine from browser.

**Comment by francescomasala** [comment] 2023-07-17 15:58
Working on it

**Comment by francescomasala** [comment] 2023-07-17 16:56
I've updated some stuff:
 - DNS Related things (removed CNAME records and used direct A/AAAA records)
 - Updated Cloudflare worker algorithm
 - Added a new mirror for the following countries: JP, KR, CN, TW

**Comment by BlackBaroness** [comment] 2023-08-05 14:54
> Cc: @gioan777 @pollux56 @kin0be @Noobao @Rrauros
> 
> I've updated some stuff:
> 
>     * DNS Related things (removed CNAME records and used direct A/AAAA records)
> 
>     * Updated Cloudflare worker algorithm
> 
>     * Added a new mirror for the following countries: JP, KR, CN, TW

Hello, the problem is still persist: #3018
I use CloudFlare DNS and can open and download indexes from the browser.

**Comment by Rrauros** [comment] 2023-08-07 17:26
> Cc: @gioan777 @pollux56 @kin0be @Noobao @Rrauros
> 
> I've updated some stuff:
> 
>     * DNS Related things (removed CNAME records and used direct A/AAAA records)
> 
>     * Updated Cloudflare worker algorithm
> 
>     * Added a new mirror for the following countries: JP, KR, CN, TW

 Issue also still persist for me.

**Comment by francescomasala** [comment] 2023-08-13 21:49
@rauros @BlackBaroness 

I've updated a couple of things from the CF side, try now

**Comment by Rrauros** [comment] 2023-08-16 12:06
> @Rauros @BlackBaroness
> 
> I've updated a couple of things from the CF side, try now

Still doesn't work.

**Comment by BlackBaroness** [comment] 2023-08-18 23:15
> @Rauros @BlackBaroness
> 
> I've updated a couple of things from the CF side, try now

Yep, still doesn't work.

```
(bottles:2): Gtk-WARNING **: 02:13:51.012: Unable to acquire the address of the accessibility bus: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown. If you are attempting to run GTK without a11y support, GTK_A11Y should be set to 'none'.
02:13:51 (INFO) Bottles Started! 
02:13:56 (ERROR) Data file not found. Creating new one. 
02:14:22 (ERROR) Could not get index for components repository: (28, 'Resolving timed out after 4727 milliseconds') 
02:14:22 (ERROR) Could not get index for components repository 
02:14:22 (ERROR) Could not get index for dependencies repository: (28, 'Resolving timed out after 4689 milliseconds') 
02:14:22 (ERROR) Could not get index for installers repository: (28, 'Resolving timed out after 4707 milliseconds') 
02:14:22 (ERROR) Could not get index for dependencies repository 
02:14:22 (ERROR) Could not get index for installers repository 
02:14:22 (INFO) Performing Bottles checks… 
02:14:22 (INFO) Runners path doesn't exist, creating now. 
02:14:22 (INFO) Runtimes path doesn't exist, creating now. 
02:14:22 (INFO) WineBridge path doesn't exist, creating now. 
02:14:22 (INFO) Bottles path doesn't exist, creating now. 
02:14:22 (INFO) Dxvk path doesn't exist, creating now. 
02:14:22 (INFO) Vkd3d path doesn't exist, creating now. 
02:14:22 (INFO) Nvapi path doesn't exist, creating now. 
02:14:22 (INFO) Templates path doesn't exist, creating now. 
02:14:22 (INFO) Temp path doesn't exist, creating now. 
02:14:22 (INFO) LatencyFleX path doesn't exist, creating now. 
02:14:22 (INFO) Runners found:
         - sys-wine-8.0.2
 
02:14:22 (WARNING) Library file not found, creating new one 
02:14:22 (INFO) Library saved 

(bottles:2): Gtk-WARNING **: 02:14:22.814: No IM module matching GTK_IM_MODULE=cedilla found
02:14:27 (INFO) No dependencies found! 
02:14:27 (INFO) No installers found! 
02:14:31 (INFO) Performing Bottles checks… 
02:14:31 (WARNING) No dxvk found. 
02:14:36 (WARNING) No vkd3d found.
```

**Comment by saikatdas0790** [comment] 2023-08-19 13:30
I'm running into the same problem as well.

I'm from India.

This is what dig gives me:

![image](https://github.com/bottlesdevs/Bottles/assets/7412443/83483eb5-aabe-4b99-88f4-3e0a2846fca7)

**Comment by saikatdas0790** [comment] 2023-08-19 13:36
@SuperSamus 
Okay, got it to install by using a VPN that connects to the Netherlands.

Quite strange.

![image](https://github.com/bottlesdevs/Bottles/assets/7412443/c1b7488b-447c-4c21-8296-890d0a09e8d2)

Thank you for the help. Closing this issue 🙂

**Comment by Rrauros** [comment] 2023-10-28 15:47
Update: I was using Arch and Arch based distros when hitting these error. Now I'm testing Fedora Kinoite and have been testing for the last couple of days. And I didn't hit these errors since then. I don't if you guys made some changes on your end or if it was related to distro itself (I don't know how much this makes sense since in both cases I was using the Flatpak package) but currently everything is working as expected.

**Comment by Rrauros** [comment] 2023-10-29 16:06
I just tried it with default Endeavouros now and yes I can confirm my previous comment. I can access to all component in Fedora without any problem and its very fast actually. But when I'm using Arch I got hit by could not get index for.

**Closed** 2024-03-21 11:53 UTC
Labels: Bug, Waiting response
