### ISSUE TITLE
make appimage

### ISSUE THREAD

**Issue by newyorkthink** [bottlesdevs/Bottles#2544] opened 2023-01-16 07:09 UTC
!!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!

**Comment by jannuary** [comment] 2023-01-16 08:00
We don't have the maintenance budget to release and perpetually mantain and test an Appimage, and no one of us is very proficient in building Appimages, sorry.

Unless someone takes that workload up, I'm afraid I have to mark this as out of scope.

**Comment by jannuary** [comment] 2023-01-16 08:06
Also, dupe of #1272

**Closed** 2023-01-16 08:07 UTC
Labels: Duplicate, Packaging
