### ISSUE TITLE
[Crash report] faudio is not a dependency installing uplay

### ISSUE THREAD

**Issue by juampiursic** [bottlesdevs/Bottles#562] opened 2021-09-24 05:04 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.9.14-treviso

**Log**
```python3
'NoneType' object is not subscriptable  File "/app/share/bottles/bottles/utils.py", line 295, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/installer.py", line 204, in __async_install
    self.__install_dependencies(config, dependencies)

  File "/app/share/bottles/bottles/backend/installer.py", line 97, in __install_dependencies
    self.__manager.dependency_manager.async_install([

  File "/app/share/bottles/bottles/backend/dependency.py", line 137, in async_install
    dependency_category=dependency[1]["Category"]

```

**Comment by mirkobrombin** [comment] 2021-09-24 05:08
What dependency were you installing?

**Comment by juampiursic** [comment] 2021-09-24 05:09
I was installing uplay installer from the installers options (didn't download the .exe from the website I mean) and it crashed, when I opend it again I got the message to send the error report.

**Comment by mirkobrombin** [comment] 2021-09-24 05:11
The link is probably no longer reachable

**Comment by juampiursic** [comment] 2021-09-24 05:34
It tries to install faudio but faudio is not on de dependencies.

**Comment by mirkobrombin** [comment] 2021-09-24 05:35
> It tries to install faudio but faudio is not on the dependencies.

Yes, I just noticed

**Comment by juampiursic** [comment] 2021-09-24 05:36
What can I do? I know this isn't the place to ask this but as steam, egs and uplay are on the installers, it might be sometime in the near future it could have an origin installer?

**Comment by mirkobrombin** [comment] 2021-09-24 05:39
> What can I do? I know this isn't the place to ask this but as steam, egs and uplay are on the installers, it might be sometime in the near future it could have an origin installer?

The installers are in a community driven repository. Anyone can contribute by creating new ones (read [here](https://github.com/bottlesdevs/programs/blob/main/GUIDELINES.md)). Personally, I don't have much time lately and can't make promises.

**Comment by mirkobrombin** [comment] 2021-09-24 05:40
Should be fixed by https://github.com/bottlesdevs/dependencies/commit/f12b8ce82e7dfd5cb188532362997dfad2807a13 (wait some minutes before testing).

**Comment by juampiursic** [comment] 2021-09-24 05:49
After installing I get this

![image](https://user-images.githubusercontent.com/6501647/134624706-00246426-706d-468a-b14e-3b174f877bc6.png)

**Comment by mirkobrombin** [comment] 2021-09-24 05:51
Is this a 32bit or 64bit bottle?Also, have you installed other dependencies (also trough installers)?

**Comment by juampiursic** [comment] 2021-09-24 17:01
> Is this a 32bit or 64bit bottle?Also, have you installed other dependencies (also trough installers)?

It's a 64bit bottle. Trying to install EGS does nothing really.

**Comment by mirkobrombin** [comment] 2021-09-25 06:05
I am not able to reproduce this. Can you try with a new clean bottle?

**Comment by juampiursic** [comment] 2021-09-25 23:41
I've deleted every Bottle, created a new one under Games and it's still happening.

![image](https://user-images.githubusercontent.com/6501647/134788566-05f4e27d-6f3c-45e6-8a6e-e0f80411c557.png)

**Comment by mirkobrombin** [comment] 2021-09-26 07:28
But is this an uplay error or an uplay pgame?

**Comment by juampiursic** [comment] 2021-09-26 21:41
> But is this an uplay error or an uplay game?

uplay error. When the installer finishes it prompts me the install of ubisoft connect, I hit nex, next, install, and then it appears on Programs, I click play and uplay launcher must open up but instead I get this error.

**Comment by mirkobrombin** [comment] 2021-09-27 05:22
Unfortunately I can't reply. I follow the same procedure I'm using Vaniglia as runner and dxvk.

**Comment by mirkobrombin** [comment] 2021-10-04 07:59
Closing as the main topic was fixed, please open another issue if the uplay problem persist :)

**Closed by mirkobrombin** 2021-10-04 07:59 UTC
