### ISSUE TITLE
[Crash report]  cabextract utility not found, 

### ISSUE THREAD

**Issue by Raul1198** [bottlesdevs/Bottles#751] opened 2021-11-27 07:36 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.11.14-treviso

**Log**
```python3
cabextract utility not found, please install to use dependencies which need this feature
```

**Comment by mirkobrombin** [comment] 2021-11-27 10:56
Duplicate of #566

Ps ask the maintainer to fix the package.

**Closed by mirkobrombin** 2021-11-27 10:56 UTC
