### ISSUE TITLE
[BUG] Bottles can't find dll files needed to run Mod Organizer

### ISSUE THREAD

**Issue by PopeRigby** [bottlesdevs/Bottles#319] opened 2021-06-21 18:47 UTC
**Describe the bug**
I'm attempting to run Mod Organizer 2 through bottles, but it doesn't seem to be able to find the dll files it needs to run. Every time I run it, it fails to launch and Bottles outputs this in the console:
<details><summary>Bottles output</summary>

```018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Quick.dll") not found
018c:err:module:import_dll Library Qt5Quick.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineCore.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineCore.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineCore.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineCore.dll") not found
018c:err:module:import_dll Library Qt5WebEngineCore.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Quick.dll") not found
018c:err:module:import_dll Library Qt5Quick.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Widgets.dll") not found
018c:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5PrintSupport.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5PrintSupport.dll") not found
018c:err:module:import_dll Library Qt5PrintSupport.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Widgets.dll") not found
018c:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Quick.dll") not found
018c:err:module:import_dll Library Qt5Quick.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5QuickWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Widgets.dll") not found
018c:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5QuickWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5QuickWidgets.dll") not found
018c:err:module:import_dll Library Qt5QuickWidgets.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WebEngineWidgets.dll") not found
018c:err:module:import_dll Library Qt5WebEngineWidgets.dll (which is needed by L"C:\\Program Files\\MO2\\ModOrganizer.exe") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5WinExtras.dll") not found
018c:err:module:import_dll Library Qt5WinExtras.dll (which is needed by L"C:\\Program Files\\MO2\\uibase.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Quick.dll") not found
018c:err:module:import_dll Library Qt5Quick.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5QuickWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Widgets.dll") not found
018c:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5QuickWidgets.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5QuickWidgets.dll") not found
018c:err:module:import_dll Library Qt5QuickWidgets.dll (which is needed by L"C:\\Program Files\\MO2\\uibase.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Widgets.dll") not found
018c:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\MO2\\uibase.dll") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\uibase.dll") not found
018c:err:module:import_dll Library uibase.dll (which is needed by L"C:\\Program Files\\MO2\\ModOrganizer.exe") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Widgets.dll") not found
018c:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\MO2\\ModOrganizer.exe") not found
018c:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\MO2\\dlls\\Qt5Gui.dll") not found
018c:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\MO2\\ModOrganizer.exe") not found
018c:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\MO2\\ModOrganizer.exe" failed, status c0000135
```

</details>

**Installation**
 - Method: Meson (AUR)
 - Version: 3.1.15-1

**To Reproduce**
1. Create a new `Gaming` bottle,
2. Download the installer for [Mod Organizer 2.4.2](https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.2/Mod.Organizer-2.4.2.exe),
3. Run the installer from within the `Gaming` bottle,
4. Choose the default options in the install wizard,
5. Attempt to run the newly installed `Mod Organizer` program from within Bottles,

**Expected behavior**
Mod Organizer launches successfully,

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: N/A

**Comment by mirkobrombin** [comment] 2021-06-21 19:09
It seems more of a problem with Wine than Bottles 🤔
Anyway, I took a look at the [installer script](https://lutris.net/games/install/18207/view) for Lutris and it looks like it needs several tweaks to work ([even if I read that it doesn't work for some anyway](https://www.reddit.com/r/linux_gaming/comments/cugr84/lutris_with_mod_organizer_2/exu9tus/?utm_source=reddit&utm_medium=web2x&context=3)). Bottles does not currently support this level of tweaking and you should proceed manually. I recommend using Lutris as the installation process seems extremely simplified there.

Anyway, I'm going to close the issue as the problem is related to Wine and not Bottles. Feel free to comment, I will be happy to try to help you somehow.

**Comment by PopeRigby** [comment] 2021-06-21 19:50
> It seems more of a problem with Wine than Bottles thinking

Maybe, but I'm not so sure. I just ran the Mod Organizer installer with the system version of WINE 6.11 and it installed just fine. The problem is that it will crash with a dialog box about not being able to load .NET libraries ([relevant MO bug](https://github.com/ModOrganizer2/modorganizer/issues/1413)). That error seems to be happening because .NET 4.8 isn't installed, which is why I'm trying to run it through Bottles and install that dependency in the prefix.

But, when I run it through Bottles, it doesn't give me any dialog box, and the issue seems unrelated. The Bottles prefix isn't able to find anything in the MO install directory.

> Anyway, I took a look at the installer script for Lutris and it looks like it needs several tweaks to work (even if I read that it doesn't work for some anyway). 

Judging by [this](https://github.com/ModOrganizer2/modorganizer/issues/372) issue on the MO issue tracker, it seems like this is no longer the case, and that the USVFS now mostly works with WINE. That comment you linked is also a year old.

> Feel free to comment, I will be happy to try to help you somehow.

Thank you :slightly_smiling_face:

**Comment by mirkobrombin** [comment] 2021-06-21 19:59
> > It seems more of a problem with Wine than Bottles thinking
> 
> Maybe, but I'm not so sure. I just ran the Mod Organizer installer with the system version of WINE 6.11 and it installed just fine. The problem is that it will crash with a dialog box about not being able to load .NET libraries ([relevant MO bug](https://github.com/ModOrganizer2/modorganizer/issues/1413)). That error seems to be happening because .NET 4.8 isn't installed, which is why I'm trying to run it through Bottles and install that dependency in the prefix.
> 
> But, when I run it through Bottles, it doesn't give me any dialog box, and the issue seems unrelated. The Bottles prefix isn't able to find anything in the MO install directory.
> 
> > Anyway, I took a look at the installer script for Lutris and it looks like it needs several tweaks to work (even if I read that it doesn't work for some anyway).
> 
> Judging by [this](https://github.com/ModOrganizer2/modorganizer/issues/372) issue on the MO issue tracker, it seems like this is no longer the case, and that the USVFS now mostly works with WINE. That comment you linked is also a year old.
> 
> > Feel free to comment, I will be happy to try to help you somehow.
> 
> Thank you

Chardonnay (our wine runner) isn't too different from the Wine you install on Arch Linux. It is always a Vanilla version. Maybe you need an older version to run that software?

I reopen the issue as a reminder so in the next days I can try to run it on my installation. At the moment you could try to create a new Custom type bottle, using Chardonnay as a runner. Then in winecfg change the Windows version to Windows 7 and uninstall mono from Uninstaller, then install dotnet48 from the dependencies tab and see if it works.

**Comment by PopeRigby** [comment] 2021-06-21 20:06
I did that, and now I get this popup when I try to launch MO
![image](https://user-images.githubusercontent.com/20866468/122821281-7cc04b80-d291-11eb-9e8d-2eb4972c237c.png)

**Comment by mirkobrombin** [comment] 2021-06-21 20:17
😂At least this time it comes out with a different error.
I will try to understand in the next few days what generates the error `010c:err:mscoree:LoadLibraryShim error reading registry key for installroot`

**Comment by mirkobrombin** [comment] 2021-06-21 20:17
> 😂At least this time it comes out with a different error.
> I will try to understand in the next few days what generates the error `010c:err:mscoree:LoadLibraryShim error reading registry key for installroot`

In the meantime, can you keep me updated if you do other tests?

**Comment by PopeRigby** [comment] 2021-06-21 20:18
Sure thing, but I'm not sure what else I would try.

**Comment by mirkobrombin** [comment] 2021-06-22 13:21
So I was able to make it works..
![image](https://user-images.githubusercontent.com/9479903/122931500-7a76f380-d35c-11eb-9e91-01394991238c.png)

It asks me for the path of a game that I don't have but is actually working.

Now let's get to the funny stuff: I created a new custom type bottle with Chardonnay 6.10 and I just started the installer, then I started it from the Programs section and it just works.

**Comment by PopeRigby** [comment] 2021-06-24 21:30
I'll have to check on this when I get home from my vacation, as my laptop doesn't have Fallout: New Vegas on it.

**Comment by mirkobrombin** [comment] 2021-06-30 06:03
I close the issue as it was a problem with the runner and not Bottles. Let me know if it works for you anyway!

**Closed by mirkobrombin** 2021-06-30 06:03 UTC
Labels: not a bug, waiting response

**Comment by PopeRigby** [comment] 2021-07-02 02:53
The problem is that once I setup Mod Organizer with a game (which you won't be able to reproduce unless you own a game that's compatible, which is most Bethesda games) it crashes. The problem was theorized to be because dotnet48 isn't installed, but Mod Organizer also crashes with a different error if that's installed. Anyway, it probably isn't even a Bottles bug.

**Comment by mirkobrombin** [comment] 2021-07-02 05:03
> The problem is that once I setup Mod Organizer with a game (which you won't be able to reproduce unless you own a game that's compatible, which is most Bethesda games) it crashes. The problem was theorized to be because dotnet48 isn't installed, but Mod Organizer also crashes with a different error if that's installed. Anyway, it probably isn't even a Bottles bug.

Yes unfortunately I don't have any Bethesda games and I have to stop here, sorry.

**Comment by PopeRigby** [comment] 2021-07-02 23:25
It's no problem. It's not even your bug.

**Comment by PopeRigby** [comment] 2021-07-03 00:10
Quick question though, how does Bottles install .NET? Is it basically just installing it by running the official installer inside the prefix?

**Comment by mirkobrombin** [comment] 2021-07-03 05:04
> Quick question though, how does Bottles install .NET? Is it basically just installing it by running the official installer inside the prefix?

Yep
