### ISSUE TITLE
DXVK NVAPI does not work (DLSS?)

### ISSUE THREAD

**Issue by Sultech** [bottlesdevs/Bottles#1013] opened 2022-02-02 23:52 UTC
**Describe the bug**
When enabling dxvk nvapi, dlss does not work

**Installation**
 - Method: Flatpak
 - Version 2022.1.28-trento-3

**To Reproduce**
1. Enable DXVK NVAPI
2. Open a game with DLSS
3. Wont be able to enable DLSS

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Xorg

**Comment by Sultech** [comment] 2022-02-02 23:58
So I have been trying to figure out the problem and one thing that needs to be done is the wine dll overrides. (nvapi64,nvapi=n)
I tried to copy the dlls from /usr/lib64/nvidia/wine and paste it in my games directory, this made dlss work in this game. Then I looked at the way lutris does it and they sym link the dll's from /usr/lib64/nvidia/wine and put in the prefix/system32 folder. I tried this but dlss did not work. Someone could try the second method without the flatpak version and see if it works

**Comment by mirkobrombin** [comment] 2022-02-10 14:13
Our system just copy the needed dlls and register the override (like lutris should do I think) https://github.com/bottlesdevs/Bottles/blob/44ec8ec8f511a6e06c240b297172737c05dcd26b/src/backend/dlls/dll.py#L99

I'm not able to reproduce. How do you know it is not working?

**Comment by Sultech** [comment] 2022-02-10 14:45
When I try a game such as cyberpunk I can not enable DLSS.

**Comment by mirkobrombin** [comment] 2022-03-21 17:20
Does the problem persist with 2022.3.14-3?

**Comment by mirkobrombin** [comment] 2022-05-13 12:49
Closing due to missing response.

**Comment by SenseiSchizo** [comment] 2022-08-15 00:14
Can confirm, I have tried everything.

**Comment by Sultech** [comment] 2022-09-13 04:16
> Does the problem persist with 2022.3.14-3?

Yes the problem is still here, sorry for the delayed response

**Comment by Shatur** [comment] 2022-09-22 17:37
@mirkobrombin experiencing the same here. Can reproduce the issue in a fresh bottle using caffe-1.15 I managed to enable ray tracing in Control by setting `VKD3D_CONFIG=dxr`, but DLSS option in settings is still grayed out.

**Comment by nadanke** [comment] 2022-10-09 20:51
I can also confirm that DLSS doesn't work on a fresh Bottles Flatpak install. When added as non-Steam game in Steam, it works, with the same launch options. Interestingly, ray tracing works, but DLSS can't be selected.
Can also confirm that copying the DLLs into the game directory makes DLSS work.

**Comment by cyberphantom52** [comment] 2022-10-13 21:17
@mirkobrombin can you reopen this issue. I have looked into this issue as it affects me too and i found that nvngx dlls don't exist in sys32 directory for me, i copied those dlls from a proton prefix and added their respective overides. Now DLSS is working. The dlls in question are `nvngx.dll` and `_nvngx.dll`, they should be automatically copied from `/usr/lib64/nvidia/wine/` when prefix is created but for some reason they aren't. Can you take a look. Thanks

**Closed** 2022-10-21 16:42 UTC
Labels: Bug, Waiting response

**Comment by Subwaytime** [comment] 2022-10-26 18:18
Anyone here that got raytracing and dlss to work for world of warcraft?
Already tried the workarounds above and unfortunately it doesnt seem to work. DirectX 12 can be selected and the dlss files are in the prefix/system32 but it still doesnt work! :thinking:

**Comment by cyberphantom52** [comment] 2022-10-26 18:38
> Anyone here that got raytracing and dlss to work for world of warcraft? Already tried the workarounds above and unfortunately it doesnt seem to work. DirectX 12 can be selected and the dlss files are in the prefix/system32 but it still doesnt work! thinking
you need
VKD3D_CONFIG=dxr11

**Comment by Subwaytime** [comment] 2022-10-27 14:42
@cyberphantom52 I already have this inside the environment variables, unfortunately it doesnt have an effect :thinking: 
Got a 3080ti with nvidia 515 - if that helps.. ^^
![image](https://user-images.githubusercontent.com/7354569/198319616-87aefbde-2390-4f2a-93c4-23d576b62818.png)

**Comment by Dungeonseeker** [comment] 2022-11-01 20:41
> @cyberphantom52 I already have this inside the environment variables, unfortunately it doesnt have an effect thinking Got a 3080ti with nvidia 515 - if that helps.. ^^ or does this need to be part of the launch options? ![image](https://user-images.githubusercontent.com/7354569/198319616-87aefbde-2390-4f2a-93c4-23d576b62818.png)

You need to manually copy the required dlls, a fix has been submitted already so hopefully this will be automated in the next Bottles update.

Something like `cp /lib64/nvidia/wine/*.dll ~/.var/app/com.usebottles.bottles/data/bottles/bottles/*BOTTLENAME*/drive_c/windows/system32`should work.

**Comment by AlawamiAZ** [comment] 2023-01-06 20:21
Still doesn't work for me. Using version 2022.12.14.1 flatpak on fedora.
No nvngx.dll in system32 of the bottle.

**Comment by Kinsteen** [comment] 2023-01-07 11:12
@AlawamiAZ Can you launch bottles from the command line, and change nvapi versions in your Bottle? It should work if you change versions

**Comment by cyberphantom52** [comment] 2023-01-07 18:30
> Still doesn't work for me. Using version 2022.12.14.1 flatpak on fedora. No nvngx.dll in system32 of the bottle.



> @AlawamiAZ Can you launch bottles from the command line, and change nvapi versions in your Bottle? It should work if you change versions. If it doesn't, please send logs.


I should probably mention that in #2183 i only fixed DLSS for non flatpak version of bottles, i wasn't familiar with how libs should be copied in flatpaks.

**Comment by Kinsteen** [comment] 2023-01-07 21:07
It's true it doesn't work under Flatpak. I created a PR that adds a "disabled" option for nvapi, and fixes the Flatpak behavior here #2495.

**Comment by alou-S** [comment] 2023-06-20 15:01
The issue doesn't seem to be fixed yet. Tested on Cyberpunk again and DLSS is greyed out. Working just fine within Proton.

**Comment by Bleuzen** [comment] 2023-11-01 16:46
Hi, any news on this? DLSS still does NOT work. Looking at the console logs, it seems to fail adding the dll overrides to the registry:
```
17:44:14 (INFO) Setting Key dxvk_nvapi=True for bottle xxx… 
/home/xxx/.var/app/com.usebottles.bottles/data/bottles/nvapi/dxvk-nvapi-v0.6.4/x32/nvapi.dll -> /home/xxx/.var/app/com.usebottles.bottles/data/bottles/bottles/xxx/drive_c/windows/syswow64/nvapi.dll
/home/xxx/.var/app/com.usebottles.bottles/data/bottles/nvapi/dxvk-nvapi-v0.6.4/x64/nvapi64.dll -> /home/xxx/.var/app/com.usebottles.bottles/data/bottles/bottles/xxx/drive_c/windows/system32/nvapi64.dll
/usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine/nvngx.dll -> /home/xxx/.var/app/com.usebottles.bottles/data/bottles/bottles/xxx/drive_c/windows/system32/nvngx.dll
/usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine/_nvngx.dll -> /home/xxx/.var/app/com.usebottles.bottles/data/bottles/bottles/xxx/drive_c/windows/system32/_nvngx.dll
17:44:14 (INFO) Importing bundle to xxx registry 
17:44:15 (INFO) Using Wine debug tool -- get_processes 
wine: could not open working directory L"unix\\home\\xxx\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\xxx\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\xxx\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\xxx\\", starting in the Windows directory.
17:44:15 (INFO) Using Wine Registry CLI -- import_bundle 
wine: could not open working directory L"unix\\home\\xxx\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\xxx\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\xxx\\.var\\app\\com.usebottles.bottles\\data\\bottles\\bottles\\xxx\\", starting in the Windows directory.
17:44:16 (INFO) Import bundle result: 'reg: The file '/home/xxx/.var/app/com.usebottles.bottles/data/bottles/temp/4c75965d-8e00-4441-a169-4d5f27323b1d.reg' was not found.
```
Using Bottles version 51.9 in flatpak

**Comment by norbertkeri** [comment] 2023-12-04 23:50
Using Sultech's solution from above made DLSS work for me in Ratchet and clank: Rift Apart. I added "nvapi64" and "nvapi" to DLL overrideds as "native, then builtin".
