### ISSUE TITLE
[Bug]: Enable toggle switch shows blue when disabled

### ISSUE THREAD

**Issue by HubKing** [bottlesdevs/Bottles#3025] opened 2023-08-08 23:51 UTC
### Describe the bug

Blue when disabled. See the screen recording.

### To Reproduce

1. Display settigs.
2. Toggle the switches.

### Package

Flatpak from Flathub

### Distribution

Arch

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.4.8-arch1-1
Disk:
    Total: 16787968000
    Free: 16787808256
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 21.3GiB
Bottles_envs: null
```

### Additional context

[Screencast from 2023-08-09 08-47-27.webm](https://github.com/bottlesdevs/Bottles/assets/10900489/a030d5c7-3a97-448c-bf53-c16c28a93501)

**Comment by koplo199** [comment] 2023-08-17 08:36
Duplicate of #2877 and fixed by #2882

**Closed** 2023-08-17 09:09 UTC
