### ISSUE TITLE
 "Add Desktop Entry" is misleading 

### ISSUE THREAD

**Issue by kryotek777** [bottlesdevs/Bottles#2756] opened 2023-02-28 20:16 UTC
### Describe the bug

The "Add Desktop Entry" button creates a shortcut in `~/.local/share/applications/` (application menu) instead of the user's desktop

No error is thrown since [it seems to be intended behaviour](https://github.com/bottlesdevs/Bottles/blob/6e583e408e18a47ffdcf83c46443b11badbdc22a/bottles/backend/utils/manager.py#L232)

I believe that the button's name should be changed or that bottles should create an actual desktop shortcut

### To Reproduce

1. Create a new bottle
2. Add any program
3. Click on the three dots 
4. Click Add Desktop Entry

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.1-zen1-1-zen
Disk:
    Total: 16786808832
    Free: 16786661376
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 23.6GiB
Bottles_envs: null
```

**Comment by TheEvilSkeleton** [comment] 2023-03-01 21:55
That's the intended behavior, as you described. [Desktop entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) is a specification by freedesktop.org for application menus.

@jannuary do you think we should change the name to, e.g. "Add to Application Menu" or should we stick with "Add Desktop Entry"?

**Comment by kryotek777** [comment] 2023-03-01 23:21
> That's the intended behavior, as you described. [Desktop entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) is a specification by freedesktop.org for application menus.
> 
> @jannuary do you think we should change the name to, e.g. "Add to Application Menu" or should we stick with "Add Desktop Entry"?

Thank you for confirming that's intended behaviour. 

"Add to Application Menu" is way more descriptive, I don't think the average user knows about freedesktop standards.

Anyway, I think a quick way to create an actual desktop shortcut would be a cool feature

**Comment by jannuary** [comment] 2023-03-02 01:21
We had this same discussion in #1722.

**Comment by TheEvilSkeleton** [comment] 2023-03-02 14:53
So, should we call it "Add to App Menu" or "Add to App Grid"? I agree with Mirko that App Menu sounds better.

**Comment by QmwJlHuSg9pa** [comment] 2023-03-07 10:36
FWIW, XDG seems to prefer "application menu":

- https://specifications.freedesktop.org/menu-spec/latest/ar01s02.html
- https://portland.freedesktop.org/doc/xdg-desktop-menu.html

**Comment by jannuary** [comment] 2023-03-07 10:54
"Application Menu" can be weird, since on GNOME, "App Menu" refers to the menu of the running app with the "New Window" and "Quit" commands.

**Comment by QmwJlHuSg9pa** [comment] 2023-03-07 13:12
Hmm, "Application menu"/"app menu" nomenclature for individual applications seem to have been discontinued with [GNOME v3.32](https://help.gnome.org/misc/release-notes/3.32/#general) (2019), in favour of the newer "primary/secondary menu" system.

Currently, GNOME uses "Activities" for their default menu, though they also support an official, classic "[Applications Menu](https://extensions.gnome.org/extension/6/applications-menu/)" extension (2nd in popularity at GNOME Extensions). Meanwhile, the [ArcMenu](https://gitlab.com/arcmenu/ArcMenu) extension (15th in popularity) refers to itself as "Application Menu Extension for GNOME". Previously, GNOME 2 (2002) referred to its menu as an "[Applications menu](https://web.archive.org/web/20021020140051/http://developer.gnome.org/projects/gup/hig/1.0/desktop-integration.html#application-menu-entries)".

KDE refers to its default menu as "[Application Launcher](https://docs.kde.org/stable5/en/plasma-desktop/plasma-desktop/panel.html#panel-launcher)", whilst including an alternative "traditional" menu called "Application Menu".

My vote at this point might be for "Add to Applications menu"? Regardless, the option could do with a tooltip with some further context as to its intended function?

**Comment by jannuary** [comment] 2023-03-07 14:39
> Hmm, "Application menu"/"app menu" nomenclature for individual applications seem to have been discontinued with [GNOME v3.32](https://help.gnome.org/misc/release-notes/3.32/#general) (2019), in favour of the newer "primary/secondary menu" system.

Apps can no longer put their stuff in menus, but the app menu is (so far) still very much a thing.

Regardless, I don't see why should we be influenced by platforms we are not targeting, extensions, or GNOME version that's 21 (!) years old, considering every official GNOME source says "App Grid", and the HIG explicitly says to use platform-specific terms:

> When referring to parts of the user interface, use the standard GNOME terms, such as “pointer” and “window”.

**Comment by MrQuerter** [comment] 2023-03-07 15:11
> I don't see why we should be influenced by platforms we are not targeting
Just out of curiosity, what are the platforms Bottles is targeting? Isn't it supposed to be working on every platform thanks to Flatpak?

**Comment by jannuary** [comment] 2023-03-07 15:20
Bottles is targeting GNOME. To be clear, "targeting" a specific platform doesn't mean that it will only be compatible with that platform, just that it's expected to use its libraries, comply by its interface guidelines and support its system features.

**Comment by QmwJlHuSg9pa** [comment] 2023-03-07 17:17
> Apps can no longer put their stuff in menus, but the app menu is (so far) still very much a thing.

Ah, I see now -- I assumed it had been retired. I'm using the "Dash to Panel" extension, which somehow kills the "Application menu", even after disabling extensions -- GNOME Shell must then be restarted for the "Application menu" to reappear.

> Regardless, I don't see why we should be influenced by platforms we are not targeting, extensions, or a GNOME version that's 21 (!) years old, considering every official current GNOME source says "App Grid", and the HIG explicitly says to use platform-specific terms:

I thought it significant to consider how these UI concepts had been popularly referred to through history.

In any case, it seems there are two distinct concepts with similar names currently referred to by GNOME Help (official user docs): "[Application menu](https://gitlab.gnome.org/GNOME/gnome-user-docs/-/blob/master/gnome-help/C/shell-introduction.page#L128)" -- GNOME 3, 4 and Classic; and "[Applications menu](https://gitlab.gnome.org/GNOME/gnome-user-docs/-/blob/master/gnome-help/C/shell-apps-open.page#L47)" -- GNOME Classic (desktop session or via extensions, both of which are officially supported by GNOME).

The most notable reference I can find to "app grid" (aside from within Gitlab) is [GNOME 40's release notes](https://help.gnome.org/misc/release-notes/40.0/). Interestingly, the phrase "app grid" is nowhere to be found in GNOME Help; rather, "Activities overview" seems to be the operative phrase when referring to the view that includes the "app grid":

> Move your mouse pointer to the **Activities** corner at the top left of the screen to show the **Activities** overview. This is where you can find all of your applications. You can also open the overview by pressing the `Super` key.
> 
> There are several ways of opening an application once you’re in the Activities overview:
> - [...]
> - Click the grid button (which has nine dots) in the dash. You will see the first page of all installed applications. To see more applications, press the dots at the bottom, above the dash, to view other applications. Press on the application to start it.

The GNOME Classic version of this section actually refers to both menus:

> You can start applications from the **Applications** menu at the top left of the screen, or you can use the **Activities** overview by pressing the `Super` key.

Seeing as the docs are guiding users to the "Activities overview" or the "Applications menu", then I'd think either is a good GNOME-centric starting point, if any. Of the two, I'd say "Applications menu" fits better as a generic term, though has the somewhat unfortunate baggage of being confused with the term "Application menu", as you've pointed out.

**Comment by yaomtc** [comment] 2023-03-10 07:31
I actually have an issue with this function: I have the Bottles flatpak installed on a fresh install of Arch Linux with Plasma, and this comes up when I try to create a desktop entry....

> Choose Application - Portal
> 
> Choose an application to open 'https'

Then it gives me a list of some of the software I have installed.

Should I make a new report for this?

**Comment by yaomtc** [comment] 2023-03-10 21:14
Ah, my mistake - for some reason Plasma doesn't choose anything as the default web browser when Firefox is the only web browser installed. Nothing to do with Bottles. Fixed now, sorry!

**Comment by Perkolator** [comment] 2023-03-16 04:35
What about "Add to Applications"? And a new feature "Add to Desktop" for just creating a desktop shortcut without adding to applications?

I'd like to see the latter option, useful for games that you just play once and then uninstall (that's how I use the desktop, only for everything temporary, functions kind of as a reminder too), but normal programs that one intends to use regularly, one could add to applications.

**Comment by yaomtc** [comment] 2023-03-16 04:41
It is a bit silly that they're called "desktop entries", but I don't think their precise name needs to be used. "Add to Applications" would make more sense as it's more of a layman's term / plain English

**Closed** 2024-01-21 19:07 UTC
Labels: Not a bug
