### ISSUE TITLE
[Request]: MFC140 missing in the dependencies section

### ISSUE THREAD

**Issue by Twig6943** [bottlesdevs/Bottles#3569] opened 2024-11-24 11:21 UTC
### Tell us the problem or your need

![image](https://github.com/user-attachments/assets/270c1be0-5a65-4554-8a79-6672c09b6078)

### Describe the solution you'd like

title.

### Other solutions?

title.

### Additional context and references

title.

**Comment by mirkobrombin** [comment] 2024-12-07 12:46
Duplicate of https://github.com/bottlesdevs/dependencies/issues/157

**Closed by mirkobrombin** 2024-12-07 12:46 UTC
Labels: Feature request
