### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by ovari** [bottlesdevs/Bottles#384] opened 2021-07-19 08:11 UTC
This crash report was generated by Bottles.

**Details**
* **package**: AppImage

**Log**
```python3
[Errno 2] Nincs ilyen fájl vagy könyvtár: '/home/c/.local/share/bottles/temp/dxvk-1.9.tar.gz'  File "/tmp/.mount_BottleQljqcb///usr/local/share/bottles/bottles/utils.py", line 198, in target
    result = self.task_func(*args, **kwargs)

  File "/tmp/.mount_BottleQljqcb///usr/local/share/bottles/bottles/runner.py", line 251, in async_install_component
    self.extract_component(component_type, archive)

  File "/tmp/.mount_BottleQljqcb///usr/local/share/bottles/bottles/runner.py", line 146, in extract_component
    tar = tarfile.open("%s/%s" % (BottlesPaths.temp, archive))

  File "/tmp/.mount_BottleQljqcb/usr/lib/python3.9/tarfile.py", line 1611, in open
    return func(name, "r", fileobj, **kwargs)

  File "/tmp/.mount_BottleQljqcb/usr/lib/python3.9/tarfile.py", line 1675, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)

  File "/tmp/.mount_BottleQljqcb/usr/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')

```

**Comment by mirkobrombin** [comment] 2021-07-19 09:33
duplicate of #382

**Closed by mirkobrombin** 2021-07-19 09:33 UTC
