### ISSUE TITLE
[Request]: Different App Icon when Launching an exe from Bottles

### ISSUE THREAD

**Issue by the16bitgamer** [bottlesdevs/Bottles#3505] opened 2024-09-21 01:27 UTC
### Tell us the problem or your need

When using Bottles to launch multiple programs in the Dash/Panel in Linux Mint/Ubuntu, the icon that is used is the same as Bottles which cascades it, making quick Program Switching between one application and another harder than it should be.

### Describe the solution you'd like

When launching an application, if the app has an icon like the ones found in the "icons" folder in a Bottle, it should be used as the dock/panel icon to separate it out from the Bottles application

### Other solutions?

Another option is to be able to configure the icon used, with the default left to the bottles icon. That way if it bugs the end user it can be manually done.

### Additional context and references

This is in comparison with Lutris which uses the app icon when launching an application. Though this may just be a default wine property which has been overridden here.

**Comment by CaptainMorgan12** [comment] 2024-10-10 15:04
Not sure that is related, but if you add an application to your library it would be great to be able to manually point to an icon image file for each library item, then this icon would be used everywhere:

![image](https://github.com/user-attachments/assets/511392af-1cd0-44a8-8a30-a59c5ceb965c)

**Comment by jntesteves** [comment] 2024-10-11 15:38
I think this issue might get solved when desktop compositors implement this new (staging) Wayland protocol and Flatpak (and maybe Wine also) starts using it: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269

**Comment by Perkolator** [comment] 2024-10-13 16:17
Duplicate of #2985 ?

**Closed** 2024-10-13 18:17 UTC
Labels: Feature request
