### ISSUE TITLE
[Bug]: bug after importing bottles archive

### ISSUE THREAD

**Issue by baaannnaaannn** [bottlesdevs/Bottles#3071] opened 2023-09-05 07:42 UTC
### Describe the bug

i gave bug with this steps
1.export full archive
2.change distribution
3.import bottle archive
4.see the error

### To Reproduce

1.export full archive
2.change distribution
3.import bottle archive
4.see the error

### Package

Flatpak from Flathub

### Distribution

Fedora 38

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.4.13-200.fc38.x86_64
Disk:
    Total: 2570215424
    Free: 2570059776
RAM:
    MemTotal: 4.8GiB
    MemAvailable: 1.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
Error -3 while decompressing data: invalid block type  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/backup.py", line 148, in import_backup
    safe_extract(tar, Paths.bottles)

  File "/app/share/bottles/bottles/backend/managers/backup.py", line 141, in safe_extract
    for member in _tar.getmembers():

  File "/usr/lib/python3.10/tarfile.py", line 1987, in getmembers
    self._load()        # all members, we first have to

  File "/usr/lib/python3.10/tarfile.py", line 2682, in _load
    tarinfo = self.next()

  File "/usr/lib/python3.10/tarfile.py", line 2587, in next
    self.fileobj.seek(self.offset - 1)

  File "/usr/lib/python3.10/gzip.py", line 393, in seek
    return self._buffer.seek(offset, whence)

  File "/usr/lib/python3.10/_compression.py", line 153, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))

  File "/usr/lib/python3.10/gzip.py", line 496, in read
    uncompress = self._decompressor.decompress(buf, size)
```

**Comment by orowith2os** [comment] 2023-09-05 08:24
Probably also a dupe of https://github.com/bottlesdevs/Bottles/issues/2904, but nobody else there has provided actual logs, so closing as dupe on an assumption.

**Closed by orowith2os** 2023-09-05 08:24 UTC
