### ISSUE TITLE
[Crash report]  checks() got an unexpected k

### ISSUE THREAD

**Issue by andyl** [bottlesdevs/Bottles#830] opened 2021-12-20 03:36 UTC
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottleU4pZ83///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by andyl** [comment] 2021-12-20 03:38
AppImage not installing on Ubuntu 20.04 - It hangs indefinitely at the "Downloading..." prompt.

**Comment by mirkobrombin** [comment] 2021-12-20 06:11
Duplicate of #784

**Closed by mirkobrombin** 2021-12-20 06:11 UTC
