### ISSUE TITLE
[Bug]: Could Not launch game on Steam deck (Caused by the space in the file path)

### ISSUE THREAD

**Issue by xtremforce** [bottlesdevs/Bottles#3236] opened 2024-01-09 10:47 UTC
### Describe the bug

Games run okay via Bottles, but after "Add to Steam", they cannot launch.

I figured it out.
The problem is caused by the space in the file path.

### To Reproduce

1. Add a game to Bottles with a path that contains spaces, like ".../path with space/game.exe."
2. Use the menu option "Add to Steam."
3. The app will not be able to launch via Steam.
4. Using `xdg-open bottles:run/'BOTTLE_NAME'/'PROGRAM_NAME'` or CLI with `flatpak run --command=bottles-cli com.usebottles.bottles run -b BOTTLE_NAME -p PROGRAM_NAME` in the terminal, neither of them can launch the game.
5. Using the CLI with `flatpak run --command=bottles-cli com.usebottles.bottles run -b BOTTLE_NAME -e "/file/path with space/game.exe"` (path wrapped with quotes) works.

### Package

Flatpak from Flathub

### Distribution

SteamOS

### Debugging Information

```shell
N/A
```

**Comment by SapryWenInera** [comment] 2024-01-10 02:08
I'm suffering the same in Fedora Kinoite. Running in the terminal prints this error:
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 652, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 199, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 574, in run_program
    _args = program.get("arguments", "") + " " + _args
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

~

**Comment by SapryWenInera** [comment] 2024-01-10 02:09
```
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 652, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 199, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 574, in run_program
    _args = program.get("arguments", "") + " " + _args
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by 13xforever** [comment] 2024-01-29 07:19
I think this is a duplicate of #3210 and not an issue with the space

**Comment by mirkobrombin** [comment] 2024-04-25 17:14
Duplicate of https://github.com/bottlesdevs/Bottles/issues/3210 (actually)

**Closed by mirkobrombin** 2024-04-25 17:14 UTC
