### ISSUE TITLE
[Crash report]  checks() got an unexpected k

### ISSUE THREAD

**Issue by Algamerthetruealbanian** [bottlesdevs/Bottles#791] opened 2021-12-14 20:51 UTC
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso

**Log**
```python3
checks() got an unexpected keyword argument 'after'  File "/tmp/.mount_BottleemqKtf///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by mirkobrombin** [comment] 2021-12-14 21:02
Duplicate of #790

**Closed by mirkobrombin** 2021-12-14 21:02 UTC
