### ISSUE TITLE
[Bug]: Crash Report

### ISSUE THREAD

**Issue by WaylonX** [bottlesdevs/Bottles#2436] opened 2022-12-24 04:43 UTC
### Describe the bug

Crashed when starting after installing dotnet472

### To Reproduce

1) Start Bottles.

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1 Cinnamon

### Troubleshooting Logs

```shell
'config'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 58, in launch
    res = WineCommand(

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 97, in __init__
    self.config = self.__get_config(config)

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 111, in __get_config
    return config.data["config"]
```

**Comment by mirkobrombin** [comment] 2023-01-05 17:11
Duplicate of #2476. Please search before opening new issues, the review task is time consuming.

**Closed by mirkobrombin** 2023-01-05 17:11 UTC
