### ISSUE TITLE
[Crash report]  'NoneType' object has no att

### ISSUE THREAD

**Issue by fwsmit** [bottlesdevs/Bottles#2075] opened 2022-09-16 09:28 UTC
This crash report was generated by Bottles.

**This happened when turning off dxvk for an application. I did not notice anything was wrong, though.**
* **package**: Flatpak
* **version**: 2022.8.28-brescia-2

**Log**
```python3
'NoneType' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    if program.get("dxvk") != dxvk:

```

**Comment by mirkobrombin** [comment] 2022-09-16 11:03
duplicate of #1999

**Closed by mirkobrombin** 2022-09-16 11:03 UTC
