### ISSUE TITLE
[BUG] Net Framework 3.5 does not install

### ISSUE THREAD

**Issue by NetDwarf** [bottlesdevs/Bottles#944] opened 2022-01-18 12:39 UTC
**Describe the bug**
Net Framework applications at least on Net 3.5 don't seem to work, probably also on other versions. 

**Installation**
 - Method: flatpak (AppImage doesn't come that far)
 - Version 2022.1.14-trento-2

**To Reproduce**
1. Create new bottle
2. (do nothing or install .Net 3.5/4.0/4.5... or install mono or install everything)
3. Install your .Net Framework application (i.e. DAoC Portal)
4. Start that application
5. See error

**Expected behavior**
Application stops right after starting it. Terminal shows error message:
```
00fc:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"Portal.exe" cannot be loaded
00fc:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files (x86)\\DAoC Portal\\Portal.exe" failed, status c0000135
```

**Desktop (please complete the following information):**
 - OS: Debian
 - Version bookworm
 - Display server: X11
 
**Additional context**

The same application in a previous bottle worked a month ago and stopped working (in the same bottle). The new bottle is of course only created for troubleshooting.

**Comment by mirkobrombin** [comment] 2022-01-18 12:43
If you haven’t recreated the bottle it should just works as before, did you made other changes?

**Comment by XT-Martinez** [comment] 2022-01-18 16:53
I'm also encountering this issue.
It seems to me that the .NET Framework was not properly installed when I installed it via the Dependency tab.

I'm getting this error when trying to install dotnet35
![image](https://user-images.githubusercontent.com/32611135/149982050-6e6b4377-1412-43b7-9692-3b481360e2cb.png)

**Comment by Githob2021** [comment] 2022-01-18 18:31
This may explain why a huge majority of my games won't work since I did a fresh install of Linux. I've wasted 2 days trying to figure out what's wrong right now as I didn't think I did anything different. The logs don't say anything helpful either, just makes it look like the game launches then closes without logging. Or sometimes it will say like in the first message

```
00fc:err:module:LdrInitializeThunk Importing dlls for L:C......
```

**Comment by NetDwarf** [comment] 2022-01-18 20:59
> If you haven’t recreated the bottle it should just works as before, did you made other changes?

No, I used it once in a while, because there runs only one program essentially. I can't exactly remember when I accessed it the last time and it worked, probably only a few weeks ago. I tried to revert to an older version of Bottles (2021.12.14-treviso-4), but that didn't help either.

**Comment by lumingzh** [comment] 2022-01-19 10:09
> I'm also encountering this issue. It seems to me that the .NET Framework was not properly installed when I installed it via the Dependency tab.
> 
> I'm getting this error when trying to install dotnet35 ![image](https://user-images.githubusercontent.com/32611135/149982050-6e6b4377-1412-43b7-9692-3b481360e2cb.png)
> 
> Edit: I'm also using the flatpak version (2022.1.14-trento-2)

Yes, same error here. Can't install .net 3.5 or 3.5sp1.

**Comment by mirkobrombin** [comment] 2022-01-19 11:27
The dep installation force winxp to avoid this problem, it was working last time I’ve checked

**Comment by Githob2021** [comment] 2022-01-20 17:45
> The dep installation force winxp to avoid this problem, it was working last time I’ve checked

Were you trying to say to use 'Windows XP" Windows version to fix this issue? Because I switched the bottle from Windows 10 to Windows XP and it is still the same. I am trying to play XCOM Enemy Unknown. As far as I know, the dependencies are VC 2010 SP1 and DX which I installed. I get the same error below with Windows XP:

```
0120:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"XCOMLauncher.exe" cannot be loaded
0120:err:module:LdrInitializeThunk Importing dlls for L"C:\\XCOM Enemy Unknown\\XEW\\Binaries\\Win32\\XCOMLauncher.exe" failed, status c0000135
```

Here is my bottles.yml

```
Arch: win64
Creation_Date: '2022-01-20 12:26:38.091700'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.3
Environment: Gaming
Environment_Variables: {}
External_Programs:
    XComGame.exe:
        executable: XComGame.exe
        name: XComGame
        path: /home/XXXXXXXXXXXXX/Downloads/Bottles/xcom/drive_c/XCOM Enemy Unknown/Binaries/Win32/XComGame.exe
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- vcredist2010
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.1
Name: xcom
Parameters:
    aco_compiler: true
    discrete_gpu: true
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: true
    fixme_logs: false
    fsr: true
    fsr_level: 5
    fullscreen_capture: false
    gamemode: true
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    pulseaudio_latency: true
    sync: esync
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: true
Path: xcom
Programs: {}
Runner: caffe-7.0
State: 0
Uninstallers:
    arial32: false
    courie32: false
    d3dcompiler_43: false
    d3dcompiler_47: false
    d3dx9: false
    msls31: false
    times32: false
    vcredist2010: true
Update_Date: '2022-01-20 12:43:38.553309'
VKD3D: vkd3d-proton-2.5
Versioning: false
Windows: winxp
WorkingDir: ''

```

**Comment by mirkobrombin** [comment] 2022-01-21 09:06
Dotnet should have been fixed with latest commits (not released), I’ll try on my. 

The second log is not a blocking thing

**Comment by NetDwarf** [comment] 2022-01-21 11:57
dotnet35 is now not installing even if you manually set "Windows Version" to "Windows XP". The error is the common:
![image](https://user-images.githubusercontent.com/14839491/150520727-c798be56-1245-4dc9-879a-436a85f2674e.png)
And in terminal it looks like this: 
```
04f8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
04f8:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
04f8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
050c:err:eventlog:ReportEventW L"setup.exe"
050c:err:eventlog:ReportEventW L"9.0.21022.8"
050c:err:eventlog:ReportEventW L"47316ce5"
050c:err:eventlog:ReportEventW L"sitsetup.dll"
050c:err:eventlog:ReportEventW L"9.0.21022.8"
050c:err:eventlog:ReportEventW L"47316ce2"
050c:err:eventlog:ReportEventW L"0"
050c:err:eventlog:ReportEventW L"00047c8b"
```

Which indicates it's not using Windows XP. After trying to install dotnet35 "Windows Version" is set to "Windows 10" in wineconfig. Here is also a mismatch with what Bottles is showing as it's still set to "Windows XP".

This might be the culprit at the start of the installation process:
```
INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] for Key: [VersionNumber] in register bottle: NuBottle
```

But here is the full log:
<details>
<summary>Complete dotnet35 install log</summary>
```
(12:48:10) INFO Setting Key: [Windows] to [winxp] for bottle: [NuBottle]… 
(12:48:11) INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] for Key: [VersionNumber] in register bottle: NuBottle 
(12:48:12) INFO Using Xwayland.. 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
(12:48:12) INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] for Key: [CurrentVersion] in register bottle: NuBottle 
(12:48:15) INFO Using Xwayland.. 
(12:48:15) INFO Using Xwayland.. 
(12:48:15) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] for Key: [ProductType] in register bottle: NuBottle 
(12:48:17) INFO Using Xwayland.. 
(12:48:17) INFO Using Xwayland.. 
(12:48:18) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ServiceCurrent] for Key: [OS] in register bottle: NuBottle 
(12:48:20) INFO Using Xwayland.. 
(12:48:20) INFO Using Xwayland.. 
(12:48:20) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] for Key: [CSDVersion] in register bottle: NuBottle 
(12:48:22) INFO Using Xwayland.. 
(12:48:23) INFO Using Xwayland.. 
(12:48:23) INFO Removing Value: [HKEY_CURRENT_USER\Softwarw\Wine] for Key: [Version] in register bottle: NuBottle 
(12:48:25) INFO Using Xwayland.. 
(12:48:25) INFO Using Xwayland.. 
(12:48:25) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CSDVersion] and Data: [Service Pack 2] in register bottle: NuBottle 
(12:48:28) INFO Using Xwayland.. 
(12:48:28) INFO Using Xwayland.. 
(12:48:28) INFO reg: The operation completed successfully
	
 
(12:48:28) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CurrentBuildNumber] and Data: [3790] in register bottle: NuBottle 
(12:48:30) INFO Using Xwayland.. 
(12:48:30) INFO Using Xwayland.. 
(12:48:31) INFO reg: The operation completed successfully
	
 
(12:48:31) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CurrentVersion] and Data: [5.2] in register bottle: NuBottle 
(12:48:33) INFO Using Xwayland.. 
(12:48:33) INFO Using Xwayland.. 
(12:48:33) INFO reg: The operation completed successfully
	
 
(12:48:33) INFO Adding Key: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] with Value: [ProductType] and Data: [WinNT] in register bottle: NuBottle 
(12:48:35) INFO Using Xwayland.. 
(12:48:36) INFO Using Xwayland.. 
(12:48:36) INFO reg: The operation completed successfully
	
 
(12:48:36) INFO Adding Key: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] with Value: [CSDVersion] and Data: [00000200] in register bottle: NuBottle 
(12:48:38) INFO Using Xwayland.. 
(12:48:38) INFO Using Xwayland.. 
(12:48:38) INFO reg: The operation completed successfully
	
 
(12:48:38) INFO Using Xwayland.. 
(12:48:49) WARNING Cannot find states.yml file for bottle: [NuBottle] 

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Gtk-CRITICAL **: 12:48:49.617: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed

(bottles:2): Handy-CRITICAL **: 12:48:49.621: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed
(12:49:02) INFO Running winecfg on the wineprefix… 
(12:49:02) INFO Using Xwayland.. 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
(12:49:08) INFO Installing dependency [dotnet35] in bottle [NuBottle]. 
(12:49:08) INFO Using Xwayland.. 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
(12:49:09) INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] for Key: [VersionNumber] in register bottle: NuBottle 
(12:49:12) INFO Using Xwayland.. 
(12:49:12) INFO Using Xwayland.. 
(12:49:12) INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] for Key: [CurrentVersion] in register bottle: NuBottle 
(12:49:14) INFO Using Xwayland.. 
(12:49:14) INFO Using Xwayland.. 
(12:49:15) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] for Key: [ProductType] in register bottle: NuBottle 
(12:49:17) INFO Using Xwayland.. 
(12:49:17) INFO Using Xwayland.. 
(12:49:17) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ServiceCurrent] for Key: [OS] in register bottle: NuBottle 
(12:49:19) INFO Using Xwayland.. 
(12:49:20) INFO Using Xwayland.. 
(12:49:20) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] for Key: [CSDVersion] in register bottle: NuBottle 
(12:49:22) INFO Using Xwayland.. 
(12:49:22) INFO Using Xwayland.. 
(12:49:22) INFO Removing Value: [HKEY_CURRENT_USER\Softwarw\Wine] for Key: [Version] in register bottle: NuBottle 
(12:49:25) INFO Using Xwayland.. 
(12:49:25) INFO Using Xwayland.. 
(12:49:25) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CSDVersion] and Data: [Service Pack 2] in register bottle: NuBottle 
(12:49:27) INFO Using Xwayland.. 
(12:49:28) INFO Using Xwayland.. 
(12:49:28) INFO reg: The operation completed successfully
	
 
(12:49:28) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CurrentBuildNumber] and Data: [3790] in register bottle: NuBottle 
(12:49:30) INFO Using Xwayland.. 
(12:49:30) INFO Using Xwayland.. 
(12:49:30) INFO reg: The operation completed successfully
	
 
(12:49:30) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CurrentVersion] and Data: [5.2] in register bottle: NuBottle 
(12:49:32) INFO Using Xwayland.. 
(12:49:33) INFO Using Xwayland.. 
(12:49:33) INFO reg: The operation completed successfully
	
 
(12:49:33) INFO Adding Key: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] with Value: [ProductType] and Data: [WinNT] in register bottle: NuBottle 
(12:49:35) INFO Using Xwayland.. 
(12:49:35) INFO Using Xwayland.. 
(12:49:36) INFO reg: The operation completed successfully
	
 
(12:49:36) INFO Adding Key: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] with Value: [CSDVersion] and Data: [00000200] in register bottle: NuBottle 
(12:49:38) INFO Using Xwayland.. 
(12:49:38) INFO Using Xwayland.. 
(12:49:38) INFO reg: The operation completed successfully
	
 
(12:49:38) INFO Using Xwayland.. 
(12:49:38) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscoree] and Data: [native,builtin] in register bottle: NuBottle 
(12:49:41) INFO Using Xwayland.. 
(12:49:41) INFO Using Xwayland.. 
(12:49:41) INFO reg: The operation completed successfully
	
 
(12:49:41) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscorwks] and Data: [native,builtin] in register bottle: NuBottle 
(12:49:43) INFO Using Xwayland.. 
(12:49:43) INFO Using Xwayland.. 
(12:49:44) INFO reg: The operation completed successfully
	
 
(12:49:44) WARNING File [dotnet35.exe] already exists in temp, skipping. 
(12:49:44) INFO Running an executable on the bottle… 
(12:49:44) INFO Using Xwayland.. 
04b8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
04b8:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
04b8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
04cc:err:eventlog:ReportEventW L"setup.exe"
04cc:err:eventlog:ReportEventW L"9.0.21022.8"
04cc:err:eventlog:ReportEventW L"47316ce5"
04cc:err:eventlog:ReportEventW L"sitsetup.dll"
04cc:err:eventlog:ReportEventW L"0.0.0.0"
04cc:err:eventlog:ReportEventW L"47316ce2"
04cc:err:eventlog:ReportEventW L"0"
04cc:err:eventlog:ReportEventW L"00047c8b"
(12:49:54) INFO Using Xwayland.. 
(12:49:55) INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] for Key: [VersionNumber] in register bottle: NuBottle 
(12:49:57) INFO Using Xwayland.. 
(12:49:57) INFO Using Xwayland.. 
(12:49:57) INFO Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] for Key: [CurrentVersion] in register bottle: NuBottle 
(12:49:59) INFO Using Xwayland.. 
(12:50:00) INFO Using Xwayland.. 
(12:50:00) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] for Key: [ProductType] in register bottle: NuBottle 
(12:50:02) INFO Using Xwayland.. 
(12:50:02) INFO Using Xwayland.. 
(12:50:02) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ServiceCurrent] for Key: [OS] in register bottle: NuBottle 
(12:50:05) INFO Using Xwayland.. 
(12:50:05) INFO Using Xwayland.. 
(12:50:05) INFO Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] for Key: [CSDVersion] in register bottle: NuBottle 
(12:50:07) INFO Using Xwayland.. 
(12:50:08) INFO Using Xwayland.. 
(12:50:08) INFO Removing Value: [HKEY_CURRENT_USER\Softwarw\Wine] for Key: [Version] in register bottle: NuBottle 
(12:50:10) INFO Using Xwayland.. 
(12:50:10) INFO Using Xwayland.. 
(12:50:10) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CSDVersion] and Data: [] in register bottle: NuBottle 
(12:50:12) INFO Using Xwayland.. 
(12:50:13) INFO Using Xwayland.. 
(12:50:13) INFO reg: The operation completed successfully
	
 
(12:50:13) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CurrentBuildNumber] and Data: [10240] in register bottle: NuBottle 
(12:50:15) INFO Using Xwayland.. 
(12:50:15) INFO Using Xwayland.. 
(12:50:16) INFO reg: The operation completed successfully
	
 
(12:50:16) INFO Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] with Value: [CurrentVersion] and Data: [10.0] in register bottle: NuBottle 
(12:50:18) INFO Using Xwayland.. 
(12:50:18) INFO Using Xwayland.. 
(12:50:18) INFO reg: The operation completed successfully
	
 
(12:50:18) INFO Adding Key: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] with Value: [ProductType] and Data: [WinNT] in register bottle: NuBottle 
(12:50:20) INFO Using Xwayland.. 
(12:50:21) INFO Using Xwayland.. 
(12:50:21) INFO reg: The operation completed successfully
	
 
(12:50:21) INFO Adding Key: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] with Value: [CSDVersion] and Data: [00000000] in register bottle: NuBottle 
(12:50:23) INFO Using Xwayland.. 
(12:50:23) INFO Using Xwayland.. 
(12:50:24) INFO reg: The operation completed successfully
	
 
(12:50:24) INFO Using Xwayland.. 
(12:50:24) INFO Setting Key: [Installed_Dependencies] to [['d3dx9', 'msls31', 'arial32', 'times32', 'courie32', 'd3dcompiler_43', 'd3dcompiler_47', 'dotnet35']] for bottle: [NuBottle]… 
(12:50:24) INFO Setting Key: [dotnet35] to [True] for bottle: [NuBottle]…
```
</details>

**Comment by mirkobrombin** [comment] 2022-01-21 13:33
Maybe related to this #949

**Comment by NetDwarf** [comment] 2022-01-21 13:59
> Maybe related to this #949
> 
> Can someone try to set winxp from winecfg and run the dotnet installer manually (not from deps)?

#949 is mostly a display bug (a hidden one is the slow regedit process that can be interrupted, which can lead to not properly setting Windows Version in the first place). The problem arises because the installer resets Windows Version. 

I am going to try manually installing net35 installer later.

**Comment by mirkobrombin** [comment] 2022-01-21 15:23
#949 is not (only) a display bug, it was actually setting the wrong keys to the register, so some programs which use these to understand the Windows version, will get wrong data.

Also, the dependency reset the windows version only when the executable exit, so it should just works. I think the problem is something else, maybe a wrong override. I was able to install it some commits ago, so this seems like a regression (oh no). Let me know if changing from winecfg and manually running the executable make it works

**Comment by NetDwarf** [comment] 2022-01-21 18:21
When setting Windows XP correctly (which is hit and miss). The manual execution of dotnet35.exe fails with the same error still.

**Comment by mirkobrombin** [comment] 2022-01-21 19:36
![image](https://user-images.githubusercontent.com/9479903/150589349-b8777f7a-1cbf-4965-8be0-56a4bde430d0.png)

My release has a lot of commits beyond the stable and it works

**Closed** 2022-01-21 22:07 UTC
Labels: bug

**Comment by VandrerenErik** [comment] 2022-01-23 09:37
I'm still having this issue with he latest version

![image](https://user-images.githubusercontent.com/54407345/150672673-3d21af0e-9f58-4882-81ce-0e58c12194c4.png)

**Comment by calvincorrieri** [comment] 2023-12-21 05:09
I’m experiencing this issue on the latest flatpak version of Bottles

**Comment by derkrasseleo** [comment] 2024-01-08 16:55
Same here

**Comment by LeviMarvin** [comment] 2024-01-28 05:00
I have the same error within Windows 10 x64 sandbox. And I had installed the dotNet20 and dotNet20sp1

**Comment by orowith2os** [comment] 2024-01-28 05:48
It would appear Proton uses old versions of Wine to install dotnet, then it runs the installed binaries through new Proton. Doing something similar (setting PREFIX to the bottle, using Proton 5, etc) might help.

**Comment by LeviMarvin** [comment] 2024-01-28 06:04
@orowith2os Use --env=PREFIX to set the variable? How to use Proton 5 by this way?

**Comment by thegrasshopper104** [comment] 2024-06-24 14:11
I have the same issue on Bottles 51.11 Flatpak. I've tried setting the version to XP and I'm using --allow=devel as well, but it fails with Proton, Soda and Wine as well

**Comment by EmersonBiggons** [comment] 2024-06-29 06:27
> I have the same issue on Bottles 51.11 Flatpak. I've tried setting the version to XP and I'm using --allow=devel as well, but it fails with Proton, Soda and Wine as well

IDK how, but I have been having issues nonstop like everyone else. But Soda 9 made it work for me after I switched to it and hit "reinstall" on the dependancy.
