### ISSUE TITLE
[BUG] (Flatpak) Steam Crashing in OCI Container (Podman/Buildah)

### ISSUE THREAD

**Issue by TheFloatingBrain** [bottlesdevs/Bottles#1118] opened 2022-03-06 03:28 UTC
**Describe the bug**
I built an OCI image using buildah that takes advantage of the Nvidia Container Runtime, and has cuda, opengl, nvidia drivers and vulkan installed. I then built an image off of the vulkan image (based on nvidia's image) that installs flatpak and bottles

**Installation**
 - Method: Flatpak in OCI image via buildah/podman
 - Version 2022.2.28-trento-2, stable, system

**To Reproduce**
 -  Make (dockerfiles)[https://gist.github.com/TheFloatingBrain/facd6d0ece8dde42d10bad4028dc0858] 
 -  Install Steam through bottles
 -  Enter username/password and go through steam guard
 - Crash
 - Try again
 - It hangs & crashes
 - Close bottles
 - Try running bottles again
 - It crashes (X11 BadAccess)
 - Try again
 - It runs
 - See there is lower-case and upper-case steam in the program list :open_mouth: 
 - Try both, they both crash

**Expected behavior**
 - Open Steam GUI and be able to install/run games

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Podman, Nvidia Ubuntu 20.04/18.04 Image on Pop!_OS with Cosmic
 - Display server: Xorg
**Additional context**
```
info:  OpenVR: Failed to locate module
[0306/032737.296:WARNING:gpu_process_host.cc(1233)] The GPU process has crashed 6 time(s)
[0306/032737.297:ERROR:browser_gpu_channel_host_factory.cc(153)] Failed to launch GPU process.
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

0138:err:combase:RoGetActivationFactory Failed to find library for L"Windows.UI.ViewManagement.UISettings"
[0306/032737.596:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: utility
[0306/032737.607:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0306/032737.609:WARNING:dns_config_service_win.cc(700)] Failed to read DnsConfig.
[0306/032737.610:WARNING:dns_config_service_win.cc(747)] Failed to read DnsHosts.
[0306/032737.613:WARNING:dhcp_pac_file_fetcher_win.cc(559)] Unexpected error retrieving WPAD configuration from DHCP.
[0306/032737.615:WARNING:dhcp_pac_file_fetcher_win.cc(559)] Unexpected error retrieving WPAD configuration from DHCP.
[0306/032737.619:INFO:crash_reporting.cc(246)] Crash reporting enabled for process: renderer
[0306/032737.718:WARNING:dns_config_service_win.cc(700)] Failed to read DnsConfig.
info:  Game: steam.exe
info:  DXVK: v1.9.4
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to initialize OpenVR
info:  Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination
src\tier0\threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'SocketThread'
src\tier1\fileio.cpp (5125) : m_vecRegisteredWriters.Count() == 0
src\tier0\threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier0\threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'Thread(0x390F35F8/0x00000458/0x'
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\common\steamservice.cpp (58) : m_hServiceLib == NULL
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
[0306/032742.636:WARNING:dns_config_service_win.cc(700)] Failed to read DnsConfig.
[0306/032742.744:WARNING:dns_config_service_win.cc(700)] Failed to read DnsConfig.
src\tier0\threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'CIPCServer::m_ThreadClient'
src\tier1\fileio.cpp (5125) : m_vecRegisteredWriters.Count() == 0
src\tier0\threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier1\fileio.cpp (5187) : CFileWriterThread already exited
src\common\steamservice.cpp (57) : m_hSteamPipe == 0
src\common\steamservice.cpp (58) : m_hServiceLib == NULL
0324:err:esync:__esync_wait_objects Polling on fd 127 returned 0x20.
0190:err:esync:__esync_wait_objects Polling on fd 133 returned 0x20.
```

**Comment by mirkobrombin** [comment] 2022-03-06 06:58
I’m scared about going to reproduce this 😅

**Comment by mirkobrombin** [comment] 2022-05-13 12:52
Closing due to missing response

**Closed by mirkobrombin** 2022-05-13 12:52 UTC
Labels: Bug, help wanted
