### ISSUE TITLE
[BUG] AppImage does not start 3.1.8-x86_64

### ISSUE THREAD

**Issue by lkjell** [bottlesdevs/Bottles#279] opened 2021-05-20 00:39 UTC
**Describe the bug**
Does not start when running the appimage

**Installation**
 - Method:  Appimage
 - Version  3.1.8-x86_64

**To Reproduce**
* Download the appimage from the website
* Make it executable
* Run the appimage

**Expected behavior**
Do not crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Version 1

**Additional context**

```
./Bottles-3.1.8-x86_64.AppImage

(bottles:46721): Gtk-WARNING **: 02:34:47.770: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

**Comment by mirkobrombin** [comment] 2021-05-20 05:30
Duplicate of #230

**Closed by mirkobrombin** 2021-05-20 05:30 UTC
Labels: bug
