### ISSUE TITLE
[Crash report] Could not load a pixbuf from icon theme

### ISSUE THREAD

**Issue by QuinsZouls** [bottlesdevs/Bottles#590] opened 2021-10-03 16:06 UTC
**Describe the bug**
Bottles AppImage image don't run
```console
foo@bar:~$ ./Bottles-2021.9.28-treviso-x86_64_a63c2ca17b00736ef2eac61abf2c867d.AppImage  
Gtk-Message: 10:55:13.680: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:55:13.682: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 10:55:13.683: Failed to load module "appmenu-gtk-module"
Gtk-Message: 10:55:13.687: Failed to load module "xapp-gtk3-module"

(bottles:78502): Gtk-WARNING **: 10:55:14.217: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/alfredo/.local/share/icons/Tela-circle-purple/16/actions/image-missing.svg: No se ha reconocido el formato de imagen del archivo (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/alfredo/.local/share/icons/Tela-circle-purple/16/actions/image-missing.svg: No se ha reconocido el formato de imagen del archivo (gdk-pixbuf-error-quark, 3)

```
**Installation**
 - Method: AppImage
 - Version 2021.9.28-treviso

**To Reproduce**
1. Download lasted appimage of bottles in github
2. Install and  start bottles with terminal
3. See error

**Expected behavior**
Bottles Open

**Desktop (please complete the following information):**
 - OS: Arch LInux

**Additional context**
WIth bottles installation form AUR i don't have any problem, I think it is fixed by installing the missing icon pack, but it is a very ambiguous solution so I suggest taking some default icons from the system.

**Comment by mirkobrombin** [comment] 2021-10-03 18:05
We know there is a problem on first start. If you try again does it work or does it persist?

**Comment by QuinsZouls** [comment] 2021-10-03 18:10
I tried run again and it still not working, same error.

**Comment by mirkobrombin** [comment] 2021-10-04 07:02
I can't reproduce on Fedora, I need to set up a vm

**Comment by mirkobrombin** [comment] 2021-10-04 07:09
I can't reproduce on Fedora, I need to set up a vm.
Are you using Wayland?

**Comment by QuinsZouls** [comment] 2021-10-04 16:31
I use xorg with KDE plasma with clear installation, also i tried with garuda linux and same error (bottles AppImage won't run).
I try clear cache and update icon database but it still not working.
#### System Info:
OS: Garuda Linux x86_64
Kernel: 5.14.8-zen1-1-zen 
DE: Plasma 5.22.5 
Theme: Breeze Dark [Plasma], Flat-Remix-GTK-Red
Icons: Tela-circle-purple [Plasma], Tela-circle

**Comment by mirkobrombin** [comment] 2021-10-05 13:54
Oh ok this is using KDE.. I will test with it

**Comment by pushqrdx** [comment] 2021-11-16 19:00
@mirkobrombin I am still unable to use Bottle because of #230 it wasn't fixed and i just tried on a fresh debian system yet again and i get
```
(bottles:4704): Gtk-WARNING **: 20:57:03.882: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted
```

i really don't know what kind of stupid decision on the gtk side might render some application unusable because of a missing pixmap

**Comment by pushqrdx** [comment] 2021-11-16 19:22
```
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"
```
Good lord, finally fixed it, make sure that XDG_DATA_DIRS is properly set

**Comment by mirkobrombin** [comment] 2021-11-16 20:32
> ```
> export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"
> ```
> 
> Good lord, finally fixed it, make sure that `XDG_DATA_DIRS` is properly set

Oh fine! Maybe we will test it and provide that env with the AppImage.

**Comment by mirkobrombin** [comment] 2022-01-23 07:22
Closing until we find a new appimage maintainer. https://twitter.com/usebottles/status/1482656337918152708?s=21

**Closed by mirkobrombin** 2022-01-23 07:22 UTC
Labels: bug
