### ISSUE TITLE
[BUG] Overland silently crash

### ISSUE THREAD

**Issue by StephenRynas** [bottlesdevs/Bottles#1061] opened 2022-02-15 21:27 UTC
[francescomasala](https://forums.usebottles.com/u/francescomasala) requested that this be assigned to him.

**Describe the bug**
Loaded Bottles from the Mint repository as a flatpak. Bottles Bottle appeared to install correctly. I downloaded two Windows programs. One with an "exe" extension and one with an "msi" extension. Both files were placed in my Mint download directory. I then clicked on "run executable". Went to the download directory, selected my Windows ".msi" program. Then clicked on "run". Nothing happened. To be more precis, the computer locked-up and I had to reboot the computer.

I did run the debug option. Unfortunately, it would not let me copy the text. [The screenshot is posted here in the Mint forum](https://forums.linuxmint.com/download/file.php?id=76305&mode=view).

**Installation**
 - Method: flatpak from Mint repository
 - Version: 

**To Reproduce**
See the screenshots. Basically everything appears to work correctly until the "run" button is pressed to install the Windows program.The computer then locks-up and has to be rebooted.

**Expected behavior**
The Windows program should be installed following the "run" button being pushed.

**Screenshots**
![Screenshot01](https://user-images.githubusercontent.com/99763298/154151903-e8d33420-c948-4d52-83fb-cfd917fd25e2.png)
![Screenshot02](https://user-images.githubusercontent.com/99763298/154151999-972c5346-61d8-4a2b-8406-e4a9e844164b.png)
![Screenshot03](https://user-images.githubusercontent.com/99763298/154152002-16a02189-8bd9-4ac3-a03f-f526a66ed96f.png)
![Screenshot04](https://user-images.githubusercontent.com/99763298/154152003-743299e6-6559-4966-bdab-e3905836a0e1.png)
![Screenshot05](https://user-images.githubusercontent.com/99763298/154152004-ca046261-5e59-4dc8-aeed-6d196d67ab8f.png)
![Screenshot06](https://user-images.githubusercontent.com/99763298/154152009-4c5ab45b-0c04-4479-ac7c-9bfaec436aca.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20.3
 - Display server: Xorg
**Additional context**

**Comment by greatquux** [comment] 2022-02-15 22:00
Me too. How can we debug this?

**Comment by mirkobrombin** [comment] 2022-02-15 22:13
CIao thanks for reporting. Unfortunately with this information I don't know how to help you and I need more details because it seems "simply" a WINE problem rather than Bottles. Can you try to run the executable with the terminal (context menu Run executable) and see if it gives any useful information?

**Comment by greatquux** [comment] 2022-02-17 02:39
This is a tough one since it completely locks up the machine. Also couldn't run the EXE from the command prompt because it wasn't showing up in my directory listing due to flatpak sandboxing.  I uninstalled the flatpak version, cloned the git repo and installed it (had to install patool as well, that's not listed as a dependency), and cannot reproduce it, no crash or lockup.

**Comment by mirkobrombin** [comment] 2022-02-17 06:37
So maybe something broken with flatpak on mint

**Comment by greatquux** [comment] 2022-02-17 13:15
mine was on ubuntu 21.10. anyway i like the non-flatpaked version better as i can actually see the text when running adwaita-dark. let's all forget this containerized crap and go back to .debs! :) srsly though.

**Comment by StephenRynas** [comment] 2022-03-01 18:55
[thanhminhmr](https://github.com/thanhminhmr) posted a workaround in bug report #1051. The workaround apparently works, but has not been fully tested. Please see my additional comments in #1051

**Comment by mirkobrombin** [comment] 2022-03-01 21:42
Closing for #1051. I'll keep tracking this there.

**Closed by mirkobrombin** 2022-03-01 21:43 UTC
Labels: bug
