### ISSUE TITLE
[Bug]: [Flatpak] C: drive space is reported much smaller than available

### ISSUE THREAD

**Issue by mmcnutt** [bottlesdevs/Bottles#1295] opened 2022-04-11 04:59 UTC
### Describe the bug

Creating a default application prefix in flatpak version of bottles only makes 2GB of space available to the bottle. Installing an application in the bottle (eg Office) fails as the disk space check is reported as being too low to continue 

### To Reproduce

create default app bottle
attempt install
not enough space

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Kinoite

### Health Check

Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.2-300.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment] 2022-04-11 08:59
EA Client has this bug too. I think it's somehow related/caused by Flatpak.

**Comment by timocapa** [comment] 2022-05-01 01:21
I also have this on normal Origin and Uplay. I've the AUR package but I think this still uses Flatpak internally?

**Comment by tmespe** [comment] 2022-05-02 09:03
I had the same issue with EA Desktop, but adding the folder as a drive through the bottles interface  instead of browsing through Z: solved it for me.

**Comment by mirkobrombin** [comment] 2022-05-10 13:53
We are investigating this, it seems related to Flatpak. The size of the disk when using Flatpak is reported smaller than host.

**Comment by udekmp** [comment] 2022-06-21 07:24
> I had the same issue with EA Desktop, but adding the folder as a drive through the bottles interface instead of browsing through Z: solved it for me.

Thank you!  

Following your method by going into Legacy Tools > Wine Configuration > Drives > Add > **Letter** > Browse > _PATH_ > Applying seems to have fixed it for the EA application.

**Comment by mirkobrombin** [comment] 2022-06-22 12:52
The only way to workaround is adding a new drive pointing to an external path in the bottle preferences and install ea there

**Comment by alvarlagerlof** [comment] 2022-06-22 12:55
That is suboptimal. Maybe we should make an issue in Flatpak?

**Comment by mirkobrombin** [comment] 2022-06-22 13:09
we can try

**Comment by mirkobrombin** [comment] 2022-07-07 13:07
Closing as not a Bottles bug

**Closed by mirkobrombin** 2022-07-07 13:07 UTC
Labels: Need To Investigate

**Comment by SuperSamus** [comment] 2023-01-12 16:37
I suffer from the same bug despite not using Flatpak.
Tested on both GOG and EA App, on Wine Soda 7.18.

```
Official Package: false
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /run/opengl-driver/share/vulkan/icd.d/amd_icd64.json:/run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json:/run/opengl-driver-32/share/vulkan/icd.d/amd_icd32.json:/run/opengl-driver-32/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.3-zen1
Distro:
    Name: NixOS
    Version: '23.05'
Disk:
    Total: 8016154624
    Free: 8016105472
RAM:
    MemTotal: 14.9GiB
    MemAvailable: 10.0GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

**Comment by farline99** [comment] 2023-03-02 14:16
Fedora 37 KDE. Same here 2GB C drive, when 100 gb available... Flatpak Bottles

**Comment by Zukureneno** [comment] 2023-03-08 12:41
> > I had the same issue with EA Desktop, but adding the folder as a drive through the bottles interface instead of browsing through Z: solved it for me.
> 
> Thank you!
> 
> Following your method by going into Legacy Tools > Wine Configuration > Drives > Add > **Letter** > Browse > _PATH_ > Applying seems to have fixed it for the EA application.

Yo tnx for writing down the method; that fixed my issue with Ubisoft Connect.

I wonder if this can be applied on a global scale for all future Bottles and old ones.

**Comment by farline99** [comment] 2023-03-08 12:44
The problem for me was solved by moving the game installer to the folder with the bottle (drive_c). After that, the installer saw the whole place and there were no problems.
