### ISSUE TITLE
[Bug]: When running an app with Gamescope in Bottles, the app window is missing.

### ISSUE THREAD

**Issue by jkrhu** [bottlesdevs/Bottles#2030] opened 2022-09-05 21:03 UTC
### Describe the bug

When running an app with Gamescope in Bottles, the app window is missing. I can hear audio and the app, as well as gamescope processes are present. I'm using the Flatpak Bottles as well as Flatpak Steam with Gamescope addon. This doesn't happen in Flatpak Steam.

### To Reproduce

1. Turn on Gamescope in the bottle setting 
2. Launch the game/app.
3. Game launches with no visible window.

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.6-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8341999616
    Free: 8341831680
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.9GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

CPU: Intel i5-10400
GPU: NVIDIA GeForce RTX 3060
Driver: 515.65.01
RAM: 16 GB

**Comment by mirkobrombin** [comment] 2022-09-05 21:09
duplicate of #1562

**Closed by mirkobrombin** 2022-09-05 21:09 UTC
