### ISSUE TITLE
[Bug]: Can't run exe files from the file manager

### ISSUE THREAD

**Issue by Hairo** [bottlesdevs/Bottles#1606] opened 2022-06-12 04:16 UTC
### Describe the bug

Seems running exe files from the file manager doesn't work again.

When running bottles in a terminal with `bottles file.exe` i get:
```
Invalid URI (syntax: bottles:run/<bottle>/<program>)
```

### To Reproduce

- Double click exe in file manager
- Nothing happens

### Package

AUR ("bottles" package)

### Distribution

EndeavourOS

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.3-zen1-1-zen
Distro:
    Name: EndeavourOS
    Version: Unknown
Disk:
    Total: 860759031808
    Free: 229982711808
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 27.8GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-06-12 05:42
duplicate of #1591

**Closed by mirkobrombin** 2022-06-12 05:42 UTC
