### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by victorffrock** [bottlesdevs/Bottles#482] opened 2021-08-22 06:29 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.8.14-treviso

**Log**
```python3
[Errno 2] Arquivo ou diretório inexistente: '/var/home/victorffrock/.var/app/com.usebottles.bottles/data/bottles/bottles/Epic/bottle.yml'  File "/app/share/bottles/bottles/utils.py", line 236, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/runner.py", line 1167, in async_create_bottle
    with open(f"{bottle_complete_path}/bottle.yml", "w") as conf_file:

```

**Comment by mirkobrombin** [comment] 2021-08-22 06:38
Duplicate of #479

**Closed by mirkobrombin** 2021-08-22 06:38 UTC
