### ISSUE TITLE
[Bug]: Dependency uninstall does not appear to remove dependency

### ISSUE THREAD

**Issue by roxya** [bottlesdevs/Bottles#2191] opened 2022-10-22 19:32 UTC
### Describe the bug

When I try to uninstall a dependency from a bottle, it shows a confusing message saying the dependency has been installed. The download icon reappears next to the dependency, leading me to believe it was successfully removed. However, dependencies which can appear in wine uninstaller are still there, and the programs continue to run perfectly even when all required dependencies were supposed to be uninstalled.

### To Reproduce

1. Go to dependencies page
2. Install a dependency which can appear in wine uninstaller e.g. vcredist2010
3. Uninstall the dependency
4. Observe that the dependency still appears in wine uninstaller
5. Observe that a program which requires that dependency is still able to run

### Package

Flatpak from Flathub

### Distribution

Steam deck OS

### Troubleshooting Logs

```shell
Version: 2022.1.014.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.3-1-neptune
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 7778668544
    Free: 7778541568
RAM:
    MemTotal: "15.6\_GB"
    MemAvailable: "12.8\_GB"
Bottles_evns: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

I'm trying to find the exact dependencies for some applications and not being able to remove any makes testing a nightmare!

**Comment by mirkobrombin** [comment] 2022-10-22 20:05
Duplicate of #2079

**Closed by mirkobrombin** 2022-10-22 20:05 UTC
