### ISSUE TITLE
[BUG] caffe-6.23 on AppImage don't create bottle files

### ISSUE THREAD

**Issue by psydvl** [bottlesdevs/Bottles#922] opened 2022-01-13 19:14 UTC
**Describe the bug**
Creation bottle in 2022.1.14 fall with exception while creating new bottle
Because caffe-6.23 creates nothing in bottle directory

**Installation**
 - Method: [nix](https://github.com/NixOS/nixpkgs/blob/b9aa18f4640df7523bf2c2fa4d07af63a7f263a7/pkgs/applications/misc/bottles/default.nix) with only updated version or AppImage
 - Version: 2012.12.28 & 2022.1.14 & 2022.1.14-2

**To Reproduce**
1. Delete `~/.local/share/bottles` if exists
2. Launch AppImage `bottles`
3. Create new bottle with name `test` for example
	```
	(21:55:24) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7f3a753d7310>>
	Exception: [Errno 2] No such file or directory: '/home/nixi/.local/share/bottles/bottles/test/drive_c/windows//syswow64/d3d9.dll' 
	  File "/nix/store/y49yvm1w2s1mzag38mk6r8y5073clxhi-bottles-2022.1.14/share/bottles/bottles/utils.py", line 339, in __target
	    result = self.task_func(*args, **kwargs)
	  File "/nix/store/y49yvm1w2s1mzag38mk6r8y5073clxhi-bottles-2022.1.14/share/bottles/bottles/backend/manager.py", line 1200, in create_bottle
	    self.install_dll_component(config, "dxvk", version=dxvk_name)
	  File "/nix/store/y49yvm1w2s1mzag38mk6r8y5073clxhi-bottles-2022.1.14/share/bottles/bottles/backend/manager.py", line 1394, in install_dll_component
	    manager.install(config, exclude)
	  File "/nix/store/y49yvm1w2s1mzag38mk6r8y5073clxhi-bottles-2022.1.14/share/bottles/bottles/backend/dll.py", line 35, in install
	    self.__install_dll(config, path, dll)
	  File "/nix/store/y49yvm1w2s1mzag38mk6r8y5073clxhi-bottles-2022.1.14/share/bottles/bottles/backend/dll.py", line 66, in __install_dll
	    shutil.copyfile(source, target)
	  File "/nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/lib/python3.9/shutil.py", line 266, in copyfile
	    with open(dst, 'wb') as fdst:
	```
5. List files in ~/.local/share/bottles/bottles/test
	``` console
	$ ls ~/.local/share/bottles/bottles/test
	bottle.yml
	```

**Expected behavior**
Successful creation

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/43755002/149391884-f2e6dd44-75a6-446c-8ccf-88eea036a126.png)

</details>

**launch log files to 2022.1.14 and 2021.12.28**
https://gist.github.com/4aaa5c8e1a5f1b68d4f1b44d08834523

NB: they are creating using `bottles 2&>1 | tee file.log` so they are probably uncomfortble to see
You can curl them to better preview
``` console
curl https://gist.githubusercontent.com/psydvl/4aaa5c8e1a5f1b68d4f1b44d08834523/raw/6880effea83ff2b525eca3e81d0ba0934d6414b0/2021.12.28.log
printf "%$(tput cols)s" | tr " " "X" # to separate
curl https://gist.githubusercontent.com/psydvl/4aaa5c8e1a5f1b68d4f1b44d08834523/raw/6880effea83ff2b525eca3e81d0ba0934d6414b0/2022.1.14.log
```

**Desktop (please complete the following information):**
 - OS: NixOS
 - Version 21.11
 - Display server: Wayland

**Additional context**`
While there are errors on 2021.12.28 too, they are not affect creation steps.

**Comment by mirkobrombin** [comment] 2022-01-13 19:30
We are updating the dependencies repository, if you face problems, please try again later.
Read the notice here: https://github.com/bottlesdevs/Bottles/releases/tag/2022.1.14-trento

**Comment by f0o** [comment] 2022-01-13 20:48
@mirkobrombin any guesstimate when it's ready? Flatpak seems to still serve 2020.10.x eventho it claims to be on 2021.1.14 on the webview. Likely related I suppose.

**Comment by psydvl** [comment] 2022-01-15 14:41
Since the problem still exist and also affected AppImage (https://github.com/bottlesdevs/Bottles/issues/928), I've tried to investigate it
I'm not sure that I truly catch this bug, but it seems a problem is in caffe-6.23 

caffe-6.23 creates bottle directory with only bottle.yml file

``` console
$ ls ~/.local/share/bottles/bottles/test
bottle.yml
```

**Comment by psydvl** [comment] 2022-01-15 14:50
@mirkobrombin can you reopen it back?

**Comment by mirkobrombin** [comment] 2022-01-15 15:02
I'm not able to reproduce this even on flatpak or appimage. Please make some checks:
- post here the Health check (from the main menu)
- there are files in the bottles' temp directory?
- .. also in runners/dxvk/vkd3d directories?

**Comment by psydvl** [comment] 2022-01-15 15:08
NB: With vaniglia-6.23 everything creates successfully

<details>
<summary>Health check</summary>

```
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: ''
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.3-zen1
Distro:
    Name: NixOS
    Version: nixos
Tools:
    cabextract: true
    p7zip: true
    patool: true
Bottles_envs: null
```

</details>

```
$ ls ~/.local/share/bottles/temp/
caffe-6.23-x86_64.tar.xz  dxvk-1.9.3.tar.gz  dxvk-nvapi-v0.5.1.tar.gz  vkd3d-proton-2.5.tar.gz
$ ls ~/.local/share/bottles/runners/
caffe-6.23
$ ls ~/.local/share/bottles/dxvk/
dxvk-1.9.3
$ ls ~/.local/share/bottles/vkd3d/
vkd3d-proton-2.5
$ ls ~/.local/share/bottles/layers/
$ ls ~/.local/share/bottles/nvapi/
dxvk-nvapi-v0.5.1
```

**Comment by psydvl** [comment] 2022-01-15 15:30
I've found the temporary solution
But why it only affected caffe, nor vaniglia?
LD_PRELOAD=$PATH_TO_libunwind.so.8

**Comment by mirkobrombin** [comment] 2022-01-15 16:38
Nice found, idk why :D

**Comment by arthurlutz** [comment] 2022-01-18 09:55
Getting the same problem with Ubuntu and the AppImage, the `LD_PRELOAD` fix doesn't seem to work (or I'm using it wrong) 

Healthcheck : 

```
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.11.0-41-generic
Distro:
    Name: ubuntu
    Version: ubuntu 20.04.3 lts
Tools:
    cabextract: true
    p7zip: true
    patool: true
Bottles_envs: null
```

**Comment by mirkobrombin** [comment] 2022-01-18 11:47
### We are looking for a maintainer for the AppImage as we have no more effort to invest on it.

Regarding your problem, how are you using the env var?

**Comment by arthurlutz** [comment] 2022-01-18 13:16
Tried with `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libunwind.so.8 ./Bottles-2022.1.14-trento-x86_64.AppImage`

Trying with flatpak since you're saying this is the more supported route.

**Comment by psydvl** [comment] 2022-01-18 13:37
For Ubuntu, it seems required glibc 2.32, having only 2.31 installed
https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system

**Comment by mirkobrombin** [comment] 2022-01-23 07:21
Closing until we find a new appimage maintainer. https://twitter.com/usebottles/status/1482656337918152708?s=21

**Closed by mirkobrombin** 2022-01-23 07:21 UTC
Labels: bug

**Comment by hthre7** [comment] 2022-01-31 09:32
> libc 2.32

the appimage have already shipped with its own libc
