### ISSUE TITLE
[Bug]:when adding game to programs,it gets overwritten.

### ISSUE THREAD

**Issue by Noobao** [bottlesdevs/Bottles#1337] opened 2022-04-18 04:47 UTC
### Describe the bug

I play some rpg maker games,the files generally have the name Game.exe

There are some small issues when adding more than 1 game to programs,once i add it,the current game who has the name Game.exe ,gets overwritten by the new Game.exe that i add (most specifically,the name stays the same,however the path is changed to the new game.exe),renaming these in-app does not help.

This should not occur as they are different games and have different file paths.

Expected behaviour: The new game.exe should be added to programs,and it should not overwrite the old game.exe

### To Reproduce

1- Open bottles.
2-Click on the plus sign to add a game
3-add executables with the same name and different paths.

### Package

AUR ("bottles" package)

### Distribution

Artix Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.2-xanmod1-1
Distro:
    Name: Artix Linux
    Version: '20220409'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-04-18 05:44
Duplicate of #1335

**Closed by mirkobrombin** 2022-04-18 05:44 UTC
