### ISSUE TITLE
[Bug]: 'str' object has no attribute 'Parameters' 

### ISSUE THREAD

**Issue by amitlevy21** [bottlesdevs/Bottles#2959] opened 2023-07-11 14:49 UTC
### Describe the bug

I opened bottles without doing anything
got this error:

'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk

### To Reproduce

open bottles normally.

### Package

Flatpak from Flathub

### Distribution

Nobara 38 (Fedora 38)

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.3.12-203.fsync.fc38.x86_64
Disk:
    Total: 16778362880
    Free: 16778207232
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.2GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment] 2023-08-01 22:10
duplicate of #2885

**Closed by mirkobrombin** 2023-08-01 22:10 UTC
