### ISSUE TITLE
[Request]: Total Play Time in Library Mode?

### ISSUE THREAD

**Issue by bayazidbh** [bottlesdevs/Bottles#1887] opened 2022-08-02 02:43 UTC
### Tell us the problem or your need

Hi, I usually use Lutris for keeping track of my playtime, especially as I like to report in sites like How Long to Beat and VNDB. It would be nice to have a way to track playtime, and maybe other personal statistics, in Library Mode.

### Describe the solution you'd like

A simple "Total Playtime" would suffice. Heroic has a nice tracking in it, with total play time and last played. Some sort of "total playtime last session/week/month" expanded statistics would be cool as well, but just a simple "total playtime" would suffice.

I think it could eventually be expanded into a Digital Wellbeing-like thing, though maybe more about just tracking your general usage inside the app.

### Other solutions?

I could do manual tracking, yes, but it's nicer to have the Library tracking it and presenting nice statistics for me.

**Comment by mirkobrombin** [comment] 2022-08-02 05:46
Duplicate of #1273

**Closed by mirkobrombin** 2022-08-02 05:46 UTC
Labels: Feature request
