### ISSUE TITLE
[Crash report]  Manager.checks() got an unexpe

### ISSUE THREAD

**Issue by walthaas** [bottlesdevs/Bottles#855] opened 2021-12-23 21:23 UTC
Fedora 35.  Installed from rpm here:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1866924

This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.12.14-treviso

**Log**
```python3
Manager.checks() got an unexpected keyword argument 'after'  File "/usr/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

```

**Comment by mirkobrombin** [comment] 2021-12-23 21:27
Duplicate of #784

**Closed by mirkobrombin** 2021-12-23 21:27 UTC
