### ISSUE TITLE
[Bug]: bottles crash report

### ISSUE THREAD

**Issue by Reyganoko** [bottlesdevs/Bottles#2677] opened 2023-02-12 20:21 UTC
### Describe the bug

*Description missing*

### To Reproduce

*Description missing*

### Package

Flatpak from Flathub

### Distribution

manjaro 22.0

### Debugging Information

*Debugging information missing*

### Troubleshooting Logs

```py
[Errno 2] No existe el fichero o el directorio: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/whatsapp/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 194, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
    times.update(self.checks(install_latest=False, first_run=True).data)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 189, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 804, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 744, in process_bottle
    self.update_config(

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 874, in update_config
    with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file:
```

**Comment by TheEvilSkeleton** [comment] 2023-02-12 22:09
Hi, can you please provide context? How did you run into this issue, what are the steps you took to get to that error?

**Comment by StoneMoe** [comment] 2023-02-13 10:47
is this duplicated with https://github.com/bottlesdevs/Bottles/issues/2456?
if so, then it's a known issue and will be fixed in next release! meanwhile you can fix it with the workaround described in the issue.

**Comment by TheEvilSkeleton** [comment] 2023-02-19 22:29
I'm just going to assume that it is, as no context was provided.

Duplicate of #2456

**Closed by TheEvilSkeleton** 2023-02-19 22:29 UTC

**Comment by TheEvilSkeleton** [comment] 2023-02-19 22:31
...Why did it not mark it as duplicate?

**Comment by TheEvilSkeleton** [comment] 2023-02-19 22:31
Duplicate of #2456
