### ISSUE TITLE
[Crash report] Cabextract not found - Flatpak beta of Bottles

### ISSUE THREAD

**Issue by irihuman** [bottlesdevs/Bottles#388] opened 2021-07-21 10:23 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak

**Log**
```python3
cabextract utility not found, please install to use dependencies which need this feature
```

Installed cabextract deb package and allowed Bottles to use system libraries just in case that may help, same issue unfortunately.

**Comment by mirkobrombin** [comment] 2021-07-21 10:27
Flatpak cannot use that command from the system but it should still work with the one already present in the Flatpak.

Is this flatpak from stable or beta repository?

**Comment by irihuman** [comment] 2021-07-21 13:55
Have tried both Beta and Stable, both do same thing unfortunately. I will try removing cabextract from my system and trying again.

**Comment by mirkobrombin** [comment] 2021-07-21 14:32
This is really weird, I'll try in a clean VM

**Comment by mirkobrombin** [comment] 2021-07-24 09:39
Unfortunately I was unable to reproduce the bug. In each of my tests Flatpak finds cabextract in its AppDir. For now I close the issue waiting for someone with the same problem.

**Closed by mirkobrombin** 2021-07-24 09:39 UTC
