### ISSUE TITLE
[Feature request]: Missing some old windows versions

### ISSUE THREAD

**Issue by TiBeN** [bottlesdevs/Bottles#1421] opened 2022-05-05 10:05 UTC
### Describe the bug

Using a 32bit arch bottles, the list in Preferences > Windows version starts from Windows XP but Wine 32bits supports 
a lot more older windows versions (Win 95, Win 98 etc.) which are required to run some older games.

Supported versions are listed in the Wine config tool:

![Screenshot from 2022-05-05 12-00-51](https://user-images.githubusercontent.com/910115/166901972-c43cca65-9ee3-4c7b-ae44-4c7e9fce4440.png)

Its is not a critical issue because it can be set directly on using internal wine config tool but solving it would add more UI consistency.

### To Reproduce

1. Go to Preferences > Windows version using a 32bit bottle

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-05-05 12:48
Not a bug, those are just not implemented. I've marked it as a Feature request, thanks for reporting.

**Closed** 2022-05-07 20:22 UTC
Labels: Task, Feature request

**Comment by DJCrashdummy** [comment] 2024-08-26 09:58
i'm not sure if this should be reopened instead of #1526, <del>but in Bottles 51.13 Windows XP is still the oldest version which can be selected (within Bottles), no Win2000, 98, 95 or the like.</del>

as the OP said, it not a big deal as it can be set via wine config, **but** what's really unfortunate is, that the used **setting shown within Bottles** stays at the one which was set within Bottles. that's really **misleading and confusing!**
as a workaround until the older versions are displayed correctly (and may even be selectable) within Bottles, i would suggest to at least display something like "custom" instead of wrong values.
