### ISSUE TITLE
[Bug]: flatpak lib32 missing even though flatpak says it's installed

### ISSUE THREAD

**Issue by kaosine** [bottlesdevs/Bottles#1477] opened 2022-05-17 16:11 UTC
### Describe the bug

Unable to get it to function beyond launching. It complains when using verbose output in terminal that both lib32 and pulse are missing despite both being installed according to flatpak on system, user, and beta channels. It just gets stuck at "still loading" to even get it functional. Can't even use the rpm instead because it seems to be a empty package for some reason that only creates a process and that's it.

### To Reproduce

Launch as normal from flatpak and it'll just hang at the still loading. The only interaction I'm able to do is hover over the add button and it give me the tooltip for that. Otherwise I get nothing.

### Package

Flatpak from Flathub

### Distribution

Fedora 36/nobara

### Health Check

```shell
Can't even use this button either to get the health check. It does nothing when clicked.
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

### Additional context

If I could get the buttons in the app to respond, I'd add more. So far tho I only get this in the terminal:

`F: /home/kaosine/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/42/d240597586ac4c87e7e8dd634b67a3c910704b77d1ef5927147e55fe57cf569a/files/lib32 does not exist
F: Pulseaudio user configuration file '/home/kaosine/.config/pulse/client.conf': Error opening file /home/kaosine/.config/pulse/client.conf: No such file or directory
`
Despite both being installed as far as I'm aware since flatpak skips it when I force it. I've even uninstalled the lib32 and reinstalled it in flatpak and get no changes.

**Comment by mirkobrombin** [comment] 2022-05-17 17:57
Not able to replicate, sounds like a flatpak related problem.

**Comment by mirkobrombin** [comment] 2022-07-07 12:52
Should not be related. Closing as it's not a bug in our side. Feel free to add more comments.

**Closed by mirkobrombin** 2022-07-07 12:52 UTC
Labels: Can't replicate
