### ISSUE TITLE
[Crash report]  run() got multiple values fo

### ISSUE THREAD

**Issue by CosCal** [bottlesdevs/Bottles#1002] opened 2022-01-31 20:46 UTC
I've been trying to re-launch a working GOG game that uses DOSBox with .conf files. The game runs fine on first install if launched from the installer, but the listing will not launch again correctly through Bottles' Programs menu. Any guidance or ideas are welcome.

This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.1.28-trento-1

**Log**
```python3
run() got multiple values for argument 'file'  File "/app/share/bottles/bottles/utils.py", line 337, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 101, in run
    return self.__launch_lnk()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 180, in __launch_lnk
    res = start.run(

```

**Comment by mirkobrombin** [comment] 2022-01-31 21:27
Duplicate of #986

I’ll do a fix tomorrow, thanks for reporting.

**Closed by mirkobrombin** 2022-01-31 21:27 UTC
