### ISSUE TITLE
Possible problem with latest DXVK and VKD3D

### ISSUE THREAD

**Issue by Froggy232** [bottlesdevs/Bottles#2382] opened 2022-12-16 22:40 UTC
Hi,
With the latest dxvk and vkd3d update in place of having a new entry called DXVK-XYZ there is a x32 and x64 entry, same for vkd3d.
Also, in ~/.var/app/com.usebottles.bottle/data/bottles/dxvk, in place of a new folder called dxvk-xyz, there is a x32 and x64 folder.
I think it lack a subfolder, the x32 and x64 folder should be in a directory called dxvk-xyz or vkd3d-xyz.
Thanks you!

**Comment by TheEvilSkeleton** [comment] 2022-12-17 02:17
Thanks for reporting. I can reproduce it on the latest version of Bottles from Flathub.

That being said, please use the provided issue form from GitHub next time.

**Comment by Froggy232** [comment] 2022-12-17 11:04
Sorry, I didn't notice there was one, I will use it next time.

**Comment by koplo199** [comment] 2022-12-17 19:28
It seems that the problem lies in the folder structure of experimental archive files, example with [dxvk-2.0-1-18b0ef6](https://github.com/bottlesdevs/components/releases/tag/dxvk-2.0-1-18b0ef6):

```
.
└── .
    ├── x32
    │   ├── d3d10core.dll
    │   ├── d3d11.dll
    │   ├── d3d9.dll
    │   └── dxgi.dll
    └── x64
        ├── d3d10core.dll
        ├── d3d11.dll
        ├── d3d9.dll
        └── dxgi.dll
```

`.` should probably replaced by `dxvk-2.0-1-18b0ef6`, but I really don't understand why it would be necessary as [dxvk-nvapi](https://github.com/jp7677/dxvk-nvapi/releases) is using the same `.` folder structure but is working perfectly fine:
```
.
└── .
    ├── LICENSE
    ├── README.md
    ├── x32
    │   └── nvapi.dll
    └── x64
        ├── nvapi64.dll
        └── nvapi64-tests.exe
```
@mirkobrombin Any idea why it is working for dxvk-nvapi and not for other components?

**Comment by koplo199** [comment] 2022-12-18 16:50
Ok found it, seems like `dxvk-nvapi` is receiving a special treatment in the backend:
https://github.com/bottlesdevs/Bottles/blob/4bb9cb53a4f3c5d1224561007d7b7e8d91380520/bottles/backend/managers/component.py#L296-L300

Imho hacks/quirks shouldn't be on the backend side, they should be on the components side : @mirkobrombin would it be an acceptable solution for you to drop the dxvk-nvapi case on the backend, and use a `rename` action on the yml file instead? It would be more consistent, as this would match the behavior of [wine-ge](https://github.com/koplo199/components/blob/main/runners/wine/wine-ge-proton7-33.yml) for instance. If so, I could submit a PR fixing the issue rather quickly

**Comment by mirkobrombin** [comment] 2022-12-18 19:09
It was a workaround to avoid hosting the builds. Btw now that we handle them all, I think we can remove it and just build it the right way

**Comment by koplo199** [comment] 2022-12-18 19:54
Ok, let's do this

**Comment by TheEvilSkeleton** [comment] 2023-01-09 05:34
I'm reopening this issue as I can reproduce as of https://github.com/bottlesdevs/Bottles/commit/485740d2dcb55b1611a63eea67ebfba5eb51ef82.

![Screenshot from 2023-01-09 00-31-51](https://user-images.githubusercontent.com/50847364/211246250-35b4d7a3-1008-4ca8-9483-c34b4daa9fa7.png)

**Comment by TheEvilSkeleton** [comment] 2023-01-09 05:37
https://github.com/bottlesdevs/Bottles/commit/39f1a3baf60ea332f377aa15732cbc5b5d4c296c seems to have it fixed, but a later version reintroduced to this regression.

**Comment by koplo199** [comment] 2023-01-09 13:03
Mhh https://github.com/bottlesdevs/Bottles/commit/39f1a3baf60ea332f377aa15732cbc5b5d4c296c never intended to fix the DXVK/VKD3D issue, it was a commit to preemptively fix NVAPI so wo don't end up with a `dxvk-nvapi-0.x/dxvk-nvapi-0.x/{x32,x64,...}` folder layout instead of the correct `dxvk-nvapi-0.x/{x32,x64,...}`

The DXVK/VKD3D issue was only affecting experimental builds, and was fixed on the components side by https://github.com/bottlesdevs/components/commit/40c6c7b1e8938b77d789413db2cbdbd9d0b30b67. To this day DXVK/VKD3D experimental builds sill have the correct folder layout, so I don't know, maybe you have some old archives downloaded? (They aren't even available for download now, and haven't been for a long time, maybe an issue with caching?). To verify: is it also happening with a component release using an official repository like dxvk-2.0 for instance? If so, this isn't the same kind of bug, as non-experimental builds would now be affected too

**Comment by TheEvilSkeleton** [comment] 2023-01-09 13:48
> To verify: is it also happening with a component release using its official repository like dxvk-2.0? If so, this isn't the same kind of bug, as non-experimental builds would now be affected too

Yes, it is. I created a new bottle and what I see is this:

![image](https://user-images.githubusercontent.com/50847364/211322610-ff04f2ac-ee01-40df-8b4d-98dbd2e7b85c.png)

(DXVK is x64 and VKD3D is x86)

 Should I open a new issue and close this one?

**Comment by TheEvilSkeleton** [comment] 2023-01-09 13:54
Okay... I removed the Bottles folder to start from scratch, and it seems to have fixed my issue? I'll close this issue.

**Closed by TheEvilSkeleton** 2023-01-09 13:54 UTC
Labels: Bug
