### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fifqaaa** [bottlesdevs/Bottles#2898] opened 2023-05-11 21:43 UTC
### Describe the bug

I have an application that requires dotnet35 to run and I try to install it from dependencies tab, but before the actual installer window, after repack to temp folder, I got an error with message „Windows Installer package cannot be opened: [c:\(temp_folder_that_contains_installer_files](https://github.com/c:/(temp_folder_that_contains_installer_files))\vs_setup.ms_ could not be opened” I tried override it, I’ve changed version to the previous one (51.5). There is no change. 

### To Reproduce

    1. Create Bottle
    2. Install dotnet35 from dependencies
    3. See error

### Package

Flatpak from Flathub

### Distribution

EndeavourOS Linux 

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.3.1-arch2-1
Disk:
    Total: 8363581440
    Free: 8363425792
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 9.1GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
23:31:17 (INFO) Bottles Started! 
23:31:18 (INFO) Performing Bottles checks… 
23:31:18 (INFO) Dxvks found:
         - dxvk-2.1-1-977669c
         - dxvk-async-1.10.2
 
23:31:18 (INFO) Vkd3ds found:
         - vkd3d-proton-2.8-1-b7fb41b
 
23:31:18 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.2-1-742b17c
 
23:31:18 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
23:31:18 (INFO) Runners found:
         - soda-7.0-9
         - soda-7.0-2
         - caffe-7.20
         - lutris-7.2-2
         - wine-ge-proton8-4
         - wine-ge-proton7-41
         - GE-Proton7-53
         - sys-wine-8.0
 
23:31:18 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
23:31:18 (INFO) Bottles found:
         - Wiesiek
         - Epic
         - Mathccad
         - MTA TEST
         - GTA IV
         - nowabutlatest
         - Factorio
         - Mount and Blade 2
         - Sifu
         - Mathcad Gaming
         - AMID EVIL
 
23:31:19 (INFO) Catalog components loaded 
23:31:19 (INFO) Catalog installers loaded 
23:31:19 (INFO) Catalog dependencies loaded 
23:38:07 (INFO) Removing dotnet35 dependency from nowabutlatest 
23:38:07 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32', 'courie32', 'mono', 'gecko'] for bottle nowabutlatest… 
23:38:15 (INFO) Installing dependency [dotnet35] in bottle [nowabutlatest]. 
23:38:16 (INFO) Using Wine Uninstaller -- get_uuid 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:18 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] from Key: [SubVersionNumber] in nowabutlatest registry 
23:38:19 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:21 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:38:21 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] from Key: [VersionNumber] in nowabutlatest registry 
23:38:22 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:23 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:38:23 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] from Key: [CSDVersion] in nowabutlatest registry 
23:38:24 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:26 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:38:26 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] from Key: [CurrentBuildNumber] in nowabutlatest registry 
23:38:27 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:28 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:38:28 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] from Key: [CurrentVersion] in nowabutlatest registry 
23:38:29 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:30 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:38:30 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] from Key: [ProductType] in nowabutlatest registry 
23:38:31 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:33 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:38:33 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ServiceCurrent] from Key: [OS] in nowabutlatest registry 
23:38:34 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:35 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:38:35 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] from Key: [CSDVersion] in nowabutlatest registry 
23:38:36 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:38 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:38:38 (INFO) Removing Value: [HKEY_CURRENT_USER\Software\Wine] from Key: [Version] in nowabutlatest registry 
23:38:39 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:40 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:38:40 (INFO) Importing bundle to nowabutlatest registry 
23:38:41 (INFO) Using Wine Registry CLI -- import_bundle 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:38:42 (INFO) Using Wine Runtime tool -- send_status(-r) 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
23:38:44 (INFO) Using Wine Runtime tool -- send_status(-u) 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wineserver: file_set_error() can't map error: Function not implemented
wine: configuration in L"/run/user/1000/doc/302ff05d/Butelki/nowabutlatest" has been updated.
23:39:11 (INFO) Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscoree] and Data: [native,builtin] in nowabutlatest registry 
23:39:12 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:14 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:39:14 (INFO) Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscorwks] and Data: [native,builtin] in nowabutlatest registry 
23:39:15 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:16 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:39:16 (WARNING) File [dotnet35.exe] already exists in temp, skipping. 
23:39:16 (INFO) Launching an executable… 
23:39:17 (INFO) Using EasyAntiCheat runtime 
23:39:17 (INFO) Using BattlEye runtime 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
wineserver: file_set_error() can't map error: Function not implemented
wineserver: file_set_error() can't map error: Function not implemented
wineserver: file_set_error() can't map error: Function not implemented
23:39:46 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] from Key: [SubVersionNumber] in nowabutlatest registry 
23:39:46 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:48 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:39:48 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion] from Key: [VersionNumber] in nowabutlatest registry 
23:39:49 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:51 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:39:51 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] from Key: [CSDVersion] in nowabutlatest registry 
23:39:52 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:53 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:39:53 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] from Key: [CurrentBuildNumber] in nowabutlatest registry 
23:39:54 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:56 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:39:56 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion] from Key: [CurrentVersion] in nowabutlatest registry 
23:39:57 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:39:58 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:39:58 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ProductOptions] from Key: [ProductType] in nowabutlatest registry 
23:39:59 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:40:01 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:40:01 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\ServiceCurrent] from Key: [OS] in nowabutlatest registry 
23:40:02 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:40:03 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:40:03 (INFO) Removing Value: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows] from Key: [CSDVersion] in nowabutlatest registry 
23:40:04 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:40:06 (INFO) reg: Pomy˜lnie zakoäczono dziaˆanie

 
23:40:06 (INFO) Removing Value: [HKEY_CURRENT_USER\Software\Wine] from Key: [Version] in nowabutlatest registry 
23:40:07 (INFO) Using Wine Registry CLI -- remove 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:40:08 (INFO) reg: Nie mo¾na znale«† danej warto˜ci rejestru

 
23:40:08 (INFO) Importing bundle to nowabutlatest registry 
23:40:09 (INFO) Using Wine Registry CLI -- import_bundle 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
23:40:11 (INFO) Using Wine Runtime tool -- send_status(-r) 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
23:40:13 (INFO) Using Wine Runtime tool -- send_status(-u) 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wineserver: file_set_error() can't map error: Function not implemented
wine: configuration in L"/run/user/1000/doc/302ff05d/Butelki/nowabutlatest" has been updated.
23:40:41 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32', 'courie32', 'mono', 'gecko', 'dotnet35'] for bottle nowabutlatest… 
23:40:41 (INFO) Dependency installed: dotnet35 in nowabutlatest
```

### Additional context

Debugging screen error 

![image](https://github.com/bottlesdevs/Bottles/assets/49234782/74cb6ba9-847f-49d9-bec6-917e4e5c6eae)

**Comment by mirkobrombin** [comment] 2023-08-01 22:19
Closing all issues with no proper title.

**Closed by mirkobrombin** 2023-08-01 22:19 UTC

**Comment by galkinvv** [comment] 2023-12-25 01:49
Got a similar problem with .Net installation (and other installations too) - and eventually found the reason.
The most interesting error message here is
```
wineserver: file_set_error() can't map error: Function not implemented
```
apperaring while running the installer. **The problem appears only while using non-default Bottles directory**.

It is caused by the fact that non-default Bottles directory opened via flatpak dialog points to a directory like `/run/user/1000/doc/1077965e/bottles-storage -> /run/flatpak/doc/1077965e/bottles-storage` that is mounted like
```
portal /run/flatpak/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
```

I suggest mantainers to rename this issue to ".Net framework can't be installed if the botlles directory is mounted via `fuse.portal` filesystem.

The root of problem is that `fuse.portal` filesystem is not fully-functional (does not implement file locking) from some version and at least before this fix is landed last month: https://github.com/flatpak/xdg-desktop-portal/commit/954cdc6aebe494dbd0e9dc5922a6e86579c2131d

**Comment by galkinvv** [comment] 2023-12-25 02:43
Without that fix fuse.portal filesystem lacks flock/lockf operations.
So this can be checked by the following python code to reject bottle directories that does not support locking and will have various problems with wine:

```python
with tempfile.TemporaryFile(dir=dir_to_test) as tl:
    fcntl.lockf(tl, fcntl.LOCK_UN)
```

On normal filesystem this works fine, and on problematic `fuse.portal` it throws `OSError: [Errno 38] Function not implemented`

Notes:

- Before updating xdg-desktop-portal just setting filesystem=host for flatpak does not help, since the directory select dialog still retes portal
- the `fcntl.flock` still not working even with xdg-desktop-portal==1.18.2 , but it seems that `fcntl.lockf` is enough
