### ISSUE TITLE
[Bug]: 32bit Bottles dont allow 32bit dependancies to be installed

### ISSUE THREAD

**Issue by Dungeonseeker** [bottlesdevs/Bottles#2355] opened 2022-12-08 17:32 UTC
### Describe the bug

Trying to run an older app and I need to install DX9 and .Net 4 on an X86 based prefix for it to run however after creating a custom bottle and selecting 32bit the dependencies page shows nothing available (and for that matter so does the "Install an Application" button).

Is it possible to have 32bit bottles show only 32bit dependencies?

### To Reproduce

1. Create new custom bottle
2. Select the 32bit option
3. After its created click "Dependencies" or "Install an Application"
4. List shows nothing compatible

### Package

Flatpak from Flathub

### Distribution

Arch

### Troubleshooting Logs

```shell
N/A
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment] 2022-12-08 19:37
Duplicate of https://github.com/bottlesdevs/Bottles/issues/2166

**Closed by mirkobrombin** 2022-12-08 19:37 UTC
