### ISSUE TITLE
Bottles crash report.

### ISSUE THREAD

**Issue by MM-Hussain** [bottlesdevs/Bottles#2616] opened 2023-01-25 09:24 UTC
### Describe the bug

When ever I start bottles, it crashes and a window opens stating that I should send a crash report. It shows that bottles is loading its third package and then the crash report window opens.

### To Reproduce

1. Click Bottles icon.
2. Wait till it starts loading its third package.
3. Crash report window opens.

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04 LTS Jammy Jellyfish

### Debugging Information

```shell
Can't reach that far. It doesn't go that far.
```

### Troubleshooting Logs

```shell
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Project-IGI/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 201, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 192, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 778, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 735, in process_bottle
    self.update_config(

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 848, in update_config
    with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file:
```

**Comment by StoneMoe** [comment] 2023-02-13 10:47
Hi, thanks for reporting!

is this duplicated with https://github.com/bottlesdevs/Bottles/issues/2456? if so, then it's a known issue and will be fixed in next release! meanwhile you can fix it with the workaround described in the issue.

**Comment by TheEvilSkeleton** [comment] 2023-02-19 22:30
Duplicate of #2456

**Closed by TheEvilSkeleton** 2023-02-19 22:30 UTC
