### ISSUE TITLE
[Bug]: bottles causing oom desktop environment crash

### ISSUE THREAD

**Issue by oomfiee** [bottlesdevs/Bottles#2102] opened 2022-09-24 17:36 UTC
### Describe the bug

while installing a dependency bottles will lag or crash the desktop environment (i.e KDE)  

### To Reproduce

1. open a bottle
2. install a dependency (i.e dotnet)
3. lag or out of memory desktop environment crash 

### Package

Flatpak from Flathub

### Distribution

NixOS 22.05

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.6
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4121808896
    Free: 4121661440
RAM:
    MemTotal: 7.7GiB
    MemAvailable: 2.6GiB
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment] 2022-09-25 11:43
I'm not able to reproduce this on a Kubuntu 22.04.1 VM

**Comment by TheEvilSkeleton** [comment] 2022-09-26 22:26
Any dependency in particular that causes Bottles to lag or crash? Or is it all the time?

**Comment by oomfiee** [comment] 2022-09-27 09:38
lags just happen when i open bottles
crashes is possibly when i try to install dotnet and visual c at the same time (altho it seems using the flatpak via the terminal fixes the crashes)

**Comment by oomfiee** [comment] 2022-09-27 09:40
this is possibly bc of mesa's unfinished haswell driver

**Comment by oomfiee** [comment] 2022-09-27 14:09
i was successful to reproduce this bug to but was unsuccessful in the crash part

to reproduce lag
1. create a custom bottle
2. install any dependency and then press select dependency 3 times or more and the flatpak will lag and turn white

**Comment by TheEvilSkeleton** [comment] 2022-09-27 14:49
> install any dependency and then press select dependency 3 times or more and the flatpak will lag and turn white

How do you "press select dependency 3 times or more"?

**Comment by oomfiee** [comment] 2022-09-27 15:05
by clicking on the checkmark button and clicking on the install selected and do it 3 times (or more) in a row 
![image](https://user-images.githubusercontent.com/80048740/192563600-b3603019-2220-44f6-b10f-a1dad0149124.png)

**Comment by TheEvilSkeleton** [comment] 2022-09-27 15:50
> by clicking on the checkmark button and clicking on the install selected and do it 3 times (or more) in a row ![image](https://user-images.githubusercontent.com/80048740/192563600-b3603019-2220-44f6-b10f-a1dad0149124.png)

Did you check if it goes out of memory?

**Comment by TheEvilSkeleton** [comment] 2022-09-27 20:07
Closing this issue since we plan to remove it. This will be continued in https://github.com/bottlesdevs/Bottles/issues/2112.

**Closed by TheEvilSkeleton** 2022-09-27 20:07 UTC
