### ISSUE TITLE
[Bug]: Cannot browse internal Windows FS when selecting program files.

### ISSUE THREAD

**Issue by ralmond** [bottlesdevs/Bottles#1831] opened 2022-07-23 21:00 UTC
### Describe the bug

I have an installer which instead of properly registering the program, simply unzips the executable to a file (https://norsys.com/download.html).

After running the installer, I can see the folder/program with the windows explorer and I can launch the program (Netica.exe) successfully from there.

However, when I go to the "Programs tab of my bottle", the file does not appear.  Refreshing does not help.  If I press the '+' button, I get a selection dialog that allows me to select a file on my host filesystem and not the internal windows one.  There also doesn't seem to be any simple mechanism for finding the internal bottles (windows) filesystem from the host (linux) filesystem.

### To Reproduce

1. Download Netica_Win.exe from https://norsys.com/downloads.html (This particular file is not necessary, but it is handy and illustrates the problem.)
2. Run the Netica_Win.exe file, selecting a directory inside of "C:\Program Files" as a location.

3. Open the Windows explorer and navigate to "C:\Program Files\Netica\Netica 609\"  Verify that the file `Netica.exe` is there.  (You should be able to run the program from here.  It will run in a limited mode without a license key, sufficient for verifying that it works).

4. Go to the Programs tab.  Press refresh.  Netica. exe does not show up.
5. Press `+` to open file chooser, note that file browser is pointed at host file system without indication of how to access files internal to the bottle.

### Package

Flatpak from Flathub

### Distribution

POP_OS 22.04

### Health Check

```shell
You need better directions here.  Where should I be looking for this hamberger menu and "health check".  There is no hamburger menu in my bottles window and the one in by browser doesn't have a "Health check" selection.

I'm running Gnome 42.2 and gdm3.
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

The problem is more serious than I thought.
The location of the file turns out to be `/home/ralmond/.var/app/com.usebottles.bottles/data/bottles/bottles/Netica/drive_c/Program Files/Netica/Netica 609/Netica.exe`; however, the file chooser dialog will not allow me to select the invisible ".var" directory. 

So I'm kind of stuck.

**Comment by mirkobrombin** [comment] 2022-07-23 21:12
hamburger menu:
![image](https://user-images.githubusercontent.com/9479903/180622949-5e2695be-0608-4fb5-9846-161d6f73ee34.png)

about the filechooser position: https://github.com/bottlesdevs/Bottles/issues/1017

the bottle path is in .var/app/com.usebottles.bottles/data/bottles/bottles/your_bottle/drive_c

about programs not being displayed: https://github.com/bottlesdevs/Bottles/issues/1792#issuecomment-1186285449


closing as duplicate of #1017 and #1792, feel free to add more comments here or there

**Comment by ralmond** [comment] 2022-07-23 21:22
Ah.  I found the hamburger menu.  It is at the top level of the bottles.  I was inside a specific bottle and it just did not appear.  For completeness, it is:
```
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.10-76051810-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16801505280
    Free: 16801349632
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 14.1GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

**Comment by mirkobrombin** [comment] 2022-07-23 21:23
The le for adding it

**Closed by mirkobrombin** 2022-07-23 21:24 UTC
