### ISSUE TITLE
[Bug]: No placeholder icon on Library when program doesn't offer one

### ISSUE THREAD

**Issue by raploz** [bottlesdevs/Bottles#2767] opened 2023-03-02 03:53 UTC
### Describe the bug

After adding a program to the Library, I noticed it showed a blank square on the Library page. Hovering over the square showed the name of the program and a button to start. Right-clicking didn't show any option to select an icon.

Suggestion: When an application doesn't have an icon, show a placeholder.

![image](https://user-images.githubusercontent.com/40844298/222326768-475a8920-ac41-4573-886f-d6d439cfdae7.png)

### To Reproduce

1. Add an application that doesn't have an icon to a bottle
2. Add that application to the library

### Package

Flatpak from Flathub

### Distribution

KDE Neon

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-32-generic
Disk:
    Total: 8353521664
    Free: 8353374208
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

### Additional context

Refer to https://github.com/bottlesdevs/Bottles/issues/2762 for more context

**Comment by TheEvilSkeleton** [comment] 2023-03-03 03:34
Duplicate of #2458

**Closed by TheEvilSkeleton** 2023-03-03 03:34 UTC
