### ISSUE TITLE
Application could not be started

### ISSUE THREAD

**Issue by Ricky-Tigg** [bottlesdevs/Bottles#231] opened 2021-04-21 09:40 UTC
Tested on | **OS:** Fedora; **Environment:** Gnome 40.0 on Wayland; **Component:** bottles-3.1.3-1.fc34.noarch.  **Source file:** _*.exe_, install version, [https://rufus.ie/en/](https://rufus.ie/en/)

```
$ bottles
2021-04-21 12:35:46 INFO: Runners found: [chardonnay-6.4]
2021-04-21 12:35:46 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-21 12:35:46 INFO: Connection status: online …
2021-04-21 12:35:47 INFO: Connection status: online …
2021-04-21 12:35:47 INFO: Connection status: online …
2021-04-21 12:35:48 INFO: Bottles found: rufus
2021-04-21 12:35:48 INFO: Bottles Started!
2021-04-21 12:35:57 INFO: Running an executable on the wineprefix …
/lib/ld-linux.so.2: could not open
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: Internal error.
```

**Comment by mirkobrombin** [comment] 2021-04-21 09:51
Wine doesn't works on wayland for what I know

**Comment by Ricky-Tigg** [comment] 2021-04-21 12:42
On Xorg side | Same observation.

**Comment by mirkobrombin** [comment] 2021-04-21 12:53
Try with a more recente release, like: https://github.com/bottlesdevs/Bottles/releases/tag/3.1.5

**Comment by Ricky-Tigg** [comment] 2021-04-22 09:54
- Translation | Addition of a new language entry into https://hosted.weblate.org/projects/bottles/bottles/ and translations are is pushed to GitHub in real time. I did know that they are handled in GitHub as commits

- Indeed, tested from source:: https://src.fedoraproject.org/rpms/bottles. 
```
$ rpm -qi bottles | sed -n '12,13p'
Build Host  : buildvm-ppc64le-12.iad2.fedoraproject.org
Packager    : Fedora Project
```
**X.org verification:**
```
$ loginctl show-session `loginctl | sed -n 2p | awk '{print $1}'` -p Type
Type=x11
```
- Distributed as AppImage! Well done  **Execution** | Same observation.
```
$ ./Bottles-devel-x86_64.AppImage 
Gtk-Message: 11:01:41.782: Failed to load module "pk-gtk-module"
2021-04-22 11:01:42 INFO: Runners found: [chardonnay-6.4]
2021-04-22 11:01:42 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-22 11:01:42 INFO: Connection status: online …
2021-04-22 11:01:42 INFO: Dxvk found: [dxvk-1.8.1]
2021-04-22 11:01:42 INFO: Runners found: [chardonnay-6.4]
2021-04-22 11:01:42 INFO: Bottles found: rufus
2021-04-22 11:01:42 INFO: Connection status: online …
2021-04-22 11:01:42 INFO: Connection status: online …
2021-04-22 11:01:42 INFO: Connection status: online …
2021-04-22 11:01:43 INFO: Connection status: online …
2021-04-22 11:01:43 INFO: Bottles found: rufus
2021-04-22 11:01:43 INFO: Bottles Started!
2021-04-22 11:01:55 INFO: Running an executable on the wineprefix …
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

/lib/ld-linux.so.2: could not open
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: Internal error.
```
Executed via `firejail`:
```
$ firejail --appimage ./Bottles-devel-x86_64.AppImage
Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **
Parent pid 15052, child pid 15055
**     Warning: dropping all Linux capabilities     **

Child process initialized in 103.49 ms
Gtk-Message: 12:31:35.085: Failed to load module "pk-gtk-module"
(...)
2021-04-22 12:31:36 INFO: Bottles Started!
2021-04-22 12:31:45 INFO: Running an executable on the wineprefix …
wine: chdir to /tmp/.wine-1000/server-23-25f841 : Permission denied

Parent is shutting down, bye...
AppImage unmounted
```
With **elevated privileges** | Application window is not started:
```
$ sudo firejail --appimage ./Bottles-devel-x86_64.AppImage
(...)
** Note: you can use --noprofile to disable server.profile **

Parent pid 15167, child pid 15170
The new log directory is /proc/15170/root/var/log
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 52.24 ms
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(bottles:3): Gtk-CRITICAL **: 12:35:40.220: gtk_style_context_add_provider_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
/run/firejail/appimage/.appimage-15167///usr/local/share/bottles/bottles/pages/list.py:27: Warning: invalid (NULL) pointer instance
  Handy.init()
/run/firejail/appimage/.appimage-15167///usr/local/share/bottles/bottles/pages/list.py:27: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  Handy.init()
/run/firejail/appimage/.appimage-15167///usr/local/share/bottles/bottles/pages/list.py:27: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  Handy.init()

(bottles:3): Gtk-CRITICAL **: 12:35:40.256: gtk_style_context_add_provider_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(bottles:3): Gtk-CRITICAL **: 12:35:40.256: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(bottles:3): Gtk-CRITICAL **: 12:35:40.256: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (icon_theme)' failed
No protocol specified
Unable to init server: Could not connect: Connection refused

(bottles:3): Gtk-WARNING **: 12:35:40.270: cannot open display: :0

Parent is shutting down, bye...
AppImage unmounted
```

**Comment by mirkobrombin** [comment] 2021-04-22 17:12
The translations are not automatic merged, I need accept the PR. For your problem I do not know how to act, I have too few details but I will investigate as soon as possible.

**Comment by Ricky-Tigg** [comment] 2021-04-23 14:35
Still official package | **Tested on:** Linux Mint 20 Mate. Same observations as on Fedora, be the application run in sandbox via `fiirejail` or not.

Package provided by Mint  seems to come from Flathud; it runs a sub-process at _/usr/bin/python3 /app/bin/bottles_. I lack knowledge to launch it from command line in order to serve debug investigation

**Comment by gabrielluz-br** [comment] 2021-04-26 02:56
Same happens to me. It happened after I've installed Newaita icon theme from github. I didn't use an APT package or a deb file, it just happened.
Even uninstalling the theme won't open Bottles anymore. I think when people changes the theme, there's some problem with mime database, but even updating the database won't make the problem go away.

Below is my log:
```
$./Bottles-devel-x86_64.AppImage 

(bottles:5436): Gtk-WARNING **: 23:55:17.202: Theme parsing error: gtk.css:17:25: negative values are not allowed.

(bottles:5436): Gtk-WARNING **: 23:55:17.464: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted
```

**Comment by mirkobrombin** [comment] 2021-04-26 06:06
> Same happens to me. It happened after I've installed Newaita icon theme from github. I didn't use an APT package or a deb file, it just happened.
> Even uninstalling the theme won't open Bottles anymore. I think when people changes the theme, there's some problem with mime database, but even updating the database won't make the problem go away.
> 
> Below is my log:
> 
> ```
> $./Bottles-devel-x86_64.AppImage 
> 
> (bottles:5436): Gtk-WARNING **: 23:55:17.202: Theme parsing error: gtk.css:17:25: negative values are not allowed.
> 
> (bottles:5436): Gtk-WARNING **: 23:55:17.464: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Aborted
> ```

Reading your output, it's not the same as the issue

**Comment by hthre7** [comment] 2021-04-26 07:42
> Same happens to me. It happened after I've installed Newaita icon theme from github. I didn't use an APT package or a deb file, it just happened.
> Even uninstalling the theme won't open Bottles anymore. I think when people changes the theme, there's some problem with mime database, but even updating the database won't make the problem go away.
> 
> Below is my log:
> 
> ```
> $./Bottles-devel-x86_64.AppImage 
> 
> (bottles:5436): Gtk-WARNING **: 23:55:17.202: Theme parsing error: gtk.css:17:25: negative values are not allowed.
> 
> (bottles:5436): Gtk-WARNING **: 23:55:17.464: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Aborted
> ```

could you try this 
```
update-mime-database $HOME/.local/share/mime
update-desktop-database $HOME/.local/share/applications
```

**Comment by hthre7** [comment] 2021-04-26 08:00
> Tested on | **OS:** Fedora; **Environment:** Gnome 40.0 on Wayland; **Component:** bottles-3.1.3-1.fc34.noarch. **Source file:** _*.exe_, install version, https://rufus.ie/en/
> 
> ```
> $ bottles
> 2021-04-21 12:35:46 INFO: Runners found: [chardonnay-6.4]
> 2021-04-21 12:35:46 INFO: Dxvk found: [dxvk-1.8.1]
> 2021-04-21 12:35:46 INFO: Connection status: online …
> 2021-04-21 12:35:47 INFO: Connection status: online …
> 2021-04-21 12:35:47 INFO: Connection status: online …
> 2021-04-21 12:35:48 INFO: Bottles found: rufus
> 2021-04-21 12:35:48 INFO: Bottles Started!
> 2021-04-21 12:35:57 INFO: Running an executable on the wineprefix …
> /lib/ld-linux.so.2: could not open
> Application could not be started, or no application associated with the specifie
> d file.
> ShellExecuteEx failed: Internal error.
> ```

do add i386 architecture to your system

**Comment by gabrielluz-br** [comment] 2021-04-26 18:11
> > Same happens to me. It happened after I've installed Newaita icon theme from github. I didn't use an APT package or a deb file, it just happened.
> > Even uninstalling the theme won't open Bottles anymore. I think when people changes the theme, there's some problem with mime database, but even updating the database won't make the problem go away.
> > Below is my log:
> > ```
> > $./Bottles-devel-x86_64.AppImage 
> > 
> > (bottles:5436): Gtk-WARNING **: 23:55:17.202: Theme parsing error: gtk.css:17:25: negative values are not allowed.
> > 
> > (bottles:5436): Gtk-WARNING **: 23:55:17.464: Could not load a pixbuf from icon theme.
> > This may indicate that pixbuf loaders or the mime database could not be found.
> > **
> > Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> > Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> > Aborted
> > ```
> 
> could you try this
> 
> ```
> update-mime-database $HOME/.local/share/mime
> update-desktop-database $HOME/.local/share/applications
> ```

I've tried those commands before and I've tried again just now. Still doesn't work.

**Comment by hthre7** [comment] 2021-04-27 06:11
> I've tried those commands before and I've tried again just now. Still doesn't work.

could you continue discussing this issue at #230 cause it related to your issue.

**Comment by Ricky-Tigg** [comment] 2021-04-27 07:18
My system uses default settings regards to [supported architectures](https://fedoraproject.org/wiki/Architectures) 

- **Primary architectures**, AMD x86-64 – _wine.x86_64_ illustrates that. Packages with no architecture are supported as well – _bottles.noarch_ illustrates that.
- **Alternative architecture**: 32-bit for i686 – _wine.i686_ illustrates that. No pacckage with that architecture installed.

**Comment by hthre7** [comment] 2021-04-27 07:45
> My system uses default settings regards to [supported architectures](https://fedoraproject.org/wiki/Architectures)
> 
>     * **Primary architectures**, AMD x86-64 – _wine.x86_64_ illustrates that. Packages with no architecture are supported as well – _bottles.noarch_ illustrates that.
> 
>     * **Alternative architecture**: 32-bit for i686 – _wine.i686_ illustrates that. No pacckage with that architecture installed.

I mean for system libraries for example in debian-based distro you add those libraries in the following 'sudo dpkg --add-architecture i386'

not for wine itself for libraries for example in debain-based distro

**Comment by Ricky-Tigg** [comment] 2021-04-27 14:24
Correction | Some packages whose architecture is i686 are also installed, e.g. _mesa-dri-drivers-21.0.3-1.fc34.i686_. According to my investigation, no counterpart of '`dpkg --add-architecture`' exist for my system. Package dpkg is available. Once installed '`dpkg --add-architecture i386`' can be executed. At last the required packaged would have to be manually installed. 

Still official package | After Windows executable has beeb selected, this Wine window message is displayed:

![Wine_window_Bottles-devel-x86_64 AppImage_rufus](https://user-images.githubusercontent.com/26058215/116257333-a0c54c00-a77c-11eb-899e-dcaf242f94e4.png)

Running with elevated privilege opens the Bottles GUI, which invariably fails do download needed components.

**Comment by Ricky-Tigg** [comment] 2021-04-28 07:05
Correction | Some packages whose architecture is i686 are also installed, e.g. _mesa-dri-drivers-21.0.3-1.fc34.i686_. According to my investigation, no counterpart of '`dpkg --add-architecture`' exist for my system, though package dpkg is available. Once installed '`dpkg --add-architecture i386`' can be executed. At last updating the system '`dnf -y --refresh upgrade`'.
'
Identical results be package official or unofficial, excepted that official package reports at first row '`Gtk-Message: 09:21:52.028: Failed to load module "pk-gtk-module"`'. Wine window message displayed after Windows executable has been selected:

![Wine_window_Bottles-devel-x86_64 AppImage_rufus](https://user-images.githubusercontent.com/26058215/116257333-a0c54c00-a77c-11eb-899e-dcaf242f94e4.png)

**Running with** _elevated privileges_ 
- Official package | Fails to launch Bottles
```
$ sudo ./Bottles-devel-x86_64.AppImage 
[sudo] password for yk: 
Gtk-Message: 09:42:12.994: Failed to load module "pk-gtk-module"

(bottles:8441): Gtk-WARNING **: 09:42:13.249: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Aborted
```
- Unofficial package
Launches Bottles, which invariably fails to achieve the download process.
```
$ sudo bottles
[sudo] password for yk: 
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 WARNING: No dxvk found.
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 WARNING: No runners found.
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
  File "/usr/share/bottles/bottles/utils.py", line 174, in target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
    self.window.send_notification(
  File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
    notification.show()
2021-04-28 09:54:54 INFO: Connection status: online …
2021-04-28 09:54:54 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
  File "/usr/share/bottles/bottles/utils.py", line 174, in target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
    self.window.send_notification(
  File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
    notification.show()
2021-04-28 09:54:55 INFO: Connection status: online …
2021-04-28 09:54:55 INFO: Connection status: online …
2021-04-28 09:54:55 INFO: Bottles Started!
2021-04-28 09:55:01 WARNING: No dxvk found.
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 WARNING: No runners found.
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 INFO: Connection status: online …
2021-04-28 09:55:01 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
  File "/usr/share/bottles/bottles/utils.py", line 174, in target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
    self.window.send_notification(
  File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
    notification.show()
2021-04-28 09:55:01 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
  File "/usr/share/bottles/bottles/utils.py", line 174, in target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
    self.window.send_notification(
  File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
    notification.show()
2021-04-28 09:55:01 INFO: Connection status: online …
```

**Comment by gabrielluz-br** [comment] 2021-04-28 13:02
> > I've tried those commands before and I've tried again just now. Still doesn't work.
> 
> could you continue discussing this issue at #230 cause it related to your issue.

Yes. Sure. Thanks.

**Comment by mirkobrombin** [comment] 2021-04-30 05:56
> Correction | Some packages whose architecture is i686 are also installed, e.g. _mesa-dri-drivers-21.0.3-1.fc34.i686_. According to my investigation, no counterpart of '`dpkg --add-architecture`' exist for my system, though package dpkg is available. Once installed '`dpkg --add-architecture i386`' can be executed. At last updating the system '`dnf -y --refresh upgrade`'.
> '
> Identical results be package official or unofficial, excepted that official package reports at first row '`Gtk-Message: 09:21:52.028: Failed to load module "pk-gtk-module"`'. Wine window message displayed after Windows executable has been selected:
> 
> ![Wine_window_Bottles-devel-x86_64 AppImage_rufus](https://user-images.githubusercontent.com/26058215/116257333-a0c54c00-a77c-11eb-899e-dcaf242f94e4.png)
> 
> **Running with** _elevated privileges_
> 
> * Official package | Fails to launch Bottles
> 
> ```
> $ sudo ./Bottles-devel-x86_64.AppImage 
> [sudo] password for yk: 
> Gtk-Message: 09:42:12.994: Failed to load module "pk-gtk-module"
> 
> (bottles:8441): Gtk-WARNING **: 09:42:13.249: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
> Aborted
> ```
> 
> * Unofficial package
>   Launches Bottles, which invariably fails to achieve the download process.
> 
> ```
> $ sudo bottles
> [sudo] password for yk: 
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 WARNING: No dxvk found.
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 WARNING: No runners found.
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
> Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
>   File "/usr/share/bottles/bottles/utils.py", line 174, in target
>     result = self.task_func(*args, **kwargs)
>   File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
>     self.window.send_notification(
>   File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
>     notification.show()
> 2021-04-28 09:54:54 INFO: Connection status: online …
> 2021-04-28 09:54:54 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
> Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
>   File "/usr/share/bottles/bottles/utils.py", line 174, in target
>     result = self.task_func(*args, **kwargs)
>   File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
>     self.window.send_notification(
>   File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
>     notification.show()
> 2021-04-28 09:54:55 INFO: Connection status: online …
> 2021-04-28 09:54:55 INFO: Connection status: online …
> 2021-04-28 09:54:55 INFO: Bottles Started!
> 2021-04-28 09:55:01 WARNING: No dxvk found.
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 WARNING: No runners found.
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 INFO: Connection status: online …
> 2021-04-28 09:55:01 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
> Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
>   File "/usr/share/bottles/bottles/utils.py", line 174, in target
>     result = self.task_func(*args, **kwargs)
>   File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
>     self.window.send_notification(
>   File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
>     notification.show()
> 2021-04-28 09:55:01 ERROR: Error while running async job: <bound method BottlesRunner.async_install_component of <bottles.runner.BottlesRunner object at 0x7f69bf80e550>>
> Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
>   File "/usr/share/bottles/bottles/utils.py", line 174, in target
>     result = self.task_func(*args, **kwargs)
>   File "/usr/share/bottles/bottles/runner.py", line 311, in async_install_component
>     self.window.send_notification(
>   File "/usr/share/bottles/bottles/window.py", line 205, in send_notification
>     notification.show()
> 2021-04-28 09:55:01 INFO: Connection status: online …
> ```

You are reporting too many different issues on different packages and we can't keep up with you.Pick a package and let's focus on that.Also all the problems I read seem to be caused by the system .. do you have any particular configuration? Restrictions or similar?

**Comment by Ricky-Tigg** [comment] 2021-04-30 09:10
If I was you, i would have soon enough begined to be clear, by avoiding irrelevant quotations everywhere with everyone, removing on time the mention _unofficial-package_ you added which became non correct regards to its context and brought confusion. Issues reported here were involving your very official package – _AppImage_, That would have allowed me soon enough to stop wasting my time, that was put into investigating issues from that non-official package. So now are you ready, aren't you.  You have one component left in your focus then can start investigating unless you already did.

**Comment by Ricky-Tigg** [comment] 2021-04-30 09:16
Good to know. If I was you, i would have soon enough begun to be clear, by avoiding irrelevant quotations everywhere with everyone, and removing on time the mention _unofficial-package_ you added and had became non correct regards to its context and as a result brought confusion. Issues reported here were involving also your very official package – AppImage, That would have allowed me soon enough to stop wasting my time, which was put into investigating issues from that non-official package. So now you are ready, aren't you? You have one component left in your focus then can start investigating unless you already did.

**Comment by mirkobrombin** [comment] 2021-04-30 10:31
> Good to know. If I was you, i would have soon enough begun to be clear, by avoiding irrelevant quotations everywhere with everyone, and removing on time the mention _unofficial-package_ you added and had became non correct regards to its context and as a result brought confusion. Issues reported here were involving also your very official package – AppImage, That would have allowed me soon enough to stop wasting my time, which was put into investigating issues from that non-official package. So now you are ready, aren't you? You have one component left in your focus then can start investigating unless you already did.

Did I miss some messages or did you read my bad or giving it the wrong tone?

The `ld.so` problem (from your first post) it can be caused by many, many reasons. If it comes up with any kind of package, the problem may be in the setup.

Regarding the tags and mentions, this is not my job and I am currently the only developer on the project. I'm sorry if I made you "waste your time" but I don't have 120h days and I make do with what I have.

**Comment by Ricky-Tigg** [comment] 2021-04-30 10:54
Let's stick to the report.  Clean Fedora 34 x86_64 installation | Updated system | System with defaults | No particular manually set configuration or restrictions.

**Comment by mirkobrombin** [comment] 2021-04-30 10:59
> Let's stick to the report. Clean Fedora 34 x86_64 installation | Updated system | System with defaults | No particular manually set configuration or restrictions.

I am setting up a VM with Fedora 34 so that I can test in a clean environment. In the meantime can you tell me if you use nouveau or proprietary drivers?

**Comment by pietrodicaprio** [comment] 2021-04-30 11:52
We tried to replicate the issue in a `Clean Fedora 34 x86_64 installation | Updated system | System with defaults | No particular manually set configuration or restrictions.`  and the app works as expected.

Closing this since:
- has been opened without respecting the mandatory issue layout
- the information is not clear
- it's not possible to understand and replicate the issue

If you want to receive further support open a new issue **following the template** and providing clear information.

Thank you

**Closed by pietrodicaprio** 2021-04-30 11:52 UTC
Labels: can't replicate, invalid, unofficial-package

**Comment by mirkobrombin** [comment] 2021-04-30 11:57
As said by @pietrodicaprio, we cannot replicate your problem but I can recommend you to install the `wine` package and try again. Open a new issue following the **Bug Report template** for any other problems.

If it works after installing the `wine` package, probably some dependencies are missing in the package for fedora.

**Comment by Ricky-Tigg** [comment] 2021-04-30 12:11
That one too was installed. Already closed; that tells everything about the developpers team. After all its your application. I can see your  frustration. Better to close and not opening anything there. Ciao Italia.
