### ISSUE TITLE
[Bug]: consolas instillation issue

### ISSUE THREAD

**Issue by vadim-ktnkv** [bottlesdevs/Bottles#2240] opened 2022-11-06 22:51 UTC
### Describe the bug

Consolas dependency cannot be installed.
After pressing diskette icon, It turns to loading circle, then after some times become as exclamation mark.

### To Reproduce

1. Create x64 bottle with caffe-7.20 runner.
2. At the dependencies try to install "consolas".

### Package

Flatpak from Flathub

### Distribution

Manjaro 22.0.0

### Troubleshooting Logs

```shell
[Errno 20] Not a directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/temp/consolas-fonts-tts.tar/Consolas-Bold.ttf/Consolas-Bold.ttf'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 144, in install
    res = self.__perform_steps(config, step)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 247, in __perform_steps
    if not self.__step_install_fonts(config=config, step=step):

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 527, in __step_install_fonts
    shutil.copyfile(f"{path}/{font}", f"{font_path}/{font}")

  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-11-08 20:51
duplicate of https://github.com/bottlesdevs/dependencies/issues/135

**Closed by mirkobrombin** 2022-11-08 20:51 UTC
