### ISSUE TITLE
[Bug]: Since 51.10 release, UI doesn't display in a readable way

### ISSUE THREAD

**Issue by lukejagger** [bottlesdevs/Bottles#3253] opened 2024-01-21 11:02 UTC
### Describe the bug

Since 51.10 release, UI doesn't display in a readable way, with a small column of text rather than filling the window.  
I am on Ubuntu Studio 23.10, using Wayland desktop.  Previous version worked perfectly in same setup.

### To Reproduce

Open app.
Text is displayed incorrectly from start.
![Screenshot_20231224_112431](https://github.com/bottlesdevs/Bottles/assets/25955344/47416549-6aac-42f9-8d58-f8838c989a15)

### Package

Flatpak from Flathub

### Distribution

Ubuntu Studio 23.10

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-14-lowlatency
Disk:
    Total: 12279324672
    Free: 12279160832
RAM:
    MemTotal: 22.9GiB
    MemAvailable: 15.7GiB
Bottles_envs: null
```

**Comment by Aeternitae** [comment] 2024-01-28 18:07
Also having this problem on Bottles with EndeavourOS/Arch on Wayland using KDE on the latest version.

**Comment by CrashTD** [comment] 2024-01-31 08:36
Can confirm this on EndeavourOS with KDE Wayland. Looks exactly the same here. I'm on the KDE 6 Beta though so maybe it has to do with that?

**Comment by breuxi** [comment] 2024-01-31 21:27
Same here!

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.2-arch1-1 (64-bit)
Graphics Platform: Wayland

**Comment by AccaliaDeElementia** [comment] 2024-02-06 23:07
Likewise, this issue also exists for me.

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.3-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 20 × 12th Gen Intel® Core™ i7-12700H
Memory: 30.9 GiB of RAM
Graphics Processor: Mesa Intel® Arc
Manufacturer: Intel(R) Client Systems
Product Name: NUC12SNKi72
System Version: M78931-500

downgrading to the previous flatpak release does resolve the narrow display issue, but isn't a great solution as it also misses out on the latest updates.

`sudo flatpak update --commit=ffe7d2673449aaf63d08da8e493628b1564b7bf7b084f05787fb9243d8b3633f com.usebottles.bottles`

**Comment by jotoho** [comment] 2024-02-08 12:15
Same issue here.

I'm using the flatpak package (`com.usebottles.bottles` `51.10` from flathub) on an up-to-date Arch Linux x86-64 KDE Plasma Wayland session.
I should also note that I'm using two monitors, one 1920x1080 and one 3840x2160, with the 4k monitor on 200% UI scaling. Bottles UI is borked, no matter which monitor I put it on.
I hadn't used Bottles for a while, but the issue has only appeared recently.

<details>
<summary>Screenshot</summary>

![Screenshot_20240208_130743](https://github.com/bottlesdevs/Bottles/assets/12120743/62746752-bd5a-45ca-b864-5ed2b93c35b8)

</details>

**Comment by leotada** [comment] 2024-02-08 12:23
I saw the same problem in other GTK4 application, I think that it's a GTK4 bug. (if I remember correctly it's Gaphor)

**Comment by nate-moo** [comment] 2024-02-09 22:36
https://github.com/bottlesdevs/Bottles/issues/3214#issuecomment-1882658850 duplicate of #3214 link provides temporary fix that works for me

**Comment by AccaliaDeElementia** [comment] 2024-02-19 13:13
Flatpak version 51.11 appears to resolve this issue without using the workaround Nate-moo mentions above.

**Closed** 2024-02-20 17:48 UTC

**Comment by yswtrue** [comment] 2024-03-09 13:36
> Flatpak version 51.11 appears to resolve this issue without using the workaround Nate-moo mentions above.

I have upgrade to latest version on flatpak, but still have this issue on plasma 6
