### ISSUE TITLE
[Request]: Install From DVD Feature

### ISSUE THREAD

**Issue by TheChaosRabbit** [bottlesdevs/Bottles#1478] opened 2022-05-17 18:16 UTC
### Tell us the problem or your need

I tried to use bottles to install some windows games like "Plants vs. Zombies" and "Roller Coaster Tycoon 3 Platinum" from a PC DVD but found that I couldn't because there wasn't an option to select more than one executable in a bottle. I tried to select the file with the .exe extension since this usually works on windows and even with wine, but it gave me a fatal error when I tried with bottles. Since I installed the flatpak package for Bottles, I tried giving the app more permissions using Flatseal before installing again. When I tried installing after doing that, it didn't give me the fatal error but it didn't install either.

The list of files on the disc for Plants vs. Zombies looks like this...
![Plants vs  Zombies Disc](https://user-images.githubusercontent.com/105741926/168881660-21dfd3df-d352-43de-b309-d2d4e5e3ccb6.png)

### Describe the solution you'd like

A good solution would be an "Install From DVD" feature which allows the user to select all of the files on the DVD and use them to install the game in the bottle. It would also be great if there was an option to, if needed, check the DVD port of a computer when running a game installed this way. This is because some games like "Roller Coaster Tycoon 3 Platinum" still require you to keep the DVD in the computer to play the game even after installing even while others like "Plants vs. Zombies" do not.

**Comment by mirkobrombin** [comment] 2022-05-17 19:07
Hi, is this a duplicate of #959 ?

**Comment by TheChaosRabbit** [comment] 2022-05-17 19:15
Oh I guess it is very similar. Sorry

**Comment by mirkobrombin** [comment] 2022-05-17 20:12
No problem, I'll track the feature request there

**Closed by mirkobrombin** 2022-05-17 20:12 UTC
Labels: Feature request
