### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by ericsbelcher** [bottlesdevs/Bottles#520] opened 2021-09-06 15:57 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.8.28-treviso-2

**Log**
```python3
[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/temp/arial32_exe/Ariali.TTF'  File "/app/share/bottles/bottles/utils.py", line 277, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/dependency.py", line 196, in async_install
    self.__step_install_fonts(

  File "/app/share/bottles/bottles/backend/dependency.py", line 534, in __step_install_fonts
    shutil.copyfile(

  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

```

**Comment by mirkobrombin** [comment] 2021-09-06 19:23
Duplicate of #517

**Closed by mirkobrombin** 2021-09-06 19:23 UTC
