### ISSUE TITLE
AppImage doesn't work on Fedora 34 with GNOME

### ISSUE THREAD

**Issue by Bohooslav** [bottlesdevs/Bottles#345] opened 2021-07-03 19:09 UTC
**Describe the bug**
I downloaded AppImage from GitHub. It doesn't wanna run.

**Installation**
 - Appimage
 - 2021.7.1-treviso-x86_64.AppImage 

**To Reproduce**
1. Go to Releases at GitHub
2. Download the AppImage
3. Try to run it

**Expected behavior**
I wanted to run the application

**Screenshots**
```
[bohuslav@aich-pee Applications]$ ./Bottles-2021.7.1-treviso-x86_64.AppImage 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
QSocketNotifier: Can only be used with threads started with QThread

(bottles:48712): GLib-GIO-ERROR **: 22:06:23.181: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
```

**Desktop (please complete the following information):**
 - Fedora 
 - 34

**Additional context**

**Comment by mirkobrombin** [comment] 2021-07-03 19:39
Is this on Wayland?

**Comment by mirkobrombin** [comment] 2021-07-03 20:04
Duplicate of #303

**Closed** 2021-07-03 20:38 UTC
Labels: bug

**Comment by Bohooslav** [comment] 2021-07-05 10:56
ok
