### ISSUE TITLE
[Bug]: Hang after downloading packages on Steam Deck

### ISSUE THREAD

**Issue by YourGamesBeOver** [bottlesdevs/Bottles#3026] opened 2023-08-09 01:56 UTC
### Describe the bug

After enabling steam integration, app will no longer boot past the "Starting up..." page, despite saying that it has downloaded all packages it needs to. Closing and reopening (or even reinstalling) cause no change except for the addition of a crash reporting dialog.

![image](https://github.com/bottlesdevs/Bottles/assets/3501739/bfa9bef8-2edd-4b4f-b021-8504fd9e9f6d)

### To Reproduce

1. fresh install via discover app
2. enable full file access
3. launch app
4. enable steam integration
5. close app
6. launch app
7. app hangs on "Starting up..." page with 3 of 3 packages fetched
8. subsequent launches show the crash reporter on launch 

### Package

Flatpak from Flathub

### Distribution

Steam Deck

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: plasma-steamos-oneshot
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve36-1-neptune
Disk:
    Total: 7769219072
    Free: 7769067520
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.1GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
'LastUpdated'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 229, in get_manager
    mng = Manager(g_settings=self.settings)

  File "/app/share/bottles/bottles/backend/utils/singleton.py", line 6, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 141, in __init__
    times.update(self.checks(install_latest=False, first_run=True).data)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 195, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 862, in check_bottles
    self.steam_manager.update_bottles()

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 320, in update_bottles
    prefixes = self.list_prefixes()

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 305, in list_prefixes
    int(_acf["AppState"]["LastUpdated"])
```

**Comment by Coopydood** [comment] 2023-08-09 20:21
Can reproduce on Linux desktop.

This seems to be related to a Steam library issue - having an uninitialized Steam library fixes the issue. A new Steam library still causes Bottles to fail.

```
'LastUpdated'  File "/usr/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 229, in get_manager
    mng = Manager(g_settings=self.settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/share/bottles/bottles/backend/utils/singleton.py", line 6, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 141, in __init__
    times.update(self.checks(install_latest=False, first_run=True).data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 195, in checks
    self.check_bottles()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 862, in check_bottles
    self.steam_manager.update_bottles()

  File "/usr/share/bottles/bottles/backend/managers/steam.py", line 320, in update_bottles
    prefixes = self.list_prefixes()
               ^^^^^^^^^^^^^^^^^^^^

  File "/usr/share/bottles/bottles/backend/managers/steam.py", line 305, in list_prefixes
    int(_acf["AppState"]["LastUpdated"])
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
```

Arch Linux, 6.4.9-arch1-1

**Comment by koplo199** [comment] 2023-08-17 08:34
Duplicated of #3009 and fixed by https://github.com/bottlesdevs/Bottles/commit/cb37c13f9bfb8afa15e5c718333fbb21e2168f6d

**Closed** 2023-08-17 09:10 UTC
