### ISSUE TITLE
[Bug]: Bottles GUI error when not using Pop_os! default icons

### ISSUE THREAD

**Issue by IvanLi0731** [bottlesdevs/Bottles#2356] opened 2022-12-11 08:31 UTC
### Describe the bug

https://imgur.com/a/6nzcmMj
When Pop!_OS Gnome Tweak - Appearance - Icons switched to any thing other than Pop, the GUI in Bottles will show missing icons. 

### To Reproduce

1. Go to "Tweaks"
2. Go to "Appearance"
3. Select "Icons"
4. Change to others
5. Open Bottles
6. See missing icons

### Package

Flatpak from Flathub

### Distribution

Pop!_OS 22.04 (Jammy)

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.6-76060006-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 33263468544
    Free: 33263321088
RAM:
    MemTotal: "66.5\_GB"
    MemAvailable: "60.8\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment] 2022-12-11 08:36
Duplicate of https://github.com/bottlesdevs/Bottles/issues/1627 and https://github.com/bottlesdevs/Bottles/issues/2265

Read here: https://github.com/bottlesdevs/Bottles/issues/2265#issuecomment-1313442063

**Closed by mirkobrombin** 2022-12-11 08:36 UTC

**Comment by digimezzo** [comment] 2026-02-23 05:43
For those coming here a after a web search, the explanation in #1627 is not accurate. The evidence:

- When using the OS's default icon set, Bottles displays the icons. 
- When using a custom icon set, Bottles displays missing icons. 

Custom icon sets are usually installed in `~/.icons`, while default icons are located in `/usr/share/icons`. This data suggests that Bottles cannot read the icons when they are located in the `/home` directory. Which might be related to the sandboxed nature of Flatpak.

**The fix to this issue**: install the custom icons to `/usr/share/icons` instead of `~/.icons`.
