### ISSUE TITLE
[BUG]  No module named 'patoolib'

### ISSUE THREAD

**Issue by Translator5** [bottlesdevs/Bottles#937] opened 2022-01-16 19:26 UTC
**Describe the bug**
Trying to run the program using the terminal or the symbolic link runs into a instant crash of the program.
Instead it gives me a error in the command line.

```bash
Traceback (most recent call last):
  File "/usr/bin/bottles", line 56, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 33, in <module>
    from .window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 27, in <module>
    from .backend.manager import Manager
  File "/usr/share/bottles/bottles/backend/manager.py", line 42, in <module>
    from .dependency import DependencyManager
  File "/usr/share/bottles/bottles/backend/dependency.py", line 22, in <module>
    import patoolib
ModuleNotFoundError: No module named 'patoolib'
```

**Installation**
 - AUR (last updates e.g. 2022.1.14-2 (update from 16.01.2022))

**To Reproduce**
 - run using 'bottles' in via command line

**Expected behavior**
 - starting the GUI

**Desktop (please complete the following information):**
 - Manjaro
 - Kernel 5.15.12
 - MATE 1.26.0

**Comment by mirkobrombin** [comment] 2022-01-16 19:49
Duplicate of https://github.com/bottlesdevs/Bottles/issues/768

**Closed by mirkobrombin** 2022-01-16 19:49 UTC
Labels: bug
