### ISSUE TITLE
[Bug]:Vaniglia runner list is displayed inside the Lutris runner list

### ISSUE THREAD

**Issue by Sblash** [bottlesdevs/Bottles#1854] opened 2022-07-27 22:03 UTC
### Describe the bug

Vaniglia runner list is always empty because is merged in the Lutris runner list
![image](https://user-images.githubusercontent.com/29551138/181380306-cebf38b0-7441-457e-87b6-df7693798a0e.png)

### To Reproduce

1. at the Bottles's main page, go to preferences
2. select "runners" tab
3. try to open Vaniglia section
4. now explore the Lutris section, at the bottom you will find all vaniglia runner

### Package

Flatpak from Flathub

### Distribution

Manjaro Linux 21.3.0

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.50-1-MANJARO
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8346120192
    Free: 8345964544
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.5GiB
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpyinfo: true
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment] 2022-07-27 22:09
Duplicate of #1791

**Closed by mirkobrombin** 2022-07-27 22:09 UTC

**Comment by Sblash** [comment] 2022-07-27 22:18
Ops, sorry for duplication, i did't see it.
Pardon :pray:
