### ISSUE TITLE
[Crash report]  'CSDVersion'  | on a fresh installation | no runners or installers touched

### ISSUE THREAD

**Issue by neod3v** [bottlesdevs/Bottles#2065] opened 2022-09-15 00:19 UTC
i was trying to install all dependencies in a bottle and after a while everything just hang, i closed and opened Bottles just to be met with the following crash report.

**Details**
* **package**: Flatpak
* **version**: 2022.8.28-brescia-2

**Log**

EDIT:
it fails and hangs on installation of the following dependancy:
```yaml
Name: mdac28
Description: Microsoft Data Access Components 2.8 SP1
Provider: Microsoft
License: Microsoft EULA
License_url:
Dependencies: []
Steps:
- action: set_windows
  version: win98

- action: override_dll
  bundle:
    - value: odbccp32
      data: native,builtin
    - value: mtxdm
      data: native,builtin
    - value: odbc32
      data: native,builtin
    - value: oledb32
      data: native,builtin

- action: install_exe
  file_name: MDAC_TYP.EXE
  url: https://web.archive.org/web/20070127061938/https://download.microsoft.com/download/4/a/a/4aafff19-9d21-4d35-ae81-02c48dcbbbff/MDAC_TYP.EXE
  file_checksum: 6e914a7391c3b17380ce54fd3a7a133d
  arguments: /q /C:"setup /qnt"
```

This crash report was generated by Bottles.
```python3
'CSDVersion'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/views/bottle_dependencies.py", line 81, in process_queue
    self.manager.dependency_manager.install(self.config, d)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 144, in install
    res = self.__perform_steps(config, step)

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 286, in __perform_steps
    self.__step_set_windows(

  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 675, in __step_set_windows
    rk.set_windows(step.get("version"))

  File "/app/share/bottles/bottles/backend/wine/regkeys.py", line 125, in set_windows
    "data": win_versions.get(version)["CSDVersion"]

```

**Comment by mirkobrombin** [comment] 2022-09-15 10:43
duplicate of #2064

**Closed by mirkobrombin** 2022-09-15 10:43 UTC
