### ISSUE TITLE
[Crash report] 

### ISSUE THREAD

**Issue by kaostornado** [bottlesdevs/Bottles#421] opened 2021-07-31 19:35 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak

**Log**
```python3
[Errno 2] No such file or directory: 'iTunes64Setup.exe'  File "/app/share/bottles/bottles/utils.py", line 235, in target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/runner_utilities.py", line 240, in run_command
    return subprocess.Popen(

  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

```

**Comment by mirkobrombin** [comment] 2021-07-31 20:50
Duplicate of #420

**Closed by mirkobrombin** 2021-07-31 20:50 UTC
