### ISSUE TITLE
[Bug]: Run installer from a mounted iso file

### ISSUE THREAD

**Issue by yosef406** [bottlesdevs/Bottles#2028] opened 2022-09-04 12:48 UTC
### Describe the bug

try to run  a setup.exe from a mounted ISO file, 
the setup requires the use of a few .bin files,
when running the .exe file from the bottle, the setup starts normally to the point that it needs to read the .bin files,
then the installer throws an error that the .bin files are missing from  `E:\run\user\1000\82af0f84\fg-10.bin`,
in  `\run\user\1000\doc\82af0f84\fg-10.bin` directory there is a setup.exe file that runs the same installer,
i think that bottles copied the installer to this directory, the problem is that it only copied the setup.exe and not the rest of the files (the .bin files)

### To Reproduce

1. mount a ISO drive file that has a setup.exe that depends on more files in the same ISO image
2. attempt to run the setup.exe from a bottle to install the program
3. go threw the installation process 

### Package

Flatpak from Flathub

### Distribution

ubuntu 22.04

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-47-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16783466496
    Free: 16783306752
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.7GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

I don't know

### Additional context

1. when doing the same thing from a folder on the desktop the same problem happens
 (in that i mean i copied the files from the mounted ISO image to the desktop).
3. when installing a single setup.exe file the installation is successful.

**Comment by mirkobrombin** [comment] 2022-09-04 20:17
duplicate of #959

**Closed by mirkobrombin** 2022-09-04 20:17 UTC

**Comment by yosef406** [comment] 2022-09-05 05:44
sorry but i think that this is not the same problem as issue #959, it is similar in the title but not the actual problem 
i will edit the title and the issue to better represent the problem

**Comment by yosef406** [comment] 2022-09-05 06:10
Work Around: 
1. in the bottle press the `three dots at the top -> Brows Files...` 
2. copy the contents of the installer folder 
3. back in the bottle `Details & Utilities -> Legacy Wine Tools -> Explorer` find the file you copied
4. run the installer (setup.exe) by double pressing 
5. now you can delete the file you copied.
