### ISSUE TITLE
[Crash report]  cabextract utility not found, 

### ISSUE THREAD

**Issue by billydodd** [bottlesdevs/Bottles#748] opened 2021-11-26 14:29 UTC
_This_ crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.11.14-treviso

**Log**
```python3
cabextract utility not found, please install to use dependencies which need this feature
```

**Comment by pietrodicaprio** [comment] 2021-11-26 14:36
Duplicate of #566

**Closed by pietrodicaprio** 2021-11-26 14:36 UTC
