### ISSUE TITLE
[Bug]: Empty library items

### ISSUE THREAD

**Issue by alsoLut** [bottlesdevs/Bottles#2511] opened 2023-01-10 17:36 UTC
### Describe the bug

Also, no way to delete those items.

See image below.

![Screenshot from 2023-01-10 19-31-16](https://user-images.githubusercontent.com/14846129/211621661-e4c2fd07-ccc5-4b69-8745-52b7283a445b.png)

### To Reproduce

1.  does not apply

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.1 LTS

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-57-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8353746944
    Free: 8353583104
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.3GiB
Bottles_envs: null
```

**Comment by mirkobrombin** [comment] 2023-01-10 19:57
duplicate of #2458

**Closed by mirkobrombin** 2023-01-10 19:57 UTC

**Comment by alsoLut** [comment] 2023-01-10 20:04
are you sure it's the same thing ? my problem is that I can't interact with those items, can't open or delete them. I don't even know how they got there in the first place.

**Comment by MrQuerter** [comment] 2023-01-10 22:40
Yes, it's not the same thing, but probably also a duplicate: https://github.com/bottlesdevs/Bottles/issues/2490

My bet is that it's some programs that you added from a bottle that was either deleted or renamed.
You can see what those programs were if you go to `/home/yourusernamehere/.var/app/com.usebottles.bottles/data/bottles` and open library.yml
Actually it would be good if you posted this file here as .txt file or as a code because I remember seeing a report that also had a broken library and was causing a weird bug. You can replace your username and program names if you need to.

**Comment by mirkobrombin** [comment] 2023-01-11 09:10
Can you try to launch bottles from your terminal and then post the output?
