### ISSUE TITLE
Suggestion: Request a takedown for unofficial outdated packages

### ISSUE THREAD

**Issue by orowith2os** [bottlesdevs/Bottles#2345] opened 2022-12-04 06:39 UTC
I'm making this issue as I've noticed that Fedora currently has Bottles in their repo, and it's outdated (the latest build provided is from July, iirc). I believe that it would be useful for Bottles to notify and ask distributions that are still shipping Bottles to potentially take down their packages in the event they're not maintained anymore, or to mark them as unofficial in some way otherwise.

Alternatively, Bottles can add a check for whether or not it's in Flatpak and use that to notify the end user, but I don't think that would be taken well, and would most likely end up be disabled by package maintainers.

**Comment by orowith2os** [comment] 2022-12-04 18:30
yeah, I know not much can be done (especially considering the GPL license), just thought I'd bring up the topic to find some potential solutions

I'm not sure on what channels I should use to ask Fedora about potentially removing the package, bleh

**Comment by TheEvilSkeleton** [comment] 2022-12-08 21:47
They can be contacted via email: https://packages.fedoraproject.org/pkgs/bottles/bottles/

**Comment by TheEvilSkeleton** [comment] 2023-01-06 15:49
I'll reopen this issue then.

**Comment by penguinpee** [comment] 2023-01-11 10:22
Thanks for your mail @orowith2os. I opened a [Bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2160007) in order to discuss with the co-maintainers.

I hope to report back soon.

**Comment by penguinpee** [comment] 2023-01-24 00:14
I/we decided to retire Bottles in Fedora. I will initiate the process sometime this week. This means Fedora 38 will be the first release to no longer offer Bottles. Fedora 36 and 37 will go EOL in six and twelve months, respectively.
I'll see if I can add some notification to the packages in F36 and F37 to let users know, that Bottles will no longer receive updates and that they should switch to the Flatpak release.

**Comment by orowith2os** [comment] 2023-01-27 18:24
Thanks for retiring the package. Now, what should we do for the other packages? The distribution packages I have in mind are:

- AUR/Arch
- Ubuntu, if any
- Void Linux, if any
- NixOS? Nix probably won't have dependency issues, imo Bottles could work with the Nix package to make it official, if nixpkgs will cater to Bottles' dev cycle.
- Gentoo, if any

**Comment by TheEvilSkeleton** [comment] 2023-01-27 18:36
IMO, there's no problem with NixOS, as they don't use an inferior package manager. Besides, the users are already experienced, so they know where to report, so I rather not inconvenience people that already do everything right.

Void should be fine too, as the users are generally experienced as well. Same with Gentoo.

I feel a bit conflicted with the AUR, as Arch users are typically experienced, so there's nothing really wrong there. However, unfortunately, Manjaro makes the AUR really discoverable, which can be a huge problem, as Manjaro users are often not experienced with Linux.

I can't find any package on Ubuntu, maybe I can't really figure out how to use their search.

**Comment by Kinsteen** [comment] 2023-01-27 18:37
AUR is still maintained, and is still very popular (93rd in popularity in the AUR). Also, we don't have a lot of issues that are specific to the AUR, I'm not even sure we had one in the last couple months (the time I was active in this project).

I vote to not take down the AUR in my opinion!

**Comment by TheEvilSkeleton** [comment] 2023-01-27 18:43
> we don't have a lot of issues that are specific to the AUR

The main issue is the lack of control over packages and dependencies. We used to use an unreleased version of libadwaita to use the newer widgets, as the ones on stable weren't enough for our need. We later stopped supporting the AUR because it does not give us enough control over dependencies - the only workaround was to use libadwaita-git from the AUR, which is extremely stupid to use bleeding edge libraries on host. We might do something similar in the future as well.

> EDIT: Manjaro is a problem, but as I said, we haven't had any report (in the last couple months) that were specific to Arch/Manjaro...

Newcomers are often inexperienced with the FOSS model, as they don't know how and where to report bugs. Not having any reports does not necessarily mean people running such package isn't running into issues. So we'll have to take that into account too.

**Comment by penguinpee** [comment] 2023-02-25 11:52
> I/we decided to retire Bottles in Fedora. I will initiate the process sometime this week. This means Fedora 38 will be the first release to no longer offer Bottles. Fedora 36 and 37 will go EOL in six and twelve months, respectively. I'll see if I can add some notification to the packages in F36 and F37 to let users know, that Bottles will no longer receive updates and that they should switch to the Flatpak release.

There has been some development regarding this request. As per Fedora Packaging Guidelines I [announced](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/VJNMRCJBEBYDPA6P3HTUCNCYRY5HOYTX/#KZZC235WSSGU2RXFHJOBVJI7PTBTF2TJ) the intention to retire the package in F38 on the devel mailing list.
The responses made us re-evaluate our decision and we decided to give it another go.

The plan is now to have Bottles updated to the latest [^1] release to ship with F38. For that we need to have python-orjson packaged for Fedora. That's currently being worked on by the Rust SIG.

Should we not make enough progress, despite the interest in keeping Bottles in the Fedora repos, then I will orphan it before F39 gets branched. Orphaning means other maintainers can adopt the package. That's mostly a procedural/administrative difference to retirement, since packages can also be unretired.

Let me know if you have any questions.

[^1]: Which release is being shipped with F38 depends very much on the latest release available before F38 enters freeze. But the intention is to follow the upstream release cycle as closely as possible.

**Comment by orowith2os** [comment] 2023-03-03 01:14
@penguinpee thanks for announcing Fedora's intent to give packaging another shot, but I'm going to have to strongly suggest against it, mainly due to many of the issues that have been encountered with native packages (outside of updates not being in-sync, dependency hell is a large one) and Bottles' support capabilities and decisions. Please send my comments to the mailing lists, as I don't like interacting with mailing lists in general 😅

**Comment by mirkobrombin** [comment] 2023-03-03 07:04
Hi @penguinpee, thank you for your update. However, after considering the matter, I would suggest against updating Bottles to the latest version and including it in the F38 release.

As you may know, Bottles has several dependencies that need to be packed in the Fedora repositories and maintained, like [FVS](https://github.com/mirkobrombin/FVS), with all its dependencies like the [orjson](https://github.com/ijl/orjson) you mentioned, and there will probably be more in the future as the project is always changing. Some features in Bottles can work without some dependencies, but in a poor or broken way. For example, [libyaml](https://github.com/yaml/libyaml), as Bottles has a large dependency on yaml, we use that library to gain more performance.

Using Flatpak gives us more freedom because we don't have to worry about other package formats, and can add or change dependencies at any time to support new features, providing a better user experience, or address any issues that arise. However, this could increase the workload for both of us since we would need to stay in touch to communicate these changes and you would have to act accordingly. Additionally, some dependencies may be custom-made for Bottles, as was the case with FVS, which means that you would also have to package and maintain those dependencies. I wouldn't want this to become a nightmare for you to maintain, or damage our project's image (despite all your good intentions).

Moreover, it's worth considering that Bottles no longer has a fixed release schedule, and new releases could occur unexpectedly. This means that any changes or updates to dependencies would also need to be made on a rolling basis, which could be challenging to keep up with.

There is also another problem that we should consider: wine can be a hole in the system security, exposing the user' s data. Running Bottles as a flatpak prevents some of the risks. We are developing an in-app sandbox based on bwrap, but that will take some time and is still experimental.

Lastly, I would like to point out that there are many users online complaining about Bottles because the Fedora package was broken. This could damage the project's reputation, and I do not want to point fingers at the maintainer.

Therefore, I would recommend continuing to have Bottles removed from the Fedora repositories. Thank you for your attention to this matter.

**Comment by TheEvilSkeleton** [comment] 2023-06-02 20:33
I'm sorry for coming off as abrasive, but I've genuinely lost my patience over the whole situation.

To be clear, we're not denying that some users prefer RPMs over Flatpak. However, that isn't enough for us to be comfortable with supporting a downstream RPM to some extent.

Most of the bug reports we got from users of the Fedora package were due to Fedora packaging/dependencies issues. One of my friends trashed Bottles when they tried the RPM, but absolutely adored it once I asked them to try the flatpak. The RPM also [prevented a YouTuber from making a video about Bottles](https://fosstodon.org/@thelinuxcast/109831741489032496).

Bottles requires a consistent and predictable environment, which is not something that most traditional packaging systems, such as RPM, provide. No matter the distro, Flatpak provides identical environments, which is something we absolutely need to troubleshoot bugs, especially with Wine.

It isn't helpful to tell us we can work with downstream. All of us have other projects to work on and are generally busy, so putting in the effort to assist with downstream packaging isn't feasible. Multiply that with the amount of package formats and distros out there, it only gets exponentially more repetitive for us (but not for you).

It's hard for us to be aware of issues due to downstream packaging. In the example I provided above, we were really lucky for being aware of it, only because we were pinged. Additionally, the user assumed that the issue was within Bottles itself, rather than with the downstream packaging. Since Fedora is such a large and reputable distro, users are more inclined to believe that the issue resides in the smaller, upstream project. The reputational damage from the event is real, and unfairly affects us. While it may have been an exception, in the end, Mirko wasted his time supporting the person regardless, *even when we were not at fault at all*. This is not "distributing the load"; it's wasted valuable time which could have been used to work on actual issues within Bottles or other projects. This unnecessary effort could have been easily prevented, by simply respecting our wishes as an upstream. Even if we referred them to Bugzilla or Fedora Discussion, it would have still wasted our time. The "issue of the past" is _not_ an issue of the past; it's an issue that left us a bad taste over maintenance at Fedora — to put it nicely.

I cannot use mailing lists. As a person who has difficulties with communicating and writing, not being able to edit messages/comments is a deal breaker. Even then, I attempted to participate a while ago in that thread you linked. My message wasn't sent and I was forced to subscribe, losing the 30 minutes I took writing out a response. I shouldn't be forced to subscribe to something for no reason, and I don't have the additional time to manage these emails, especially when I'll get spammed every 10 seconds.

In the end, Bottles is FOSS, and you are legally allowed to redistribute our software however you see fit. We've already listed various technical and personal reasons of why this method of packaging isn't fit for an app like Bottles. It seems to me that it's a disservice to upstream and your own users to continue to package a complex app, only to have it continuously break and waste our time. An apology does not suffice when you repeatedly make the same mistakes without learning anything from it.

Once again, I apologize for coming out as abrasive. I sincerely appreciate that you put in the time to participate in this thread and even initiated retiring the package, but it doesn't and cannot fix the fundamental issues.

**Comment by orowith2os** [comment] 2023-06-16 00:43
Fedora still intends to package Bottles in Fedora 38.

I will make a comment about this on their bugzilla later.

**Comment by MyFedora** [comment] 2023-08-15 18:05
Perhaps fork Bottles and rebrand it? @penguinpee

I think it's obvious from this conversation that 3rd-party packages:
- Create more work for volunteers who _explicitly_ don't want more work.
- Stumble on bugs that nobody that uses the official distribution cares about, except packagers.
- Damage the reputation when the packages are abandoned, broken, outdated, etc.

You can solve all of the above if you choose to fork and rebrand. I believe that's the only morally acceptable solution, unless you can accept that:
- You create work for volunteers who don't want more work.
- You report bugs that nobody who uses the official distribution cares about.
- You damage the reputation when your package is abandoned, broken, outdated, etc.

I want to make it very clear that you're doing a disservice to many people here, only for the benefit of a handful of Fedora users excluding myself that prefer RPM to Flatpak on a Linux distro made by a company that made and promotes the use of Flatpak in that very Linux distro.

I can't stress enough that you force volunteers to support the fallout of your package's shortcomings. People and humans with real identities and real history, who choose to dedicate their precious free time on an awesome project, not thankless support work. Don't be that douche boss that rejects every QoL suggestion from your employees, only to shove more work on them. Please respect their boundaries and mental health.

I chose very harsh words here, but I find the blatant disregard of the input by the people whose software you package and the impact of your package on others concerning, to say the least.

**Comment by DemiMarie** [comment] 2023-09-24 18:05
> In the end, Bottles is FOSS, and you are legally allowed to redistribute our software however you see fit. We've already listed various technical and personal reasons of why this method of packaging isn't fit for an app like Bottles. It seems to me that it's a disservice to upstream and your own users to continue to package a complex app, only to have it continuously break and waste our time. An apology does not suffice when you repeatedly make the same mistakes without learning anything from it.

I’m not sure if this has already been considered, but one option might be to trademark the name “Bottles” and the Bottles branding, and use trademark law to forbid people from using the Bottles name and branding without permission.  This is the same strategy used by many FOSS products and projects, including Red Hat Enterprise Linux, GrapheneOS, OpenJDK, Firefox, Thunderbird, and Dasharo.  My understanding is that trademarks are not considered a threat to software freedom so long as the trademarks can easily be replaced during the build, which is the case for at least RHEL, Firefox, and Thunderbird.

**Comment by mirkobrombin** [comment] 2023-09-25 08:06
I am aware that in this message, I will use an uncomfortable "tone" that may come across as arrogant, and I apologize in advance.

I believe this discussion is coming to its conclusion. At Bottles, we do not wish to support third-party packages, nor do we want to be implicated if there are issues caused by these packages.

As the maintainer of the Bottles project and the founder of the company fabricators.ltd, which is the current distributor of the product, it is both my interest and duty to preserve the product's image and ensure it is not "tarnished" by packaging errors or, to put it simply, the inadequacy of third parties. Bottles is not only a project associated with my company but also supported by a large community that, for obvious reasons, should not suffer from problems caused by factors beyond our control. They might lose interest in supporting the project if they find themselves in a hostile environment that is, again, beyond our control.

Bottles is an open-source project, and I am aware that it is in the spirit of open source to redistribute applications. However, this should happen outside the project's name, without causing issues to the project itself, and taking responsibility for one's actions. This means giving users of that package the ability to submit bug reports on a platform dedicated to that package and managing bug resolution independently, only involving Bottles when it's not a packaging-related bug.

This process is the most accurate but also the most resource-intensive in terms of effort and resources. I understand that it is not feasible to allocate one or more people to each packaging format in which Bottles is distributed, but it is the price to pay for offering a quality product to our users on Fedora, Ubuntu, and Arch.

In the Linux world, there are many distributions, each with its own packages and software versions, and we cannot guarantee that all of them will respect our takedown request. For this reason, I have decided to take more proactive measures that may address the problem at its root. In the coming weeks, we will modify Bottles to alert the user if it has been provided through unofficial means, displaying an alert in the user interface. Support links will be disabled, and the software version will be obscured unless the maintainer includes a file with all the necessary parameters, such as the package version and support link, along with the package. These parameters will be discussed in the coming weeks, and we will provide documentation on the matter. Bottles offers an integrated health check, which verifies the presence of critical dependencies. This will continue to function but will expand its search scope to ensure these dependencies meet the minimum required version, displaying an alert otherwise.

Additionally, in the coming weeks, we will remove the bottles package currently available in the AUR repository, even though it is unofficial but supported by me and Francesco as separate entities from the Bottles project. This is to prevent any confusion associating that package with the Bottles project itself.

I regret to say that in the event of the removal of these controls or falsification of the product's identity (e.g., passing off the app as the official version), we will consider implementing restrictions on Bottles repositories for unofficial packages. These repositories provide dependencies, components, and runners (wine engines).

**Comment by penguinpee** [comment] 2023-09-26 21:43
> Bottles is an open-source project, and I am aware that it is in the spirit of open source to redistribute applications. However, this should happen outside the project's name, without causing issues to the project itself, and taking responsibility for one's actions. This means giving users of that package the ability to submit bug reports on a platform dedicated to that package and managing bug resolution independently, only involving Bottles when it's not a packaging-related bug.

This sounds a bit like [what I was suggesting](https://github.com/bottlesdevs/Bottles/issues/2345#issuecomment-1572975228) when I offered to send users of the Fedora package over to our Bugzilla:

> Should you receive bug reports from Fedora users for the current or future releases, you could either send them to [Bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?component=bottles&product=Fedora), where package maintainers will be notified and can trial the bug (e.g. trying to reproduce it using the Flatpak version) _or_ put a label on the issue (e.g. _Fedora_), so package maintainers can look into it, saving upstream some time.

**Comment by TheEvilSkeleton** [comment] 2023-09-27 10:01
Right, and I am against that because you're using an inaccessible platform that is intentionally difficult for normal users to use. Emails aren't something that people want to use to report bugs either.

You still haven't addressed anything I said here https://github.com/bottlesdevs/Bottles/issues/2345#issuecomment-1574284415

At this point, is it even worth keeping this issue open? It's clear the packagers will continue to make our lives difficult just to make their 2 users happy.

> This will continue to function but will expand its search scope to ensure these dependencies meet the minimum required version, displaying an alert otherwise.

> Additionally, in the coming weeks, we will remove the bottles package currently available in the AUR repository, even though it is unofficial but supported by me and Francesco as separate entities from the Bottles project. This is to prevent any confusion associating that package with the Bottles project itself.

> I regret to say that in the event of the removal of these controls or falsification of the product's identity (e.g., passing off the app as the official version), we will consider implementing restrictions on Bottles repositories for unofficial packages. These repositories provide dependencies, components, and runners (wine engines).

@mirkobrombin Yeah, we should go with those. Just keep in mind that I'm burnt out from maintaining this project, and am not in a good position to review code, but it's something I'd like to visit in the future.

**Comment by penguinpee** [comment] 2023-09-27 10:47
> Right, and I am against that because you're using an inaccessible platform that is unnecessarily difficult for normal users to use. Emails aren't something that people want to use to report bugs either. It still doesn't address anything I said here [#2345 (comment)](https://github.com/bottlesdevs/Bottles/issues/2345#issuecomment-1574284415) -- Frankly, Mirko was being too nice, but I disagree with him here.

Well, what's there to say. It didn't sound like you were offering something to make this work for both parties. How do you define "normal users" and "difficult". I'm aware Bugzilla might not be the most fancy tool for bug reporting. Neither are the forges in my opinion, albeit they make it a little easier, more configurable.

And users will be users. They use whatever platform they can lay their hands on to vent their disappointment, frustration and what not.

> It isn't helpful to tell us we can work with downstream. All of us have other projects to work on and are generally busy, so putting in the effort to assist with downstream packaging isn't feasible. Multiply that with the amount of package formats and distros out there, it only gets exponentially more repetitive for us (but not for you).

How about some documentation on building the package according to your standards? A complete list of runtime dependencies would also be very helpful. Saves us packagers from having to trial and error that and saves users running into issues when a dependency is missing. They get a stack trace now. Not the most friendly way of handling a missing dependency.

> I cannot use mailing lists. As a person who has difficulties with communicating and writing, not being able to edit messages/comments is a deal breaker.

Would Discourse be an option? It allows editing.

> In the end, Bottles is FOSS, and you are legally allowed to redistribute our software however you see fit. We've already listed various technical and personal reasons of why this method of packaging isn't fit for an app like Bottles. It seems to me that it's a disservice to upstream and your own users to continue to package a complex app, only to have it continuously break and waste our time. An apology does not suffice when you repeatedly make the same mistakes without learning anything from it.

The packaging process quite often is a community effort. We try our best to offer stable and usable packages. But life happens to all of us and people move on. I hadn't been involved in Bottles around the time the YouTube incident happened. I took up Bottles maintenance after that.

> I regret to say that in the event of the removal of these controls or falsification of the product's identity (e.g., passing off the app as the official version), we will consider implementing restrictions on Bottles repositories for unofficial packages. These repositories provide dependencies, components, and runners (wine engines).

I think it's clear by now that I do not agree with the direction Bottles is moving towards. But, hey, it's your baby. You can do whatever you please.

However, the above sounds to me like it's one step short of moving to a restrictive none FOSS license. But, seeing that most of you are involved in open source in some way or another, I'm sure you are aware that doing so would close the doors for your audience.

**Comment by mirkobrombin** [comment] 2023-09-27 12:35
> However, the above sounds to me like it's one step short of moving to a restrictive none FOSS license. But, seeing that most of you are involved in open source in some way or another, I'm sure you are aware that doing so would close the doors for your audience.

If my intention was to go in that direction (and it is not), I would have done it already 6 years ago when I created the project.

I cannot teach you to interpret my words as I intend them, but I believe it is obvious that you are misconstruing them. There is not much else to discuss; let me summarize: you can continue to offer the package, but soon Bottles will notify the user that this is not the official method, and it will do so clearly in the graphical interface, perhaps on the About screen. Version and support links will also be hidden and will need to be redefined by the package maintainer, so they will exist only if you define them with your details (for example, I can see a version 56-5, where 5 is a hypothetical internal version or patch by you).

Among other things, Bottles' health check will be expanded, so it will show you clearly which dependencies are at the wrong version; it seems to me that I am doing you a favor rather than harm.

The matter of taking down the repositories is something that will ONLY happen IF maintainers promote their version of the package as official, mitigate all issues to the Bottles team, and let's be clear, it seems to me the most reasonable thing to do, after all, we are the ones paying for the traffic of those repositories.

If you think my tone is arrogant or that I want to go in a proprietary direction, you are mistaken and misinterpreting my words. I think this is a great compromise for everyone: follow the rules, and we will all be happy. If you don't follow them, you must take responsibility, which includes maintaining the repositories yourselves and paying for their maintenance.

**Closed** 2023-09-27 12:50 UTC
Labels: Feedback

**Comment by orowith2os** [comment] 2023-09-27 16:10
Also changing this issue title, at is no longer a suggestion.
