### ISSUE TITLE
[Crash report]  'NoneType' object has no att

### ISSUE THREAD

**Issue by frequency403** [bottlesdevs/Bottles#1413] opened 2022-05-03 07:06 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.4.28

**Log**
```python3
'NoneType' object has no attribute 'encoding'  File "/app/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/widgets/program.py", line 185, in _run
    WineExecutor(

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 132, in run
    return self.__launch_with_bridge()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 151, in __launch_with_bridge
    return self.__launch_with_starter()

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 214, in __launch_with_starter
    res = start.run(

  File "/app/share/bottles/bottles/backend/wine/start.py", line 35, in run
    self.launch(

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 51, in launch
    res = WineCommand(

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 472, in run
    enc = detect_encoding(res)

  File "/app/share/bottles/bottles/backend/utils/generic.py", line 43, in detect_encoding
    sys.stdout.encoding,

```

**Comment by mirkobrombin** [comment] 2022-05-03 08:00
duplicate of #1395

**Closed by mirkobrombin** 2022-05-03 08:00 UTC
