### ISSUE TITLE
[Bug]: windows apps crash when using gnome 3 finger gestures

### ISSUE THREAD

**Issue by allaeddineomc** [bottlesdevs/Bottles#2512] opened 2023-01-10 20:29 UTC
### Describe the bug

when a windows app is in focus and the user starts a 3 finger gesture on gnome the app will crash , reproducible on both gnome 42 and 43 on wayland , not tested on xorg or other gnome versions

### To Reproduce

run any app
swipe with 3 fingers to any direction

### Package

Flatpak from Flathub

### Distribution

fedora silverblue 37

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.17-300.fc37.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4102111232
    Free: 4101951488
RAM:
    MemTotal: 7.6GiB
    MemAvailable: 2.6GiB
Bottles_envs: null
```

### Additional context

entering the overview using the super(meta/windows) button doesn't crash apps

**Comment by mirkobrombin** [comment] 2023-01-10 21:00
duplicate of https://github.com/bottlesdevs/wine/issues/41

**Closed by mirkobrombin** 2023-01-10 21:00 UTC
