### ISSUE TITLE
[BUG] expanding menus do not expand unless you go to another tab and back

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1189] opened 2022-03-15 03:35 UTC
flatpak 2022.3.14-trento-3

when inside a bottle Preferences > System section and click "Components version" it always expand to 1 milometer. I need to go to another tab like Dependencies or Programs then click back to Preferences and it is expanded properly.

ideally the components version would expand properly the first time. 

this also happens to Preferences > Display settings. I need to click "Display settings" to expand  but it only shows the arrow downward but not actually expand. I click to another section like Installers or versioning and go back and it is properly expanded.

I do not know if other areas have "expanding" menus but I am guess they have the same issue as these two above.

**Comment by mirkobrombin** [comment] 2022-03-15 06:50
Duplicate of https://github.com/bottlesdevs/Bottles/issues/1116

**Closed by mirkobrombin** 2022-03-15 06:50 UTC
Labels: bug
