### ISSUE TITLE
[Crash report]  one of the hex, bytes, byt

### ISSUE THREAD

**Issue by AlexandreNochi** [bottlesdevs/Bottles#1782] opened 2022-07-15 04:05 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.7.14-brescia-1

**Log**
```python3
one of the hex, bytes, bytes_le, fields, or int arguments must be given  File "/app/share/bottles/bottles/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/window.py", line 234, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 133, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 190, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 813, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 745, in process_bottle
    uuid.UUID(k)

  File "/usr/lib/python3.9/uuid.py", line 171, in __init__
    raise TypeError('one of the hex, bytes, bytes_le, fields, '

```

**Comment by mirkobrombin** [comment] 2022-07-15 05:52
Duplicate of  #1774

**Closed by mirkobrombin** 2022-07-15 05:52 UTC
