### ISSUE TITLE
[Crash report]  every time I open bottles it hangs

### ISSUE THREAD

**Issue by totoLab** [bottlesdevs/Bottles#1331] opened 2022-04-16 14:11 UTC
After running in terminal the commnad "bottles":

(15:44:53) WARNING Connection status: offline … 
(15:44:53) INFO Bottles Started! 
(15:46:58) ERROR Could not get index for dependencies repository 
(15:51:17) ERROR Could not get index for installers repository 
(15:53:27) ERROR Cannot fetch components repository index. 
(15:53:27) INFO Performing Bottles checks... 
(15:53:27) INFO Dxvks found:
	 - dxvk-1.10.1
 
(15:53:27) INFO Vkd3ds found:
	 - vkd3d-proton-2.6
 
(15:53:27) INFO Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
(15:53:27) INFO Latencyflexs found:
	 - latencyflex-v0.1.0
 
(15:53:27) INFO Runners found:
	 - sys-wine-7.6
	 - caffe-7.5
 
(15:53:27) ERROR Error while running async job: <function MainWindow.__on_start.<locals>.get_manaher at 0x7f1ec5006d40>

Then the second time it gave this: 

This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2022.4.14-trento-1

**Log**
```python3
  File "/usr/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/window.py", line 265, in get_manaher
    mng = Manager(window)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 116, in __init__
    self.checks(install_latest=False, first_run=True)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 132, in checks
    self.organize_components()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 234, in organize_components
    or self.winebridge_available[0] != next(iter(self.supported_winebridge)):

```

EDIT: bottles was installed from AUR on Arch vanilla

**Comment by mirkobrombin** [comment] 2022-04-16 14:48
This issue has been reported before but no one on the team has been able to replicate. I'm going to remove the automatic-download for winebridge.

duplicate of #1220

**Closed by mirkobrombin** 2022-04-16 14:49 UTC
