### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by eson57** [bottlesdevs/Bottles#258] opened 2021-05-05 14:13 UTC
**Describe the bug**
Swedish translation do not work

**Installation**
 - Method: Flatpak
 - Version 3.1.7

Launch Bottles

**Expected behavior**
App gui in Swedish

**Desktop : Cinnamon
 - OS: Linux Mint
 - Version 20.1

**Comment by mirkobrombin** [comment] 2021-05-05 15:54
Duplicate of #174 
I close the discussion as it is the same problem as a previous issue. Comment them in case you have more details.

**Closed by mirkobrombin** 2021-05-05 15:54 UTC
Labels: duplicate
