### ISSUE TITLE
[Crash report]  'NoneType' object is not sub

### ISSUE THREAD

**Issue by daPharaoh** [bottlesdevs/Bottles#958] opened 2022-01-22 17:06 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.1.14-trento-2

**Log**
```python3
'NoneType' object is not subscriptable  File "/app/share/bottles/bottles/utils.py", line 339, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/installer.py", line 360, in install
    self.__install_dependencies(_config, dependencies, widget)

  File "/app/share/bottles/bottles/backend/installer.py", line 143, in __install_dependencies
    res = self.__manager.dependency_manager.install(_config, _dep)

  File "/app/share/bottles/bottles/backend/dependency.py", line 146, in install
    dependency_category=dependency[1]["Category"]

```

**Comment by mirkobrombin** [comment] 2022-01-22 19:02
Duplicate of #476

**Closed by mirkobrombin** 2022-01-22 19:02 UTC
