### ISSUE TITLE
[Bug]: Adding a program executable should show the open dialogue preset in a relevant location

### ISSUE THREAD

**Issue by nclm** [bottlesdevs/Bottles#1719] opened 2022-07-04 16:26 UTC
### Describe the bug

The + button in “Programs” opens the the file open dialogue in the Linux home folder. It should open the dialogue in the bottle’s Wine filesystem.

### To Reproduce

1. Open a bottle.
2. Go to the “Programs” section
3. Click “+”
4. See your Linux home folder
5. Have no idea how to select an executable from the bottle’s Wine filesystem from there

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.15.0-40-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8323837952
    Free: 8323678208
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.3GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

**Comment by mirkobrombin** [comment] 2022-07-04 17:15
duplicate of https://github.com/bottlesdevs/Bottles/issues/1017

**Closed by mirkobrombin** 2022-07-04 17:15 UTC
