### ISSUE TITLE
[Bug]: Unable to add Steam shortcut

### ISSUE THREAD

**Issue by m3anmug** [bottlesdevs/Bottles#2718] opened 2023-02-23 13:27 UTC
### Describe the bug

SteamManager.add_shortcut() missing 1 required positional argument: 'program_path'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

### To Reproduce

Add to Steam button

### Package

Flatpak from Flathub

### Distribution

Steam Deck

### Debugging Information

```shell
Official Package: true
Version: '51.0'
DE/WM: plasma-steamos-oneshot
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve36-1-neptune
Disk:
    Total: 6183772160
    Free: 6183628800
RAM:
    MemTotal: 11.5GiB
    MemAvailable: 7.7GiB
Bottles_envs: null
```

**Comment by m3anmug** [comment] 2023-02-23 13:29
I have no idea how to properly submit my issue so i did the best i could.

**Comment by TheEvilSkeleton** [comment] 2023-02-23 14:17
No problem. If it helps, I would suggest to read the description of each section when you open an issue. These descriptions generally tell you what they expect you to fill. It's essentially a form that you have to fill.

That being said, this was already reported in https://github.com/bottlesdevs/Bottles/issues/2706, so I'm going to close this issue and continue there.

**Comment by TheEvilSkeleton** [comment] 2023-02-23 14:18
Duplicate of #2706

**Closed by TheEvilSkeleton** 2023-02-23 14:18 UTC
