### ISSUE TITLE
[Bug]: Library Icon missing in KDE

### ISSUE THREAD

**Issue by tazihad** [bottlesdevs/Bottles#2399] opened 2022-12-19 08:32 UTC
### Describe the bug

Library Icons do not show in Fedora KDE. Or Breeze Theme.

### To Reproduce

Install flatpak version of bottles in Fedora KDE

### Package

Flatpak from Flathub

### Distribution

Fedora 37 Kinoite

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.0.12-300.fc37.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4103409664
    Free: 4103241728
RAM:
    MemTotal: 7.6GiB
    MemAvailable: 3.5GiB
Bottles_envs: null
```

### Additional context

![Screenshot_20221219_142950](https://user-images.githubusercontent.com/19417232/208381897-be47aa82-804b-4bb4-955c-34a3b69a0460.png)

**Comment by mirkobrombin** [comment] 2022-12-19 09:31
Duplicate of https://github.com/bottlesdevs/Bottles/issues/1627

Please read this https://github.com/bottlesdevs/Bottles/issues/1627#issuecomment-1156398604

**Closed by mirkobrombin** 2022-12-19 09:31 UTC
