### ISSUE TITLE
[Bug]: Bottles no longer run

### ISSUE THREAD

**Issue by smotim** [bottlesdevs/Bottles#1876] opened 2022-07-31 06:30 UTC
### Describe the bug

The application does not start after loading. I've been using it for a while now, it worked fine. Even reinstalling doesn't help right now
![Снимок экрана от 2022-07-31 11-21-02](https://user-images.githubusercontent.com/57951811/182013052-cdc26155-1d30-4769-9cba-0795db729c4b.png)

### To Reproduce

I don't know what exactly needs to be done. Yesterday I installed the old GOG and the Witcher 3, I also turned on library mode. The app doesn't launch today

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
sorry, I couldn't write. The application does not let you go beyond the loading screen
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Logs from sreenshot
[tim@fedora ~]$ flatpak run com.usebottles.bottles
11:20:29 (INFO) Bottles Started! 
11:20:31 (INFO) Catalog components loaded 
11:20:31 (INFO) Catalog installers loaded 
11:20:31 (INFO) Catalog dependencies loaded 
11:20:31 (INFO) Performing Bottles checks… 
11:20:31 (INFO) Dxvks found:
	 - dxvk-1.10.2
 
11:20:31 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6-1-5b73139
 
11:20:31 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
11:20:31 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
11:20:31 (INFO) Runners found:
	 - sys-wine-7.0
	 - soda-7.0-2
 
11:20:32 (INFO) Bottles found:
	 - __140
 
11:20:32 (INFO) Library saved 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/window.py", line 154, in set_manager
    self.page_library = LibraryView(self)
  File "/app/share/bottles/bottles/views/library.py", line 43, in __init__
    self.update()
  File "/app/share/bottles/bottles/views/library.py", line 56, in update
    entry = LibraryEntry(self, u, e)
  File "/app/share/bottles/bottles/widgets/library.py", line 78, in __init__
    path = ThumbnailManager.get_path(self.config, entry['thumbnail'])
  File "/app/share/bottles/bottles/backend/managers/thumbnail.py", line 32, in get_path
    return ThumbnailManager.__load_grid(config, uri)
  File "/app/share/bottles/bottles/backend/managers/thumbnail.py", line 42, in __load_grid
    bottle_path = ManagerUtils.get_bottle_path(config)
  File "/app/share/bottles/bottles/backend/utils/manager.py", line 86, in get_bottle_path
    if config.get("Environment") == "Steam":
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by mirkobrombin** [comment] 2022-07-31 08:32
Duplicate of #1859

**Closed by mirkobrombin** 2022-07-31 08:32 UTC
