### ISSUE TITLE
[Crash report]  Destination path '/home/USER/Games

### ISSUE THREAD

**Issue by Stefan99353** [bottlesdevs/Bottles#2092] opened 2022-09-20 15:42 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2022.8.28-brescia-2

**Log**
```python3
Destination path '/home/USER/Games/bottles/League-of-Legends/cache/dxvk_state/LeagueClientUxRender.dxvk-cache' already exists  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 204, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 136, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 193, in checks
    self.check_bottles()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 841, in check_bottles
    process_bottle(b)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 830, in process_bottle
    shutil.move(os.path.join(_bottle, c), os.path.join(_bottle, "cache", "dxvk_state"))

  File "/usr/lib/python3.10/shutil.py", line 813, in move
    raise Error("Destination path '%s' already exists" % real_dst)

```

**Comment by mirkobrombin** [comment] 2022-09-20 20:38
duplicate of #2054

**Closed by mirkobrombin** 2022-09-20 20:38 UTC
