### ISSUE TITLE
[Crash report]  'Tlauncher-test'  

### ISSUE THREAD

**Issue by srpitt** [bottlesdevs/Bottles#689] opened 2021-11-04 13:50 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2021.10.28-treviso

**Log**
```python3
'Tlauncher-test'  File "/app/share/bottles/bottles/utils.py", line 298, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 1178, in async_delete_bottle
    del self.local_bottles[config.get("Path")]

```

**Comment by mirkobrombin** [comment] 2021-11-04 14:16
Duplicate of #676

**Closed by mirkobrombin** 2021-11-04 14:16 UTC
