### ISSUE TITLE
[Bug]: Creating a bottle fails installing dependencies

### ISSUE THREAD

**Issue by olafcatsnake** [bottlesdevs/Bottles#3550] opened 2024-11-07 11:40 UTC
### Describe the bug

Creating a new bottle or installing dependencies fails:

Failed to install dependency: Microsoft Arial Font

Download URL for the font might have changed.

### To Reproduce

1. Create a new Bottle

### Package

Flatpak from Flathub

### Distribution

Fedora 41

### Debugging Information

```shell
Official Package: true
Version: '51.15'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-565-57-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.11.6-300.fc41.x86_64
Disk:
    Total: 16783646720
    Free: 16783462400
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 25.9GiB
Bottles_envs: null
```

**Comment by GabsEdits** [comment] 2024-11-07 14:41
Duplicate of https://github.com/bottlesdevs/Bottles/issues/3125

**Closed by GabsEdits** 2024-11-07 14:41 UTC
