### ISSUE TITLE
[Bug]: After latest update no longer dark and looks weird also cannot create bottle

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1801] opened 2022-07-18 16:56 UTC
### Describe the bug

Flatpak 2022.7.14-brescia-3

when i was on 2022.7.14-brescia it looked fine but when i updated to 2022.7.14-brescia-3 today everything looks weird and the menu option for dark mode is  good. I used to have dark mode. I did not change anything besides update bottles flatpak.

I also try to make a new  bottle and waited 30 minute and nothing happened
stuck on:
```
Generating bottle configuration…
Template found, applying…
```

### To Reproduce

1 update to brescia-3 flatpak
2 launch bottles

### Package

Flatpak from Flathub

### Distribution

arch

### Health Check

```shell
Version: 2022.7.14-brescia-3
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.18.11-hardened1-1-hardened
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 4103133001
    Free: 4102013021
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 13.1GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
    icoextract: true
    pefile: true
    markdown: true
    xdpinfo: true
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-07-18 17:00
Sounds like a big duplicate of #1728


I'm able to make new bottles also resetting Bottles. About theming, this is absolutely system related as we don't define anything about theming.

**Closed** 2022-07-18 19:04 UTC
Labels: Waiting response, Not a bug, Can't replicate
