### ISSUE TITLE
[BUG] Failed to load image-missing.png

### ISSUE THREAD

**Issue by pushqrdx** [bottlesdevs/Bottles#230] opened 2021-04-21 03:06 UTC
**Describe the bug**
```
Gtk-Message: 05:04:27.152: Failed to load module "colorreload-gtk-module"
Gtk-Message: 05:04:27.153: Failed to load module "window-decorations-gtk-module"

(bottles:118100): Gtk-WARNING **: 05:04:27.396: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
zsh: abort (core dumped)  ./Bottles.AppImage
```

**Desktop (please complete the following information):**
 - OS: Manjaro (Latest)
 - Version: 3.1.5

**Comment by mirkobrombin** [comment] 2021-04-21 05:32
Please fill the form:
**Describe the bug**
A clear and concise description of what the bug is.

**Installation**
 - Method: [e.g. Appimage, Meson build, other]
 - Version [e.g. 877386d (find this in name file for Appimage)]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 33]

**Additional context**
Add any other context about the problem here.

**Comment by pushqrdx** [comment] 2021-04-21 17:31
@mirkobrombin Sorry, the reason i didn't is that i found a similar bug that was supposed to be fixed so i thought it's the same issue, i am running KDE, and using the AppImage as i don't wanna install from AUR is there anyway to use AppImage here?

**Comment by mirkobrombin** [comment] 2021-04-21 17:58
If you don't want to install it, it makes sense to use the AppImage. Regarding your problem, I think there are some dependencies missing in the recipe.

@hthre7 Do you have any idea?

**Comment by hthre7** [comment] 2021-04-22 10:42
> @hthre7 Do you have any idea?

My initial thought that this issue is similar to #205 , and I think it's not related to appimage itself(I test on manjaro KDE and its running no issues)

**Comment by mirkobrombin** [comment] 2021-04-22 12:02
Duplicate of #205

**Comment by hthre7** [comment] 2021-04-26 07:18
this https://github.com/bottlesdevs/Bottles/issues/231#issuecomment-826467137 is similar to what we see here and considering it using non standard theme (theme don't follow standard), @pushqrdx what theme are you using?

**Comment by pushqrdx** [comment] 2021-04-26 17:19
@hthre7 Breeze and Breeze GTK, just vanilla KDE

**Comment by hthre7** [comment] 2021-04-27 06:07
> @hthre7 Breeze and Breeze GTK, just vanilla KDE

try:
```
update-mime-database $HOME/.local/share/mime
update-desktop-database $HOME/.local/share/applications
update-mime-database /usr/share/mime
```
also you could use appimagelauncher {it will help managing appimage} (https://github.com/TheAssassin/AppImageLauncher/releases)

**Comment by gabrielluz-br** [comment] 2021-04-28 12:31
> > @hthre7 Breeze and Breeze GTK, just vanilla KDE
> 
> try:
> 
> ```
> update-mime-database $HOME/.local/share/mime
> update-desktop-database $HOME/.local/share/applications
> update-mime-database /usr/share/mime
> gtk-update-icon-cache
> ```
> 
> also you could use appimagelauncher {it will help managing appimage} (https://github.com/TheAssassin/AppImageLauncher/releases)
I have the same exact problem

I've tried the solutions above, I now got this message:
```
sudo update-mime-database $HOME/.local/share/mime
sudo update-desktop-database $HOME/.local/share/applications
sudo update-mime-database /usr/share/mime
sudo gtk-update-icon-cache
[sudo] password for supreme: 

Note that '/home/supreme/.local/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
- /usr/local/share/
- /usr/share/
```

I had to use sudo because I was getting permission denied.

**Comment by hthre7** [comment] 2021-04-28 17:57
> sudo gtk-update-icon-cache

are you using kde? the above is for gtk
if so please try `rm ~/.cache/icon-cache.kcache` and report back if that work .
in addition you could try `update-icon-caches /directories/of/icons/you/are/using` (you should use sudo if icons you are using in root)

**Comment by mirkobrombin** [comment] 2021-04-30 05:58
Can you try the latest build?

**Comment by gabrielluz-br** [comment] 2021-04-30 15:05
> 
> 
> > sudo gtk-update-icon-cache
> 
> are you using kde? the above is for gtk
> if so please try `rm ~/.cache/icon-cache.kcache` and report back if that work .
> in addition you could try `update-icon-caches /directories/of/icons/you/are/using` (you should use sudo if icons you are using in root)

I'm actually using Parrot OS with MATE/iceWM installed. Ok. I'll try those things and then the last build.

**Comment by gabrielluz-br** [comment] 2021-04-30 18:55
>  if so please try `rm ~/.cache/icon-cache.kcache` and report back if that work .

WOW
it works!

Removing kcache did the trick!

`rm ~/.cache/icon-cache.kcache`

Now it works. I didn't update the appimage yet. So it's working as of 3.1.6.

**Comment by gabrielluz-br** [comment] 2021-04-30 18:56
I was getting nervous actually. I use Bottles in my workplace and I was having to use VirtualBox instead. You guys are amazing. I hope that solved the problem for the op.

**Comment by gabrielluz-br** [comment] 2021-05-02 19:07
> **Describe the bug**
> 
> ```
> Gtk-Message: 05:04:27.152: Failed to load module "colorreload-gtk-module"
> Gtk-Message: 05:04:27.153: Failed to load module "window-decorations-gtk-module"
> 
> (bottles:118100): Gtk-WARNING **: 05:04:27.396: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> zsh: abort (core dumped)  ./Bottles.AppImage
> ```
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Manjaro (Latest)
> 
>     * Version: 3.1.5

DId you try the solutions above, my friend? It worked for me.

**Comment by pushqrdx** [comment] 2021-05-02 22:52
Unfortunately i still have this problem, i tried latest unstable release (the one built 5h ago) after running
```
update-mime-database ~/.local/share/mime
update-desktop-database ~/.local/share/applications
sudo update-mime-database /usr/share/mime
gtk-update-icon-cache
rm ~/.cache/icon-cache.kcache
```

but i still get 
```
Gtk-Message: 00:49:57.394: Failed to load module "colorreload-gtk-module"
Gtk-Message: 00:49:57.395: Failed to load module "window-decorations-gtk-module"

(bottles:199099): Gtk-WARNING **: 00:49:57.448: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

**Comment by mirkobrombin** [comment] 2021-05-03 07:22
> @mirkobrombin
> Unfortunately i still have this problem, i tried latest unstable release (the one built 5h ago) after running
> 
> ```
> update-mime-database ~/.local/share/mime
> update-desktop-database ~/.local/share/applications
> sudo update-mime-database /usr/share/mime
> gtk-update-icon-cache
> rm ~/.cache/icon-cache.kcache
> ```
> 
> but i still get this crash log... it's incredibly ridiculous for gtk to crash because of missing icons, let alone missing `missing icon`
> 
> ```
> Gtk-Message: 00:49:57.394: Failed to load module "colorreload-gtk-module"
> Gtk-Message: 00:49:57.395: Failed to load module "window-decorations-gtk-module"
> 
> (bottles:199099): Gtk-WARNING **: 00:49:57.448: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Aborted (core dumped)
> ```

Welcome to the fairy world of GTK.
I'm pretty sure it's about the lack of one or more dependencies, I just need to figure out which ones.

**Comment by pushqrdx** [comment] 2021-06-18 22:13
i even distro hopped and this problem still exists for me

**Comment by mirkobrombin** [comment] 2021-06-19 04:40
Unfortunately I haven't been able to replicate the problem in the last 20 builds yet

**Comment by mirkobrombin** [comment] 2021-06-30 06:09
Unfortunately I am unable to replicate the bug in any way. I had this problem many builds ago but it was fixed. Unfortunately, after more than a month, I was unable to replicate it again on Arch Linux, Ubuntu 21.04, elementary 5 and Fedora 34.

I am going to close the issue which I will reopen if other users find the same problem.

**Closed by mirkobrombin** 2021-06-30 06:09 UTC
Labels: bug, can't replicate, help wanted

**Comment by laurentbenaroya** [comment] 2023-09-27 11:55
I solved the problem setting `export XDG_DATA_HOME="$HOME/.local/share:/root/.local/share:/usr/local/share/:/usr/share/"` and `export XDG_DATA_DIRS="$HOME/.local/share:/root/.local/share:/usr/local/share/:/usr/share/"`
