### ISSUE TITLE
[Bug]: 'str' object has no attribute 'Parameters' 

### ISSUE THREAD

**Issue by ALEX5402** [bottlesdevs/Bottles#2908] opened 2023-05-27 18:14 UTC
### Describe the bug

'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk

### To Reproduce

it happens suddenly

### Package

Flatpak from Flathub

### Distribution

garuda linux

### Debugging Information

```shell
i dont have
```

### Troubleshooting Logs

```shell
'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk
```

### Additional context

'str' object has no attribute 'Parameters'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)

  File "/app/share/bottles/bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk

**Comment by RocketRide9** [comment] 2023-06-11 19:51
I found a stable way to reproduce it:

1. Create bottle for games
2. Grab Wings2 v1.4.0 from here http://www.wings2.net/index.php?page=download
3. Open installer in new bottle with `Virtual Desktop` option enabled and install the game
4. `Wings` should appear in `Programs` section
5. Disable `Virtual Desktop` and `VKD3D` in `Launch Options` of `Wings`.
6. Press `Launch with Terminal` in 3 dots menu.
Black window should appear with game itself located in top left corner.
7. Close black window and terminal
8. Open `Launch Options` and then press `Save`
9. Press `Launch with Terminal` again
If nothing happens and play button is replaced with square then close bottles and open again, see error.
If game launches then go to step 7.

**Comment by SeongGino** [comment] 2023-06-25 15:50
Seems like this is the exact problem I've run into as well; just with running games in a bottle, every couple of runs it will just stop, forcing me to close Bottles and reopen where this same traceback pops up.

FWIW I only use "custom" bottles profiles for better control, not sure if this happens across all types of bottles or only to do when dxvk is involved.

Native version from AUR and not Flatpak, in my instance.

**Comment by VortexAcherontic** [comment] 2023-06-29 14:28
I have a similar issue with the flatpak version.

As soon as I hit "Save" in the launch options of an installed game I get this error.
It is also not possible to open up the launch options again after this unless I restart bottles.

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 202, in update_programs
    self.view_bottle.update_programs(config=self.config)
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 287, in update_programs
    raise TypeError("config param need BottleConfig type, but it was %s" % type(config))
TypeError: config param need BottleConfig type, but it was <class 'str'>
```

**Comment by CaptainCoward** [comment] 2023-07-03 21:43
I also found a way to reproduce it. 
I installed Grim Dawn using the GOG Standalone Installer.
After installation just change a launch parameter for example to /x64. Then start the game and nothing will happen. When then closing bottles you'll get the same error message as OP posted.

**Comment by Perkolator** [comment] 2023-07-23 12:48
> It is also not possible to open up the launch options again after this unless I restart bottles.

For me, after saving in "change launch options", trying to open it again doesn't work. One has to exit the bottle (**not** bottles itself) and come back, then it works again. Note that after saving launch option for one program, the "change launch options" window opens normally for other programs. Just not the one that was saved.

**Comment by mirkobrombin** [comment] 2023-08-01 22:11
duplicate of #2885 but I keep this since has more details

**Closed** 2023-08-01 22:18 UTC
