### ISSUE TITLE
[Crash report]  cabextract utility not found, 

### ISSUE THREAD

**Issue by arteymix** [bottlesdevs/Bottles#952] opened 2022-01-19 19:26 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.12.28-treviso

**Log**
```python3
cabextract utility not found, please install to use dependencies which need this feature
```

I suspect the dependency is missing from the RPM package on Fedora. I had it fixed by installing it manually.

**Comment by mirkobrombin** [comment] 2022-01-19 19:43
Duplicate of #921

**Closed by mirkobrombin** 2022-01-19 19:43 UTC
