### ISSUE TITLE
[Crash report]  'Office365'  

### ISSUE THREAD

**Issue by brAvEiitoOr** [bottlesdevs/Bottles#703] opened 2021-11-10 17:24 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2021.10.28-treviso

**Log**
```python3
'Office365'  File "/usr/share/bottles/bottles/utils.py", line 298, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/backend/manager.py", line 1178, in async_delete_bottle
    del self.local_bottles[config.get("Path")]

```

**Comment by mirkobrombin** [comment] 2021-11-10 18:28
Duplicate of #676

**Closed by mirkobrombin** 2021-11-10 18:28 UTC
