### ISSUE TITLE
[Bug]: Bottles shows that dxvk is installed even if failed to extract 

### ISSUE THREAD

**Issue by qarmin** [bottlesdevs/Bottles#2395] opened 2022-12-18 07:37 UTC
### Describe the bug

First issue is that latest dxvk-2.0-1-18b0ef6 fails to install/extract.

Second is that, even if installation failed(folder was not created), in logs/gui there is no info about this situation

### To Reproduce

- Just try to install `dxvk-2.0-1-18b0ef6`

https://user-images.githubusercontent.com/41945903/208286780-1ef97e6b-b016-48fe-81ee-416a144dd81d.mp4

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-26-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 12562391040
    Free: 12562243584
RAM:
    MemTotal: 23.4GiB
    MemAvailable: 15.7GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment] 2022-12-18 15:35
Duplicate of #2382

**Closed by mirkobrombin** 2022-12-18 15:35 UTC

**Comment by qarmin** [comment] 2022-12-18 19:43
Well, part about failing to extract archive is duplicate, but other problem is that there is no info that this happened
