### ISSUE TITLE
[BUG] Download fails do not block the installation process resulting in an error

### ISSUE THREAD

**Issue by nozzzdev** [bottlesdevs/Bottles#929] opened 2022-01-14 14:55 UTC
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.1.14-trento

**Log**
```python3
Cab file /home/nolove/.var/app/com.usebottles.bottles/data/bottles/temp/directx_Jun2010_redist/Apr2005_d3dx9_25_x86.cab not found
```

**Comment by mirkobrombin** [comment] 2022-01-14 14:56
Does this path exists? `/home/nolove/.var/app/com.usebottles.bottles/data/bottles/temp/directx_Jun2010_redist`

**Comment by mirkobrombin** [comment] 2022-01-22 09:51
Duplicate of #769

**Closed by mirkobrombin** 2022-01-22 09:51 UTC
