### ISSUE TITLE
Bottles AppImage

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#1272] opened 2022-04-05 20:58 UTC
cc @azubieta (GitHub doesn’t let me to assign the issue)

Bottles’ Appimage has been deprecated due to several issues. Let me make a small summary:

- packages like p7zip and cabextract are not always found even if they are present (in silverblue yes but Ubuntu and Arch no)
- WINE is unable to find winbind and 32bit dependencies (this may be related to the first point, i.e. that what is installed is not detectable by Bottles)
- Caffe (the default runner in Bottles) requires glibc 2.32 or higher
- for the first releases we used a custom script that did not include dependencies https://github.com/bottlesdevs/Bottles/blob/master/appimage-build.sh
- we switched to Appimage builder, this is the recipe which has the above problems https://github.com/bottlesdevs/Bottles/blob/master/AppImageBuilder.yml

Here is the list of necessary dependencies https://github.com/bottlesdevs/Bottles/wiki/Packaging#dependencies

**Comment by probonopd** [comment] 2022-04-05 21:08
> GitHub doesn’t let me to assign the issue

As far as I know, you can only assign to members of the repo/project, but @azubieta will see this.

**Comment by mirkobrombin** [comment] 2022-04-05 21:46
Oh this makes sense 😅

**Comment by mirkobrombin** [comment] 2022-04-06 18:28
Hi! I hope I understand everything well:

- Caffe: distributing runners as Appimage can be a problem because of how Bottles handle runners (it requires these as archives and does some edits). Do you think it is possible to add glibc as a recipe dependency as well?
- winbind: when it is not available, every single operation with WINE will result in `0130:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.`

**Comment by azubieta** [comment] 2022-04-06 19:37
AppImages created with builder already include a copy of glibc at `APPDIR/runtime/compat` at runtime we chdir into that folder and switch back before reaching the target application main so the binaries inside can be executed with the right libc. The issue is that we don't do that on purpose for binaries living outside the APPDIR (coffe in this case).

Regarding winbind, I'm seen those messages so it "should" be fixed now.

**Comment by mirkobrombin** [comment] 2022-04-06 19:46
Nice! I'll test your recipe

**Comment by azubieta** [comment] 2022-04-06 19:50
Oh, the recipe is still broken because of the coffe issue.

**Comment by mirkobrombin** [comment] 2022-04-06 19:55
Right. There is also another problem, `libhandy`. Bottles need 1.6 but Ubuntu 21.10 is stuck with 1.2. I think the Appimage can be built using any distro, right?

**Comment by azubieta** [comment] 2022-04-06 19:59
You could use latest Debian if you want, also you can build libhandy from sources and manually deploy it.

**Comment by TheEvilSkeleton** [comment] 2022-04-09 15:30
Wouldn't it be better to use Arch Linux as a base at this point?

**Comment by srevinsaju** [comment] 2022-04-09 18:59
@mirkobrombin has the AppImage artifacts been removed from the older releases? I don't seem to find the older ones for some reason :(

**Comment by mirkobrombin** [comment] 2022-04-09 19:27
> @mirkobrombin has the AppImage artifacts been removed from the older releases? I don't seem to find the older ones for some reason :(

Hi! yes... we are working to make it works again. Old releases cannot be used due to Bottles repositories changes.

**Comment by mirkobrombin** [comment] 2022-04-09 20:35
I'm trying to build the appimage with arch linux but an exception came up:

```
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 33, in <module>
    sys.exit(load_entry_point('appimage-builder==1.0.0a3', 'console_scripts', 'appimage-builder')())
  File "/usr/lib/python3.10/site-packages/appimagebuilder/__main__.py", line 44, in __main__
    invoker.execute(commands)
  File "/usr/lib/python3.10/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/lib/python3.10/site-packages/appimagebuilder/commands/pacman_deploy.py", line 50, in __call__
    deployed_packages = pacman_deploy.deploy(
  File "/usr/lib/python3.10/site-packages/appimagebuilder/modules/deploy/pacman/deploy.py", line 87, in deploy
    os.symlink("usr/bin", appdir_root / "bin")
FileExistsError: [Errno 17] File exists: 'usr/bin' -> '/var/home/mirko/Projects/bottlesdevs/appimage/AppDir/bin'
```

those are the requested dependencies:

```
  pacman:
    include:
      - lib32-gnutls
      - gtksourceview4
      - hicolor-icon-theme
      - dconf
      - python
      - libhandy
      - gtk3
      - p7zip
      - python-gobject
      - python-requests
      - python-yaml
      - python-markdown
      - cabextract
      - webkit2gtk
      - xorg-xdpyinfo
      - gvfs
      - vkd3d
      - lib32-vkd3d
      - lib32-vulkan-icd-loader
      - vulkan-icd-loader
      - gamemode
```

**Comment by azubieta** [comment] 2022-04-10 17:52
I thought I had fixed that bug, but it seems to strike again, hehehe. Please open an issue at appimage-builder.

Bit the way the bottles recipe is almost ready. But we need to add an install step for Bottles modules. Basically we need to patch the interpreter paths to make the relative using this script: https://gist.github.com/azubieta/202c85f1f5a9e5c6be5cb066fcb2d5e2

**Comment by mirkobrombin** [comment] 2022-04-11 08:54
Ok!

**Comment by azubieta** [comment] 2022-04-11 15:46
> About modules, do you mean the python modules used by Bottles. Right?

I'm referring to all that goes inside `$HOME/.local/share/bottles/`

**Comment by mirkobrombin** [comment] 2022-04-11 16:19
> > About modules, do you mean the python modules used by Bottles. Right?
> 
> I'm referring to all that goes inside `$HOME/.local/share/bottles/`

Those stuff are managed by Bottles itself on first run

**Comment by azubieta** [comment] 2022-04-11 16:36
The thing is that we need those binaries and scripts to be ran with the AppImage ld-linux and interpreters. To do so, the libapprun_hooks performs a chdir to the runtime directory inside the AppDir and executes the binaries from there if the paths are relative they will point to a file inside the AppDir and everything will work.

**Comment by mirkobrombin** [comment] 2022-04-11 18:18
So will those files actually be inside the appimage?

**Comment by azubieta** [comment] 2022-04-11 19:33
> So will those files actually be inside the appimage?

No, they will live in the user home dir (or somewhere else). As I understood they are add-ons so the user can select which ones it will use. The inconvenient here is that once they are patched you will not be able to use then with other non-AppImage installation of Bottles.

**Comment by azubieta** [comment] 2022-04-11 19:33
I just updated the recipe and you should be able to build a Bottles AppImage with the latest appimage-builder (the one in the git main branch)

**Comment by mirkobrombin** [comment] 2022-04-11 19:53
> > So will those files actually be inside the appimage?
> 
> No, they will live in the user home dir (or somewhere else). As I understood they are add-ons so the user can select which ones it will use. The inconvenient here is that once they are patched you will not be able to use then with other non-AppImage installation of Bottles.

oh ok ok



> I just updated the recipe and you should be able to build a Bottles AppImage with the latest appimage-builder (the one in the git main branch)

nice! I'll set up the github action too

**Comment by mirkobrombin** [comment] 2022-04-13 13:08
I've updated the Github workflow according to your Dockerfile: https://github.com/mirkobrombin/Bottles/blob/master/.github/workflows/build_pkgs_unstable.yml

but it fails:
```
mkdir -p AppDir/usr/share/locale/$lang/LC_MESSAGES
msgfmt -o AppDir/usr/share/locale/$lang/LC_MESSAGES/bottles.mo po/$lang.po
done
cp -a data/icons AppDir/usr/share
mv AppDir/usr/share/icons/symbolic/scalable/apps/*.svg AppDir/usr/share/icons/hicolor/scalable/apps/
cp build/data/com.usebottles.bottles.desktop AppDir/usr/share/applications/
cp data/com.usebottles.bottles.gschema.xml AppDir/usr/share/glib-2.0/schemas/com.usebottles.bottles.gschema.xml
glib-compile-schemas AppDir/usr/share/glib-2.0/schemas/
cp -a data/com.usebottles.bottles.appdata.xml.in AppDir/usr/share/metainfo/com.usebottles.bottles.appdata.xml
mkdir -p $APPDIR/bin
ln -s bash $APPDIR/bin/sh
ln: failed to create symbolic link '/bin/sh': File exists
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.10/dist-packages/appimagebuilder/__main__.py", line 44, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.10/dist-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/local/lib/python3.10/dist-packages/appimagebuilder/commands/run_script.py", line 69, in __call__
    raise RuntimeError("Script exited with code: %s" % _proc.returncode)
RuntimeError: Script exited with code: 1
```

**Comment by azubieta** [comment] 2022-04-13 15:23
Use `ln -sf` to override any existent link also make sure that the target dir exists.

**Comment by mirkobrombin** [comment] 2022-04-13 15:52
I’ve replicated your docker image in the workflow to avoid GitHub stuff and use the latest version of Ubuntu as in your 🤔

updated using -sf

**Comment by mirkobrombin** [comment] 2022-04-13 16:48
🥳 https://github.com/bottlesdevs/Bottles/actions/runs/2162408389

**Comment by probonopd** [comment] 2022-04-14 06:54
OK, I am a bit un an unusual setup (FreeBSD with Linuxulator and a Debian runtime) but I am getting:

```
FreeBSD% runappimage ./Bottles-devel-x86_64.AppImage 
AppDir                          com.usebottles.bottles.desktop  runtime
AppRun                          com.usebottles.bottles.svg      sbin
AppRun.env                      etc                             usr
bin                             lib                             var
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (cannot stat shared object): ignored.
/tmp/appimage.CRe4qj03//usr/bin/python3.9: error while loading shared libraries: libm.so.6: cannot stat shared object: Invalid argument
```

**Comment by mirkobrombin** [comment] 2022-04-14 07:12
What an interesting setup ahah Yes it definitely need more testing. On my side it raise some SSL errors but there may be other problems.

**Comment by azubieta** [comment] 2022-04-14 16:53
`ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (cannot stat shared object): ignored.`

This error could be for two reasons the AppImage runtime wasn't removed on a external app call or we are missing a copy of libapprun_hooks.so for one arch. 

`/tmp/appimage.CRe4qj03//usr/bin/python3.9: error while loading shared libraries: libm.so.6: cannot stat shared object: Invalid argument`

This could be a byproduct of the above error.

`On my side it raise some SSL errors but there may be other problems.`

In appimage-builder I bundle a copy of ssl certificates from the certifi package. This could be a solution here. Please share the system you are running to reproduce.

**Comment by probonopd** [comment] 2022-04-15 06:34
...which might well be a byproduct of using the FreeBSD Linuxulator... how would I go about testing/debugging this systematically?

**Comment by mirkobrombin** [comment] 2022-04-15 08:31
For reference, the SSL error:

```
Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt  File "/usr/share/bottles/bottles/utils/threading.py", line 64, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/window.py", line 259, in check_first_run
    mng = Manager(window)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 116, in __init__
    self.checks(install_latest=False, first_run=True)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 132, in checks
    self.organize_components()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 235, in organize_components
    self.check_winebridge(install_latest=True, update=True)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 396, in check_winebridge
    self.component_manager.install(

  File "/usr/share/bottles/bottles/backend/managers/component.py", line 356, in install
    download = self.download(

  File "/usr/share/bottles/bottles/backend/managers/component.py", line 198, in download
    response = requests.head(

  File "/tmp/.mount_Bottlehl6hLS/usr/lib/python3/dist-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)

  File "/tmp/.mount_Bottlehl6hLS/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/tmp/.mount_Bottlehl6hLS/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "/tmp/.mount_Bottlehl6hLS/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "/tmp/.mount_Bottlehl6hLS/usr/lib/python3/dist-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)

  File "/tmp/.mount_Bottlehl6hLS/usr/lib/python3/dist-packages/requests/adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
```

this hang downloading the winebridge component.

There is also a libhandy related problem:

```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/main.py", line 186, in do_startup
    manager = Handy.StyleManager.get_default()
  File "/tmp/.mount_BottlekVupJu/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Handy' object has no attribute 'StyleManager'
```

the package provided by ubuntu:jammy is ([1.6.1](https://packages.ubuntu.com/jammy/libhandy-1-0)) like on [Arch Linux](https://archlinux.org/packages/extra/x86_64/libhandy/), I think what comes in the app is the wrong version.


OS: Fedora Silverblue 35.

**Comment by mirkobrombin** [comment] 2022-05-06 14:15
Latest build works but is missing p7zip:
```
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.17.3-302.fc36.x86_64
Distro:
    Name: Fedora Linux
    Version: '36'
Tools:
    cabextract: true
    p7zip: false
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

I can see it in `APPDIR/usr/bin` but seems ignored.

**Comment by ivan-hc** [comment] 2022-05-08 17:39
In my use case I would have bypassed the inclusion of p7zip (and other stuff) in the AppImage package by changing this line:
https://github.com/bottlesdevs/Bottles/blob/35b68b52fb00cb0083263a6f489f987641e7fa91/AppRun#L3
this way:

    export PATH="/usr/bin/:$APPDIR/usr/bin/:$PATH"

using the versions installed on the host.

This is an ugly trick, but should work well.

**Comment by ivan-hc** [comment] 2022-05-09 16:21
> But this assumes that p7zip is installed on the host system

il senso è quello.

Personally I would prefer this workaround, in the meantime that does not solve the problem.

**Comment by ivan-hc** [comment] 2022-05-09 17:02
Just seen something weird:
https://github.com/bottlesdevs/Bottles/blob/35b68b52fb00cb0083263a6f489f987641e7fa91/AppRun#L4

I think that (in your case) this should be like this:

    export LD_LIBRARY_PATH="$APPDIR/usr/lib/:$LD_LIBRARY_PATH"

In my AppImages I use:

    export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${LD_LIBRARY_PATH}"

**Comment by mirkobrombin** [comment] 2022-05-09 17:23
```yaml
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

You are a genius ahahah. Thanks!

**Comment by ivan-hc** [comment] 2022-05-09 17:24
È sempre un piacere aiutare un connazionale ;)

**Comment by mirkobrombin** [comment] 2022-05-09 18:04
Sadly setting `LD_LIBRARY_PATH` doesn't works as expected. I was testing in a container which has p7zip installed

**Comment by ivan-hc** [comment] 2022-05-09 18:10
Try to add `/usr/lib/p7zip/`

**Comment by mirkobrombin** [comment] 2022-05-09 18:41
Same behavior

**Comment by ivan-hc** [comment] 2022-05-09 18:51
can I see the output?

**Comment by mirkobrombin** [comment] 2022-05-09 18:57
It's hard to get an output, Bottles checks for it issuing a `which p7zip` (`shutil.which` in python).

**Comment by ivan-hc** [comment] 2022-05-09 19:04
launch the AppImage from a terminal (or share it, I can try to check it for issues)

**Comment by mirkobrombin** [comment] 2022-05-09 19:16
it doesn't raise any related output, Bottles handle the missing p7zip package

**Comment by ivan-hc** [comment] 2022-05-09 19:43
if all the dependences are there, try to include [libunionpreload](https://github.com/project-portable/libunionpreload) in your AppImage, make it executable and add these lines to the AppRun:

    export UNION_PRELOAD="${APPDIR}"
    export LD_PRELOAD="${APPDIR}/libunionpreload.so"

I don't know much about python or any version of python you include into the AppImage, but you may be interested also in:

    export PYTHONPATH="${APPDIR}"/usr/share/pyshared/:"${PYTHONPATH}"
    export PYTHONHOME="${APPDIR}"/usr/:"${PYTHONHOME}"

**Comment by azubieta** [comment] 2022-05-10 04:05
> if all the dependences are there, try to include [libunionpreload](https://github.com/project-portable/libunionpreload) in your AppImage, make it executable and add these lines to the AppRun:

libapprun_hooks already provides the features contained in libunionpreload, check the path mapping feature in the runtime

If python uses the which binary to find the location of other binaries please make sure this is included. If the `which` path is hardcoded use a path_mapping to force it being used from the bundle like this `/usr/bin/which:$APPDIR/usr/bin/which`

**Comment by mirkobrombin** [comment] 2022-05-10 06:12
`which` is not the problem as it is been used by other successful checks.

**Comment by mirkobrombin** [comment] 2022-05-10 07:40
Investigating the `p7zip` package that comes from Ubuntu, the binaries are sh files that have hard-coded paths inside. Using a portable version I fixed the problem and now it is detected.

The new problem is: the binaries are found by `shutil.which` but `subprocess` uses `sh` and it doesn't find them.

**Comment by mirkobrombin** [comment] 2022-05-10 08:29
Binaries in the appimage are not accessible:

```bash
❯ ~/Downloads '/var/home/mirko/Downloads/squashfs-root/usr/bin/7z' 
zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/usr/bin/7z

❯ ~/Downloads '/var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract' 
zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract

❯ ~/Downloads '/var/home/mirko/Downloads/squashfs-root/bin/bash' 
zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/bin/bash
```

the file size is correct while the hash is wrong, idk how it is possible, files gets altered in somehow

**Comment by ivan-hc** [comment] 2022-05-10 09:42
uhm... sometime the $PATH in /usr/bin is symlinked as /bin. This is the template I use in the AppRun:

    export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
maybe the AppDir has both /bin and /usr/bin, that's why it can't see every file.

About p7zip that can't see 7z, the binaries are in /usr/lib/p7zip/, if it can't detect them, try to replace the /usr/bin/7z script with it.
However, the solution I've provided with the $PATH line above should be enough.

**Comment by mirkobrombin** [comment] 2022-05-10 09:48
p7zip is no more a problem, all utilities are present and detected by `shutil.which`, the problem now is: 

> Files in the appimage `/bin` and `/usr/bin` are not accessible:
> 
> ```shell
> ❯ ~/Downloads '/var/home/mirko/Downloads/squashfs-root/usr/bin/7z' 
> zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/usr/bin/7z
> 
> ❯ ~/Downloads '/var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract' 
> zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract
> 
> ❯ ~/Downloads '/var/home/mirko/Downloads/squashfs-root/bin/bash' 
> zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/bin/bash
> 
> 
> ❯ ~/Downloads ls -l '/var/home/mirko/Downloads/squashfs-root/usr/bin/7z'      
> -rwxr-xr-x. 1 mirko mirko 548320 May 10 10:22 /var/home/mirko/Downloads/squashfs-root/usr/bin/7z
> 
> ❯ ~/Downloads ls -l '/var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract' 
> -rwxr-xr-x. 1 mirko mirko 38424 May 10 10:22 /var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract
> 
> ❯ ~/Downloads ls -l '/var/home/mirko/Downloads/squashfs-root/bin/bash'        
> -rwxr-xr-x. 1 mirko mirko 1416272 May 10 10:22 /var/home/mirko/Downloads/squashfs-root/bin/bash
> ```
> 
> the file size is correct while the hash is wrong, idk how it is possible, files gets altered in somehow

**Comment by ivan-hc** [comment] 2022-05-10 09:56
My question is: are 7z, cabextract and bash in `$APPDIR/urs/bin/` or are them in `$APPDIR/bin/`?

EDIT: `bash` is in `$APPDIR/bin/`, that is not listed in the AppRun

On Debian the `7z` binary is located in `/usr/lib/p7zip/` and called from the `/usr/bin/7z` script

About `cabextract`, is it executable (I can see it as a binary file, on Debian)?

**Comment by mirkobrombin** [comment] 2022-05-10 11:52
It is not a problem of location but of file corruption. If I extract the appimage and try them, they don't work, if I replace them with the local copy, they work.

**Comment by azubieta** [comment] 2022-05-10 14:56
> zsh: no such file or directory: /var/home/mirko/Downloads/squashfs-root/usr/bin/cabextract

This error is provably because zsh is not being ran with the AppDir environment. This happens when the execution flow exits the AppDir. `libapprun_hooks` remove the whole private environment to avoid polluting the system binaries. So we need to locate which binary outside the bundle is being executed and move it inside our bundle so the context is preserved all the time. Pay special attention to scripts interpreters or other fixed paths.

**Comment by mirkobrombin** [comment] 2022-05-10 15:59
Just for context: I've tried with bash and sh too.

I think I don't understand what you mean, I tried extracting the appimage and starting 7z (which is standalone) from there and it gave me that result (in my environment, on host). Is it correct that it doesn't work?

**Comment by mirkobrombin** [comment] 2022-05-10 16:49
Find latest build from the GitHub actions artifacts (should be public)

**Comment by mirkobrombin** [comment] 2022-06-10 12:52
Reminder: 2022.6.14 came with GTK4+libadwaita replacing GTK3+libhandy

**Comment by mirkobrombin** [comment] 2022-06-27 11:00
Need fix:
- [ ] cabextract doesn't works

**Comment by azubieta** [comment] 2022-06-27 15:39
>  cabextract doesn't works (bin need to be patched?)

If it's a Linux binary, yes

**Comment by mirkobrombin** [comment] 2022-06-27 17:15
Ty

**Comment by mirkobrombin** [comment] 2022-07-31 14:29
Idk what I'm doing wrong but I'm not able to get the patcher path
https://github.com/bottlesdevs/Bottles/runs/7599170503?check_suite_focus=true#step:6:2718

**Comment by azubieta** [comment] 2022-08-01 16:13
I seems that you're trying to patch binaries/scripts inside your AppDir, this is not necessary as it's already done by appimage-builder. The `appimage_module_patcher` script is meant to be on files located outside your AppDir like the wine binaries that bottles download.

**Comment by mirkobrombin** [comment] 2022-08-01 16:56
Then I don't understand why cabextract (installed in the appimage during the build process) doesn't work

**Comment by azubieta** [comment] 2022-08-01 17:00
> Then I don't understand why cabextract (installed in the appimage during the build process) doesn't work

Could you please provide an AppImage for me to look at it?

**Comment by mirkobrombin** [comment] 2022-08-01 17:05
This is the latest successful build https://github.com/bottlesdevs/Bottles/actions/runs/2769548912

**Comment by cat-master21** [comment] 2022-08-01 17:25
The appimage does contain easyterm, `easyterm.py`. You can check it yourself by extracting the appimage.

**Comment by mirkobrombin** [comment] 2022-08-01 17:26
> The appimage does contain easyterm, `easyterm.py`. You can check it yourself by extracting the appimage.

I may have configured the build recipe badly

**Comment by cat-master21** [comment] 2022-08-01 17:32
As for the `appimage_module_patcher` script will existing binaries still be compatable outside of the appimage @azubieta? This may require some code in bottles to run the script after extracting the runner but before running Wine. That is if the binaries are still compatable because this may mess up say, if ran in the flatpak in which it isn't needed.

**Comment by azubieta** [comment] 2022-08-01 18:31
> will existing binaries still be compatable outside of the appimage

No, the patch needs to be reverted in order to allow that (which should not be complicated). As an alternative you could use a different prefix for the AppImage related modules.

**Comment by cat-master21** [comment] 2022-08-01 20:38
Well @azubieta I manually tried your `appimage_module_patcher` and I now get 
`/bin/sh: line 1: /home/pumkinking/.local/share/bottles/runners/soda-7.0-2/bin/wine64: No such file or directory`
and it is definitely right there odly.

**Comment by azubieta** [comment] 2022-08-01 21:26
> definitely right there odly

The error message is misleading (thank to the Linux developers there) what is missing is the wine64 interpreter path.

The script makes all the interpreter paths relative. For example It changes `/bin/bash` to `bin/bash` without the first `/` which allows us to control which interpreter get used at runtime by changing the running directory. In order to run a patched binary you can chdir to `/` or to `AppDir/opt/glibc` (if you have a bottles AppImage at hand).

**Comment by TheEvilSkeleton** [comment] 2022-09-27 03:01
> So I have been quite busy lately but here is a status report if anybody wants to pick it up. Wine doesn't work because it tries and manually find ld with a set path. This might be rpath do not know. I tried running the library patcher that appimage builder uses but still same issue.

_Originally posted by @cat-master21 in https://github.com/bottlesdevs/Bottles/issues/1646#issuecomment-1258862643_

**Comment by TheEvilSkeleton** [comment] 2022-10-01 21:02
I'm unpinning this issue because the movement has stalled. Should someone volunteer to create an appimage and continue the work, we will consider pinning this issue again.

**Comment by TheEvilSkeleton** [comment] 2022-12-26 18:28
As of https://github.com/bottlesdevs/Bottles/pull/2430, we removed all references of AppImage, as we are not considering maintaining another format. For now, we're only going maintain and stick with Flatpak. Sorry.

**Closed by TheEvilSkeleton** 2022-12-26 18:28 UTC
Labels: Packaging
